/**
 * Auto-generert komplett rute-katalog (portal + admin + auth + booking + foreldre).
 * Generert av scripts/extract-routes.ts. Ikke rediger manuelt.
 */

export type AllRouteEntry = {
  route: string;
  label: string;
  category: string;
  filePath: string;
};

export const ALL_ROUTES: AllRouteEntry[] = [
  { route: "/admin", label: "Admin", category: "AgencyOS", filePath: "src/app/admin/page.tsx" },
  { route: "/admin/agencyos", label: "Agencyos", category: "AgencyOS", filePath: "src/app/admin/agencyos/page.tsx" },
  { route: "/admin/agencyos/caddie", label: "Caddie", category: "AgencyOS", filePath: "src/app/admin/agencyos/caddie/page.tsx" },
  { route: "/admin/agencyos/caddie/aktivitet", label: "Aktivitet", category: "AgencyOS", filePath: "src/app/admin/agencyos/caddie/aktivitet/page.tsx" },
  { route: "/admin/agencyos/okonomi", label: "Okonomi", category: "AgencyOS", filePath: "src/app/admin/agencyos/okonomi/page.tsx" },
  { route: "/admin/agencyos/spillere", label: "Spillere", category: "AgencyOS", filePath: "src/app/admin/agencyos/spillere/page.tsx" },
  { route: "/admin/agencyos/uka", label: "Uka", category: "AgencyOS", filePath: "src/app/admin/agencyos/uka/page.tsx" },
  { route: "/admin/agents", label: "Agents", category: "AgencyOS", filePath: "src/app/admin/agents/page.tsx" },
  { route: "/admin/agents/[agentId]", label: "agents · detalj", category: "AgencyOS", filePath: "src/app/admin/agents/[agentId]/page.tsx" },
  { route: "/admin/analyse", label: "Analyse", category: "AgencyOS", filePath: "src/app/admin/analyse/page.tsx" },
  { route: "/admin/analysere", label: "Analysere", category: "AgencyOS", filePath: "src/app/admin/analysere/page.tsx" },
  { route: "/admin/anlegg", label: "Anlegg", category: "AgencyOS", filePath: "src/app/admin/anlegg/page.tsx" },
  { route: "/admin/anlegg/[id]", label: "anlegg · detalj", category: "AgencyOS", filePath: "src/app/admin/anlegg/[id]/page.tsx" },
  { route: "/admin/approvals", label: "Approvals", category: "AgencyOS", filePath: "src/app/admin/approvals/page.tsx" },
  { route: "/admin/approvals/[id]", label: "approvals · detalj", category: "AgencyOS", filePath: "src/app/admin/approvals/[id]/page.tsx" },
  { route: "/admin/audit-log", label: "Audit log", category: "AgencyOS", filePath: "src/app/admin/audit-log/page.tsx" },
  { route: "/admin/audit-log/[id]", label: "audit-log · detalj", category: "AgencyOS", filePath: "src/app/admin/audit-log/[id]/page.tsx" },
  { route: "/admin/availability", label: "Availability", category: "AgencyOS", filePath: "src/app/admin/availability/page.tsx" },
  { route: "/admin/board", label: "Board", category: "AgencyOS", filePath: "src/app/admin/board/page.tsx" },
  { route: "/admin/bookinger", label: "Bookinger", category: "AgencyOS · Booking", filePath: "src/app/admin/bookinger/page.tsx" },
  { route: "/admin/brief", label: "Brief", category: "AgencyOS", filePath: "src/app/admin/brief/page.tsx" },
  { route: "/admin/calendar", label: "Calendar", category: "AgencyOS", filePath: "src/app/admin/calendar/page.tsx" },
  { route: "/admin/calendar/maned", label: "Maned", category: "AgencyOS", filePath: "src/app/admin/calendar/maned/page.tsx" },
  { route: "/admin/coach-workbench", label: "Coach workbench", category: "AgencyOS", filePath: "src/app/admin/coach-workbench/page.tsx" },
  { route: "/admin/drills", label: "Drills", category: "AgencyOS", filePath: "src/app/admin/drills/page.tsx" },
  { route: "/admin/drills/[id]", label: "drills · detalj", category: "AgencyOS", filePath: "src/app/admin/drills/[id]/page.tsx" },
  { route: "/admin/drills/[id]/rediger", label: "Rediger", category: "AgencyOS", filePath: "src/app/admin/drills/[id]/rediger/page.tsx" },
  { route: "/admin/email-templates", label: "Email templates", category: "AgencyOS", filePath: "src/app/admin/email-templates/page.tsx" },
  { route: "/admin/email-templates/[id]/rediger", label: "Rediger", category: "AgencyOS", filePath: "src/app/admin/email-templates/[id]/rediger/page.tsx" },
  { route: "/admin/finance", label: "Finance", category: "AgencyOS", filePath: "src/app/admin/finance/page.tsx" },
  { route: "/admin/foresporsler", label: "Foresporsler", category: "AgencyOS", filePath: "src/app/admin/foresporsler/page.tsx" },
  { route: "/admin/gjennomfore", label: "Gjennomfore", category: "AgencyOS", filePath: "src/app/admin/gjennomfore/page.tsx" },
  { route: "/admin/gjennomfore/okter/[id]", label: "okter · detalj", category: "AgencyOS", filePath: "src/app/admin/gjennomfore/okter/[id]/page.tsx" },
  { route: "/admin/godkjenninger", label: "Godkjenninger", category: "AgencyOS · Godkjenning", filePath: "src/app/admin/godkjenninger/page.tsx" },
  { route: "/admin/grupper", label: "Grupper", category: "AgencyOS", filePath: "src/app/admin/grupper/page.tsx" },
  { route: "/admin/grupper/[id]", label: "grupper · detalj", category: "AgencyOS", filePath: "src/app/admin/grupper/[id]/page.tsx" },
  { route: "/admin/hjelp", label: "Hjelp", category: "AgencyOS", filePath: "src/app/admin/hjelp/page.tsx" },
  { route: "/admin/innboks", label: "Innboks", category: "AgencyOS", filePath: "src/app/admin/innboks/page.tsx" },
  { route: "/admin/integrasjoner", label: "Integrasjoner", category: "AgencyOS", filePath: "src/app/admin/integrasjoner/page.tsx" },
  { route: "/admin/kalender", label: "Kalender", category: "AgencyOS · Kalender", filePath: "src/app/admin/kalender/page.tsx" },
  { route: "/admin/kalender/maned", label: "Maned", category: "AgencyOS · Kalender", filePath: "src/app/admin/kalender/maned/page.tsx" },
  { route: "/admin/kalender/uke", label: "Uke", category: "AgencyOS · Kalender", filePath: "src/app/admin/kalender/uke/page.tsx" },
  { route: "/admin/kapasitet", label: "Kapasitet", category: "AgencyOS", filePath: "src/app/admin/kapasitet/page.tsx" },
  { route: "/admin/klubb/innstillinger", label: "Innstillinger", category: "AgencyOS", filePath: "src/app/admin/klubb/innstillinger/page.tsx" },
  { route: "/admin/kommunikasjon", label: "Kommunikasjon", category: "AgencyOS", filePath: "src/app/admin/kommunikasjon/page.tsx" },
  { route: "/admin/lag-snitt", label: "Lag snitt", category: "AgencyOS", filePath: "src/app/admin/lag-snitt/page.tsx" },
  { route: "/admin/messages", label: "Messages", category: "AgencyOS", filePath: "src/app/admin/messages/page.tsx" },
  { route: "/admin/okter", label: "Okter", category: "AgencyOS", filePath: "src/app/admin/okter/page.tsx" },
  { route: "/admin/oppfolging", label: "Oppfolging", category: "AgencyOS", filePath: "src/app/admin/oppfolging/page.tsx" },
  { route: "/admin/organisasjon", label: "Organisasjon", category: "AgencyOS", filePath: "src/app/admin/organisasjon/page.tsx" },
  { route: "/admin/plan-templates", label: "Plan templates", category: "AgencyOS", filePath: "src/app/admin/plan-templates/page.tsx" },
  { route: "/admin/plan-templates/[id]", label: "plan-templates · detalj", category: "AgencyOS", filePath: "src/app/admin/plan-templates/[id]/page.tsx" },
  { route: "/admin/plan-templates/[id]/rediger", label: "Rediger", category: "AgencyOS", filePath: "src/app/admin/plan-templates/[id]/rediger/page.tsx" },
  { route: "/admin/plan-templates/ny", label: "Ny", category: "AgencyOS", filePath: "src/app/admin/plan-templates/ny/page.tsx" },
  { route: "/admin/planlegge", label: "Planlegge", category: "AgencyOS", filePath: "src/app/admin/planlegge/page.tsx" },
  { route: "/admin/plans", label: "Plans", category: "AgencyOS · Planer", filePath: "src/app/admin/plans/page.tsx" },
  { route: "/admin/plans/[planId]", label: "plans · detalj", category: "AgencyOS · Planer", filePath: "src/app/admin/plans/[planId]/page.tsx" },
  { route: "/admin/plans/new", label: "New", category: "AgencyOS · Planer", filePath: "src/app/admin/plans/new/page.tsx" },
  { route: "/admin/plans/templates", label: "Templates", category: "AgencyOS · Planer", filePath: "src/app/admin/plans/templates/page.tsx" },
  { route: "/admin/plans/templates/[id]/effectiveness", label: "Effectiveness", category: "AgencyOS · Planer", filePath: "src/app/admin/plans/templates/[id]/effectiveness/page.tsx" },
  { route: "/admin/plans/templates/[id]/rediger", label: "Rediger", category: "AgencyOS · Planer", filePath: "src/app/admin/plans/templates/[id]/rediger/page.tsx" },
  { route: "/admin/plans/templates/ny", label: "Ny", category: "AgencyOS · Planer", filePath: "src/app/admin/plans/templates/ny/page.tsx" },
  { route: "/admin/profile", label: "Profile", category: "AgencyOS", filePath: "src/app/admin/profile/page.tsx" },
  { route: "/admin/queue", label: "Queue", category: "AgencyOS", filePath: "src/app/admin/queue/page.tsx" },
  { route: "/admin/reach", label: "Reach", category: "AgencyOS", filePath: "src/app/admin/reach/page.tsx" },
  { route: "/admin/recording", label: "Recording", category: "AgencyOS", filePath: "src/app/admin/recording/page.tsx" },
  { route: "/admin/reports", label: "Reports", category: "AgencyOS", filePath: "src/app/admin/reports/page.tsx" },
  { route: "/admin/runder", label: "Runder", category: "AgencyOS", filePath: "src/app/admin/runder/page.tsx" },
  { route: "/admin/services", label: "Services", category: "AgencyOS · Tjenester", filePath: "src/app/admin/services/page.tsx" },
  { route: "/admin/settings", label: "Settings", category: "AgencyOS", filePath: "src/app/admin/settings/page.tsx" },
  { route: "/admin/settings/api", label: "Api", category: "AgencyOS", filePath: "src/app/admin/settings/api/page.tsx" },
  { route: "/admin/settings/calendar", label: "Calendar", category: "AgencyOS", filePath: "src/app/admin/settings/calendar/page.tsx" },
  { route: "/admin/settings/security", label: "Security", category: "AgencyOS", filePath: "src/app/admin/settings/security/page.tsx" },
  { route: "/admin/settings/tilgang", label: "Tilgang", category: "AgencyOS", filePath: "src/app/admin/settings/tilgang/page.tsx" },
  { route: "/admin/spillere", label: "Spillere", category: "AgencyOS · Spillere", filePath: "src/app/admin/spillere/page.tsx" },
  { route: "/admin/spillere/[id]", label: "spillere · detalj", category: "AgencyOS · Spillere", filePath: "src/app/admin/spillere/[id]/page.tsx" },
  { route: "/admin/spillere/[id]/plan/[planId]", label: "plan · detalj", category: "AgencyOS · Spillere", filePath: "src/app/admin/spillere/[id]/plan/[planId]/page.tsx" },
  { route: "/admin/spillere/[id]/profil", label: "Profil", category: "AgencyOS · Spillere", filePath: "src/app/admin/spillere/[id]/profil/page.tsx" },
  { route: "/admin/spillere/[id]/rediger", label: "Rediger", category: "AgencyOS · Spillere", filePath: "src/app/admin/spillere/[id]/rediger/page.tsx" },
  { route: "/admin/spillere/[id]/tester", label: "Tester", category: "AgencyOS · Spillere", filePath: "src/app/admin/spillere/[id]/tester/page.tsx" },
  { route: "/admin/spillere/[id]/tildel-test", label: "Tildel test", category: "AgencyOS · Spillere", filePath: "src/app/admin/spillere/[id]/tildel-test/page.tsx" },
  { route: "/admin/spillere/[id]/workbench", label: "Workbench", category: "AgencyOS · Spillere", filePath: "src/app/admin/spillere/[id]/workbench/page.tsx" },
  { route: "/admin/spillere/ny", label: "Ny", category: "AgencyOS · Spillere", filePath: "src/app/admin/spillere/ny/page.tsx" },
  { route: "/admin/stats/moderering", label: "Moderering", category: "AgencyOS", filePath: "src/app/admin/stats/moderering/page.tsx" },
  { route: "/admin/stats/overview", label: "Overview", category: "AgencyOS", filePath: "src/app/admin/stats/overview/page.tsx" },
  { route: "/admin/talent", label: "Talent", category: "AgencyOS", filePath: "src/app/admin/talent/page.tsx" },
  { route: "/admin/talent/[playerId]", label: "talent · detalj", category: "AgencyOS", filePath: "src/app/admin/talent/[playerId]/page.tsx" },
  { route: "/admin/talent/discovery", label: "Discovery", category: "AgencyOS", filePath: "src/app/admin/talent/discovery/page.tsx" },
  { route: "/admin/talent/kohort", label: "Kohort", category: "AgencyOS", filePath: "src/app/admin/talent/kohort/page.tsx" },
  { route: "/admin/talent/radar", label: "Radar", category: "AgencyOS", filePath: "src/app/admin/talent/radar/page.tsx" },
  { route: "/admin/talent/radar/[playerId]", label: "radar · detalj", category: "AgencyOS", filePath: "src/app/admin/talent/radar/[playerId]/page.tsx" },
  { route: "/admin/talent/region", label: "Region", category: "AgencyOS", filePath: "src/app/admin/talent/region/page.tsx" },
  { route: "/admin/talent/ressurser", label: "Ressurser", category: "AgencyOS", filePath: "src/app/admin/talent/ressurser/page.tsx" },
  { route: "/admin/talent/sammenligning", label: "Sammenligning", category: "AgencyOS", filePath: "src/app/admin/talent/sammenligning/page.tsx" },
  { route: "/admin/talent/wagr-benchmark", label: "Wagr benchmark", category: "AgencyOS", filePath: "src/app/admin/talent/wagr-benchmark/page.tsx" },
  { route: "/admin/talent/wagr-import", label: "Wagr import", category: "AgencyOS", filePath: "src/app/admin/talent/wagr-import/page.tsx" },
  { route: "/admin/team", label: "Team", category: "AgencyOS · Team", filePath: "src/app/admin/team/page.tsx" },
  { route: "/admin/team/inviter", label: "Inviter", category: "AgencyOS · Team", filePath: "src/app/admin/team/inviter/page.tsx" },
  { route: "/admin/teknisk-plan", label: "Teknisk plan", category: "AgencyOS", filePath: "src/app/admin/teknisk-plan/page.tsx" },
  { route: "/admin/teknisk-plan/[spillerId]", label: "teknisk-plan · detalj", category: "AgencyOS", filePath: "src/app/admin/teknisk-plan/[spillerId]/page.tsx" },
  { route: "/admin/tester", label: "Tester", category: "AgencyOS", filePath: "src/app/admin/tester/page.tsx" },
  { route: "/admin/tester/[id]", label: "tester · detalj", category: "AgencyOS", filePath: "src/app/admin/tester/[id]/page.tsx" },
  { route: "/admin/tester/foreslatte", label: "Foreslatte", category: "AgencyOS", filePath: "src/app/admin/tester/foreslatte/page.tsx" },
  { route: "/admin/tester/tildel/[spillerId]", label: "tildel · detalj", category: "AgencyOS", filePath: "src/app/admin/tester/tildel/[spillerId]/page.tsx" },
  { route: "/admin/tilstander", label: "Tilstander", category: "AgencyOS", filePath: "src/app/admin/tilstander/page.tsx" },
  { route: "/admin/tournaments", label: "Tournaments", category: "AgencyOS", filePath: "src/app/admin/tournaments/page.tsx" },
  { route: "/admin/tournaments/[id]", label: "tournaments · detalj", category: "AgencyOS", filePath: "src/app/admin/tournaments/[id]/page.tsx" },
  { route: "/admin/tournaments/dubletter", label: "Dubletter", category: "AgencyOS", filePath: "src/app/admin/tournaments/dubletter/page.tsx" },
  { route: "/admin/tournaments/ny", label: "Ny", category: "AgencyOS", filePath: "src/app/admin/tournaments/ny/page.tsx" },
  { route: "/admin/trackman", label: "Trackman", category: "AgencyOS", filePath: "src/app/admin/trackman/page.tsx" },
  { route: "/admin/videoer", label: "Videoer", category: "AgencyOS", filePath: "src/app/admin/videoer/page.tsx" },
  { route: "/admin/workspace", label: "Workspace", category: "AgencyOS", filePath: "src/app/admin/workspace/page.tsx" },
  { route: "/admin/workspace/notion", label: "Notion", category: "AgencyOS", filePath: "src/app/admin/workspace/notion/page.tsx" },
  { route: "/admin/workspace/oppgaver", label: "Oppgaver", category: "AgencyOS", filePath: "src/app/admin/workspace/oppgaver/page.tsx" },
  { route: "/admin/workspace/oppgaver/[id]", label: "oppgaver · detalj", category: "AgencyOS", filePath: "src/app/admin/workspace/oppgaver/[id]/page.tsx" },
  { route: "/admin/workspace/prosjekter", label: "Prosjekter", category: "AgencyOS", filePath: "src/app/admin/workspace/prosjekter/page.tsx" },
  { route: "/admin/workspace/tildelt-meg", label: "Tildelt meg", category: "AgencyOS", filePath: "src/app/admin/workspace/tildelt-meg/page.tsx" },
  { route: "/auth/bankid", label: "Bankid", category: "Auth", filePath: "src/app/auth/bankid/page.tsx" },
  { route: "/auth/check-email", label: "Check email", category: "Auth", filePath: "src/app/auth/check-email/page.tsx" },
  { route: "/auth/forgot-password", label: "Forgot password", category: "Auth", filePath: "src/app/auth/forgot-password/page.tsx" },
  { route: "/auth/guardian-consent/[token]", label: "guardian-consent · detalj", category: "Auth", filePath: "src/app/auth/guardian-consent/[token]/page.tsx" },
  { route: "/auth/logget-ut", label: "Logget ut", category: "Auth", filePath: "src/app/auth/logget-ut/page.tsx" },
  { route: "/auth/login", label: "Login", category: "Auth", filePath: "src/app/auth/login/page.tsx" },
  { route: "/auth/onboarding", label: "Onboarding", category: "Auth", filePath: "src/app/auth/onboarding/page.tsx" },
  { route: "/auth/onboarding/forelder", label: "Forelder", category: "Auth", filePath: "src/app/auth/onboarding/forelder/page.tsx" },
  { route: "/auth/reset-password", label: "Reset password", category: "Auth", filePath: "src/app/auth/reset-password/page.tsx" },
  { route: "/auth/samtykke-venter", label: "Samtykke venter", category: "Auth", filePath: "src/app/auth/samtykke-venter/page.tsx" },
  { route: "/auth/signup", label: "Signup", category: "Auth", filePath: "src/app/auth/signup/page.tsx" },
  { route: "/forelder", label: "Forelder", category: "Foreldreportal", filePath: "src/app/forelder/page.tsx" },
  { route: "/forelder/barn", label: "Barn", category: "Foreldreportal", filePath: "src/app/forelder/barn/page.tsx" },
  { route: "/forelder/barn/[childId]", label: "barn · detalj", category: "Foreldreportal", filePath: "src/app/forelder/barn/[childId]/page.tsx" },
  { route: "/forelder/bookinger", label: "Bookinger", category: "Foreldreportal", filePath: "src/app/forelder/bookinger/page.tsx" },
  { route: "/forelder/coach", label: "Coach", category: "Foreldreportal", filePath: "src/app/forelder/coach/page.tsx" },
  { route: "/forelder/fakturaer", label: "Fakturaer", category: "Foreldreportal", filePath: "src/app/forelder/fakturaer/page.tsx" },
  { route: "/forelder/innstillinger", label: "Innstillinger", category: "Foreldreportal", filePath: "src/app/forelder/innstillinger/page.tsx" },
  { route: "/forelder/okonomi", label: "Okonomi", category: "Foreldreportal", filePath: "src/app/forelder/okonomi/page.tsx" },
  { route: "/forelder/samtykke", label: "Samtykke", category: "Foreldreportal", filePath: "src/app/forelder/samtykke/page.tsx" },
  { route: "/forelder/ukerapport", label: "Ukerapport", category: "Foreldreportal", filePath: "src/app/forelder/ukerapport/page.tsx" },
  { route: "/forelder/varsler", label: "Varsler", category: "Foreldreportal", filePath: "src/app/forelder/varsler/page.tsx" },
  { route: "/portal", label: "Portal", category: "PlayerHQ", filePath: "src/app/portal/page.tsx" },
  { route: "/portal/agent-pipeline", label: "Agent pipeline", category: "PlayerHQ", filePath: "src/app/portal/agent-pipeline/page.tsx" },
  { route: "/portal/ai/foresla-drill", label: "Foresla drill", category: "PlayerHQ", filePath: "src/app/portal/ai/foresla-drill/page.tsx" },
  { route: "/portal/ai/foresla-turnering", label: "Foresla turnering", category: "PlayerHQ", filePath: "src/app/portal/ai/foresla-turnering/page.tsx" },
  { route: "/portal/ai/mal-bygger", label: "Mal bygger", category: "PlayerHQ", filePath: "src/app/portal/ai/mal-bygger/page.tsx" },
  { route: "/portal/analyse", label: "Analyse", category: "PlayerHQ", filePath: "src/app/portal/analyse/page.tsx" },
  { route: "/portal/analysere", label: "Analysere", category: "PlayerHQ · Analysere", filePath: "src/app/portal/analysere/page.tsx" },
  { route: "/portal/booking", label: "Booking", category: "PlayerHQ · Booking", filePath: "src/app/portal/booking/page.tsx" },
  { route: "/portal/booking/[bookingId]", label: "booking · detalj", category: "PlayerHQ · Booking", filePath: "src/app/portal/booking/[bookingId]/page.tsx" },
  { route: "/portal/booking/anlegg/[anleggId]", label: "anlegg · detalj", category: "PlayerHQ · Booking", filePath: "src/app/portal/booking/anlegg/[anleggId]/page.tsx" },
  { route: "/portal/booking/bekreftet", label: "Bekreftet", category: "PlayerHQ · Booking", filePath: "src/app/portal/booking/bekreftet/page.tsx" },
  { route: "/portal/booking/coach/[coachId]", label: "coach · detalj", category: "PlayerHQ · Booking", filePath: "src/app/portal/booking/coach/[coachId]/page.tsx" },
  { route: "/portal/booking/ny", label: "Ny", category: "PlayerHQ · Booking", filePath: "src/app/portal/booking/ny/page.tsx" },
  { route: "/portal/booking/ny/bekreft", label: "Bekreft", category: "PlayerHQ · Booking", filePath: "src/app/portal/booking/ny/bekreft/page.tsx" },
  { route: "/portal/coach", label: "Coach", category: "PlayerHQ · Coach", filePath: "src/app/portal/coach/page.tsx" },
  { route: "/portal/coach/[coachId]", label: "coach · detalj", category: "PlayerHQ · Coach", filePath: "src/app/portal/coach/[coachId]/page.tsx" },
  { route: "/portal/coach/ai", label: "Ai", category: "PlayerHQ · Coach", filePath: "src/app/portal/coach/ai/page.tsx" },
  { route: "/portal/coach/melding", label: "Melding", category: "PlayerHQ · Coach", filePath: "src/app/portal/coach/melding/page.tsx" },
  { route: "/portal/coach/melding/[id]", label: "melding · detalj", category: "PlayerHQ · Coach", filePath: "src/app/portal/coach/melding/[id]/page.tsx" },
  { route: "/portal/coach/melding/[id]/vedlegg", label: "Vedlegg", category: "PlayerHQ · Coach", filePath: "src/app/portal/coach/melding/[id]/vedlegg/page.tsx" },
  { route: "/portal/coach/melding/ny", label: "Ny", category: "PlayerHQ · Coach", filePath: "src/app/portal/coach/melding/ny/page.tsx" },
  { route: "/portal/coach/notes", label: "Notes", category: "PlayerHQ · Coach", filePath: "src/app/portal/coach/notes/page.tsx" },
  { route: "/portal/coach/notes/[noteId]", label: "notes · detalj", category: "PlayerHQ · Coach", filePath: "src/app/portal/coach/notes/[noteId]/page.tsx" },
  { route: "/portal/coach/ovelser", label: "Ovelser", category: "PlayerHQ · Coach", filePath: "src/app/portal/coach/ovelser/page.tsx" },
  { route: "/portal/coach/ovelser/[id]/rediger", label: "Rediger", category: "PlayerHQ · Coach", filePath: "src/app/portal/coach/ovelser/[id]/rediger/page.tsx" },
  { route: "/portal/coach/ovelser/ny", label: "Ny", category: "PlayerHQ · Coach", filePath: "src/app/portal/coach/ovelser/ny/page.tsx" },
  { route: "/portal/coach/plans", label: "Plans", category: "PlayerHQ · Coach", filePath: "src/app/portal/coach/plans/page.tsx" },
  { route: "/portal/coach/plans/[planId]", label: "plans · detalj", category: "PlayerHQ · Coach", filePath: "src/app/portal/coach/plans/[planId]/page.tsx" },
  { route: "/portal/coach/plans/[planId]/ny-okt", label: "Ny okt", category: "PlayerHQ · Coach", filePath: "src/app/portal/coach/plans/[planId]/ny-okt/page.tsx" },
  { route: "/portal/coach/plans/perioder", label: "Perioder", category: "PlayerHQ · Coach", filePath: "src/app/portal/coach/plans/perioder/page.tsx" },
  { route: "/portal/coach/sporsmal/[id]", label: "sporsmal · detalj", category: "PlayerHQ · Coach", filePath: "src/app/portal/coach/sporsmal/[id]/page.tsx" },
  { route: "/portal/coach/videoer", label: "Videoer", category: "PlayerHQ · Coach", filePath: "src/app/portal/coach/videoer/page.tsx" },
  { route: "/portal/drills", label: "Drills", category: "PlayerHQ", filePath: "src/app/portal/drills/page.tsx" },
  { route: "/portal/drills/[id]", label: "drills · detalj", category: "PlayerHQ", filePath: "src/app/portal/drills/[id]/page.tsx" },
  { route: "/portal/gjennomfore", label: "Gjennomfore", category: "PlayerHQ · Gjennomføre", filePath: "src/app/portal/gjennomfore/page.tsx" },
  { route: "/portal/kalender", label: "Kalender", category: "PlayerHQ", filePath: "src/app/portal/kalender/page.tsx" },
  { route: "/portal/live/[sessionId]", label: "live · detalj", category: "PlayerHQ", filePath: "src/app/portal/(fullscreen)/live/[sessionId]/page.tsx" },
  { route: "/portal/live/[sessionId]/active", label: "Active", category: "PlayerHQ", filePath: "src/app/portal/(fullscreen)/live/[sessionId]/active/page.tsx" },
  { route: "/portal/live/[sessionId]/brief", label: "Brief", category: "PlayerHQ", filePath: "src/app/portal/(fullscreen)/live/[sessionId]/brief/page.tsx" },
  { route: "/portal/live/[sessionId]/logger", label: "Logger", category: "PlayerHQ", filePath: "src/app/portal/(fullscreen)/live/[sessionId]/logger/page.tsx" },
  { route: "/portal/live/[sessionId]/summary", label: "Summary", category: "PlayerHQ", filePath: "src/app/portal/(fullscreen)/live/[sessionId]/summary/page.tsx" },
  { route: "/portal/live/[sessionId]/tapper", label: "Tapper", category: "PlayerHQ", filePath: "src/app/portal/(fullscreen)/live/[sessionId]/tapper/page.tsx" },
  { route: "/portal/mal", label: "Mal", category: "PlayerHQ · Mål", filePath: "src/app/portal/mal/page.tsx" },
  { route: "/portal/mal/bygger", label: "Bygger", category: "PlayerHQ · Mål", filePath: "src/app/portal/mal/bygger/page.tsx" },
  { route: "/portal/mal/goal/[id]", label: "goal · detalj", category: "PlayerHQ · Mål", filePath: "src/app/portal/mal/goal/[id]/page.tsx" },
  { route: "/portal/mal/leaderboard", label: "Leaderboard", category: "PlayerHQ · Mål", filePath: "src/app/portal/mal/leaderboard/page.tsx" },
  { route: "/portal/mal/milepaeler", label: "Milepaeler", category: "PlayerHQ · Mål", filePath: "src/app/portal/mal/milepaeler/page.tsx" },
  { route: "/portal/mal/runder", label: "Runder", category: "PlayerHQ · Mål", filePath: "src/app/portal/mal/runder/page.tsx" },
  { route: "/portal/mal/runder/[id]", label: "runder · detalj", category: "PlayerHQ · Mål", filePath: "src/app/portal/mal/runder/[id]/page.tsx" },
  { route: "/portal/mal/runder/[id]/shot-by-shot", label: "Shot by shot", category: "PlayerHQ · Mål", filePath: "src/app/portal/mal/runder/[id]/shot-by-shot/page.tsx" },
  { route: "/portal/mal/runder/ny", label: "Ny", category: "PlayerHQ · Mål", filePath: "src/app/portal/mal/runder/ny/page.tsx" },
  { route: "/portal/mal/sg-hub", label: "Sg hub", category: "PlayerHQ · Mål", filePath: "src/app/portal/mal/sg-hub/page.tsx" },
  { route: "/portal/mal/sg-hub/[club]", label: "sg-hub · detalj", category: "PlayerHQ · Mål", filePath: "src/app/portal/mal/sg-hub/[club]/page.tsx" },
  { route: "/portal/mal/sg-hub/best-vs-now", label: "Best vs now", category: "PlayerHQ · Mål", filePath: "src/app/portal/mal/sg-hub/best-vs-now/page.tsx" },
  { route: "/portal/mal/sg-hub/coach/[spillerId]", label: "coach · detalj", category: "PlayerHQ · Mål", filePath: "src/app/portal/mal/sg-hub/coach/[spillerId]/page.tsx" },
  { route: "/portal/mal/sg-hub/coach/[spillerId]/[club]", label: "[spillerId] · detalj", category: "PlayerHQ · Mål", filePath: "src/app/portal/mal/sg-hub/coach/[spillerId]/[club]/page.tsx" },
  { route: "/portal/mal/sg-hub/coach/[spillerId]/equipment", label: "Equipment", category: "PlayerHQ · Mål", filePath: "src/app/portal/mal/sg-hub/coach/[spillerId]/equipment/page.tsx" },
  { route: "/portal/mal/sg-hub/conditions", label: "Conditions", category: "PlayerHQ · Mål", filePath: "src/app/portal/mal/sg-hub/conditions/page.tsx" },
  { route: "/portal/mal/sg-hub/equipment", label: "Equipment", category: "PlayerHQ · Mål", filePath: "src/app/portal/mal/sg-hub/equipment/page.tsx" },
  { route: "/portal/mal/sg-hub/strategy", label: "Strategy", category: "PlayerHQ · Mål", filePath: "src/app/portal/mal/sg-hub/strategy/page.tsx" },
  { route: "/portal/mal/sg-hub/yardage", label: "Yardage", category: "PlayerHQ · Mål", filePath: "src/app/portal/mal/sg-hub/yardage/page.tsx" },
  { route: "/portal/mal/statistikk", label: "Statistikk", category: "PlayerHQ · Mål", filePath: "src/app/portal/mal/statistikk/page.tsx" },
  { route: "/portal/mal/trackman", label: "Trackman", category: "PlayerHQ · Mål", filePath: "src/app/portal/mal/trackman/page.tsx" },
  { route: "/portal/mal/trackman/[id]", label: "trackman · detalj", category: "PlayerHQ · Mål", filePath: "src/app/portal/mal/trackman/[id]/page.tsx" },
  { route: "/portal/meg", label: "Meg", category: "PlayerHQ · Min profil", filePath: "src/app/portal/meg/page.tsx" },
  { route: "/portal/meg/abonnement", label: "Abonnement", category: "PlayerHQ · Min profil", filePath: "src/app/portal/meg/abonnement/page.tsx" },
  { route: "/portal/meg/abonnement/avbestill", label: "Avbestill", category: "PlayerHQ · Min profil", filePath: "src/app/portal/meg/abonnement/avbestill/page.tsx" },
  { route: "/portal/meg/abonnement/faktura/[id]", label: "faktura · detalj", category: "PlayerHQ · Min profil", filePath: "src/app/portal/meg/abonnement/faktura/[id]/page.tsx" },
  { route: "/portal/meg/abonnement/kort/ny", label: "Ny", category: "PlayerHQ · Min profil", filePath: "src/app/portal/meg/abonnement/kort/ny/page.tsx" },
  { route: "/portal/meg/abonnement/oppgrader", label: "Oppgrader", category: "PlayerHQ · Min profil", filePath: "src/app/portal/meg/abonnement/oppgrader/page.tsx" },
  { route: "/portal/meg/abonnement/oppgrader/flyt", label: "Flyt", category: "PlayerHQ · Min profil", filePath: "src/app/portal/meg/abonnement/oppgrader/flyt/page.tsx" },
  { route: "/portal/meg/bookinger", label: "Bookinger", category: "PlayerHQ · Min profil", filePath: "src/app/portal/meg/bookinger/page.tsx" },
  { route: "/portal/meg/bookinger/reschedule/[bookingId]", label: "reschedule · detalj", category: "PlayerHQ · Min profil", filePath: "src/app/portal/meg/bookinger/reschedule/[bookingId]/page.tsx" },
  { route: "/portal/meg/dokumenter", label: "Dokumenter", category: "PlayerHQ · Min profil", filePath: "src/app/portal/meg/dokumenter/page.tsx" },
  { route: "/portal/meg/feedback", label: "Feedback", category: "PlayerHQ · Min profil", filePath: "src/app/portal/meg/feedback/page.tsx" },
  { route: "/portal/meg/foreldre", label: "Foreldre", category: "PlayerHQ · Min profil", filePath: "src/app/portal/meg/foreldre/page.tsx" },
  { route: "/portal/meg/help", label: "Help", category: "PlayerHQ · Min profil", filePath: "src/app/portal/meg/help/page.tsx" },
  { route: "/portal/meg/help/artikkel/[slug]", label: "artikkel · detalj", category: "PlayerHQ · Min profil", filePath: "src/app/portal/meg/help/artikkel/[slug]/page.tsx" },
  { route: "/portal/meg/help/kategori/[slug]", label: "kategori · detalj", category: "PlayerHQ · Min profil", filePath: "src/app/portal/meg/help/kategori/[slug]/page.tsx" },
  { route: "/portal/meg/help/kontakt", label: "Kontakt", category: "PlayerHQ · Min profil", filePath: "src/app/portal/meg/help/kontakt/page.tsx" },
  { route: "/portal/meg/helse", label: "Helse", category: "PlayerHQ · Min profil", filePath: "src/app/portal/meg/helse/page.tsx" },
  { route: "/portal/meg/helse/symptom/ny", label: "Ny", category: "PlayerHQ · Min profil", filePath: "src/app/portal/meg/helse/symptom/ny/page.tsx" },
  { route: "/portal/meg/innstillinger", label: "Innstillinger", category: "PlayerHQ · Min profil", filePath: "src/app/portal/meg/innstillinger/page.tsx" },
  { route: "/portal/meg/innstillinger/anlegg", label: "Anlegg", category: "PlayerHQ · Min profil", filePath: "src/app/portal/meg/innstillinger/anlegg/page.tsx" },
  { route: "/portal/meg/innstillinger/eksport", label: "Eksport", category: "PlayerHQ · Min profil", filePath: "src/app/portal/meg/innstillinger/eksport/page.tsx" },
  { route: "/portal/meg/innstillinger/integrasjoner", label: "Integrasjoner", category: "PlayerHQ · Min profil", filePath: "src/app/portal/meg/innstillinger/integrasjoner/page.tsx" },
  { route: "/portal/meg/innstillinger/okter", label: "Okter", category: "PlayerHQ · Min profil", filePath: "src/app/portal/meg/innstillinger/okter/page.tsx" },
  { route: "/portal/meg/innstillinger/personvern", label: "Personvern", category: "PlayerHQ · Min profil", filePath: "src/app/portal/meg/innstillinger/personvern/page.tsx" },
  { route: "/portal/meg/innstillinger/sikkerhet", label: "Sikkerhet", category: "PlayerHQ · Min profil", filePath: "src/app/portal/meg/innstillinger/sikkerhet/page.tsx" },
  { route: "/portal/meg/innstillinger/sprak", label: "Sprak", category: "PlayerHQ · Min profil", filePath: "src/app/portal/meg/innstillinger/sprak/page.tsx" },
  { route: "/portal/meg/innstillinger/varsler", label: "Varsler", category: "PlayerHQ · Min profil", filePath: "src/app/portal/meg/innstillinger/varsler/page.tsx" },
  { route: "/portal/meg/profil/rediger", label: "Rediger", category: "PlayerHQ · Min profil", filePath: "src/app/portal/meg/profil/rediger/page.tsx" },
  { route: "/portal/meg/sikkerhet", label: "Sikkerhet", category: "PlayerHQ · Min profil", filePath: "src/app/portal/meg/sikkerhet/page.tsx" },
  { route: "/portal/meg/sikkerhet/2fa", label: "2fa", category: "PlayerHQ · Min profil", filePath: "src/app/portal/meg/sikkerhet/2fa/page.tsx" },
  { route: "/portal/meg/utstyrsbag", label: "Utstyrsbag", category: "PlayerHQ · Min profil", filePath: "src/app/portal/meg/utstyrsbag/page.tsx" },
  { route: "/portal/ny-okt", label: "Ny okt", category: "PlayerHQ", filePath: "src/app/portal/ny-okt/page.tsx" },
  { route: "/portal/onskeligokt", label: "Onskeligokt", category: "PlayerHQ", filePath: "src/app/portal/onskeligokt/page.tsx" },
  { route: "/portal/onskeligokt/bekreftet", label: "Bekreftet", category: "PlayerHQ", filePath: "src/app/portal/onskeligokt/bekreftet/page.tsx" },
  { route: "/portal/planlegge", label: "Planlegge", category: "PlayerHQ · Planlegge", filePath: "src/app/portal/planlegge/page.tsx" },
  { route: "/portal/planlegge/workbench", label: "Workbench", category: "PlayerHQ · Planlegge", filePath: "src/app/portal/planlegge/workbench/page.tsx" },
  { route: "/portal/reach", label: "Reach", category: "PlayerHQ", filePath: "src/app/portal/reach/page.tsx" },
  { route: "/portal/spiller/[spillerId]", label: "spiller · detalj", category: "PlayerHQ", filePath: "src/app/portal/spiller/[spillerId]/page.tsx" },
  { route: "/portal/statistikk", label: "Statistikk", category: "PlayerHQ", filePath: "src/app/portal/statistikk/page.tsx" },
  { route: "/portal/statistikk/[metric]", label: "statistikk · detalj", category: "PlayerHQ", filePath: "src/app/portal/statistikk/[metric]/page.tsx" },
  { route: "/portal/statistikk/runder/[runId]/del", label: "Del", category: "PlayerHQ", filePath: "src/app/portal/statistikk/runder/[runId]/del/page.tsx" },
  { route: "/portal/stats", label: "Stats", category: "PlayerHQ", filePath: "src/app/portal/stats/page.tsx" },
  { route: "/portal/talent", label: "Talent", category: "PlayerHQ · Talent", filePath: "src/app/portal/talent/page.tsx" },
  { route: "/portal/talent/min-plan", label: "Min plan", category: "PlayerHQ · Talent", filePath: "src/app/portal/talent/min-plan/page.tsx" },
  { route: "/portal/talent/mitt-niva", label: "Mitt niva", category: "PlayerHQ · Talent", filePath: "src/app/portal/talent/mitt-niva/page.tsx" },
  { route: "/portal/talent/roadmap", label: "Roadmap", category: "PlayerHQ · Talent", filePath: "src/app/portal/talent/roadmap/page.tsx" },
  { route: "/portal/talent/sammenligning", label: "Sammenligning", category: "PlayerHQ · Talent", filePath: "src/app/portal/talent/sammenligning/page.tsx" },
  { route: "/portal/test/[testId]/live", label: "Live", category: "PlayerHQ", filePath: "src/app/portal/(fullscreen)/test/[testId]/live/page.tsx" },
  { route: "/portal/test/[testId]/summary", label: "Summary", category: "PlayerHQ", filePath: "src/app/portal/(fullscreen)/test/[testId]/summary/page.tsx" },
  { route: "/portal/trackman/[sessionId]", label: "trackman · detalj", category: "PlayerHQ", filePath: "src/app/portal/trackman/[sessionId]/page.tsx" },
  { route: "/portal/tren", label: "Tren", category: "PlayerHQ · Tren", filePath: "src/app/portal/(fullscreen)/tren/page.tsx" },
  { route: "/portal/tren/[sessionId]", label: "tren · detalj", category: "PlayerHQ · Tren", filePath: "src/app/portal/tren/[sessionId]/page.tsx" },
  { route: "/portal/tren/[sessionId]/planlagt", label: "Planlagt", category: "PlayerHQ · Tren", filePath: "src/app/portal/tren/[sessionId]/planlagt/page.tsx" },
  { route: "/portal/tren/aarsplan", label: "Aarsplan", category: "PlayerHQ · Tren", filePath: "src/app/portal/tren/aarsplan/page.tsx" },
  { route: "/portal/tren/aarsplan/periode/[id]/rediger", label: "Rediger", category: "PlayerHQ · Tren", filePath: "src/app/portal/tren/aarsplan/periode/[id]/rediger/page.tsx" },
  { route: "/portal/tren/feiring/[planId]", label: "feiring · detalj", category: "PlayerHQ · Tren", filePath: "src/app/portal/tren/feiring/[planId]/page.tsx" },
  { route: "/portal/tren/fys-plan", label: "Fys plan", category: "PlayerHQ · Tren", filePath: "src/app/portal/tren/fys-plan/page.tsx" },
  { route: "/portal/tren/fys-plan/[planId]", label: "fys-plan · detalj", category: "PlayerHQ · Tren", filePath: "src/app/portal/tren/fys-plan/[planId]/page.tsx" },
  { route: "/portal/tren/kalender", label: "Kalender", category: "PlayerHQ · Tren", filePath: "src/app/portal/tren/kalender/page.tsx" },
  { route: "/portal/tren/ovelser", label: "Ovelser", category: "PlayerHQ · Tren", filePath: "src/app/portal/tren/ovelser/page.tsx" },
  { route: "/portal/tren/ovelser/[id]", label: "ovelser · detalj", category: "PlayerHQ · Tren", filePath: "src/app/portal/tren/ovelser/[id]/page.tsx" },
  { route: "/portal/tren/teknisk-plan", label: "Teknisk plan", category: "PlayerHQ · Tren", filePath: "src/app/portal/tren/teknisk-plan/page.tsx" },
  { route: "/portal/tren/teknisk-plan/[planId]", label: "teknisk-plan · detalj", category: "PlayerHQ · Tren", filePath: "src/app/portal/tren/teknisk-plan/[planId]/page.tsx" },
  { route: "/portal/tren/tester", label: "Tester", category: "PlayerHQ · Tren", filePath: "src/app/portal/tren/tester/page.tsx" },
  { route: "/portal/tren/tester/[testId]", label: "tester · detalj", category: "PlayerHQ · Tren", filePath: "src/app/portal/tren/tester/[testId]/page.tsx" },
  { route: "/portal/tren/tester/katalog", label: "Katalog", category: "PlayerHQ · Tren", filePath: "src/app/portal/tren/tester/katalog/page.tsx" },
  { route: "/portal/tren/tester/ny", label: "Ny", category: "PlayerHQ · Tren", filePath: "src/app/portal/tren/tester/ny/page.tsx" },
  { route: "/portal/tren/tester/ny/egen", label: "Egen", category: "PlayerHQ · Tren", filePath: "src/app/portal/tren/tester/ny/egen/page.tsx" },
  { route: "/portal/tren/turneringer", label: "Turneringer", category: "PlayerHQ · Tren", filePath: "src/app/portal/tren/turneringer/page.tsx" },
  { route: "/portal/tren/turneringer/[id]", label: "turneringer · detalj", category: "PlayerHQ · Tren", filePath: "src/app/portal/tren/turneringer/[id]/page.tsx" },
  { route: "/portal/tren/turneringer/ny", label: "Ny", category: "PlayerHQ · Tren", filePath: "src/app/portal/tren/turneringer/ny/page.tsx" },
  { route: "/portal/utfordringer", label: "Utfordringer", category: "PlayerHQ", filePath: "src/app/portal/utfordringer/page.tsx" },
  { route: "/portal/utfordringer/[id]", label: "utfordringer · detalj", category: "PlayerHQ", filePath: "src/app/portal/utfordringer/[id]/page.tsx" },
  { route: "/portal/utfordringer/ny", label: "Ny", category: "PlayerHQ", filePath: "src/app/portal/utfordringer/ny/page.tsx" },
  { route: "/portal/varsler", label: "Varsler", category: "PlayerHQ", filePath: "src/app/portal/varsler/page.tsx" },
  { route: "/portal/workbench-v2", label: "Workbench v2", category: "PlayerHQ", filePath: "src/app/portal/workbench-v2/page.tsx" },
];
