/**
 * AK Golf — TS-speil av --ak-*. GENERERT fra tokens.json — ikke rediger.
 * Peker BARE på var(--ak-*), så lys/mørk følger data-ak-flate og ingen hex
 * dupliseres. Gjelder merket (marked, materiell, presentasjon), aldri
 * produktskjermer — de bruker TL fra src/lib/v2/train-lock.ts.
 */

export const AK_GOLF = {
  farge: {
    grunn: "var(--ak-grunn)",
    grunnSenk: "var(--ak-grunn-senk)",
    ark: "var(--ak-ark)",
    tekst: "var(--ak-tekst)",
    dempet: "var(--ak-dempet)",
    svak: "var(--ak-svak)",
    linje: "var(--ak-linje)",
    linjeHard: "var(--ak-linje-hard)",
    signal: "var(--ak-signal)",
    signalFyll: "var(--ak-signal-fyll)",
    signalTekst: "var(--ak-signal-tekst)",
    signalMyk: "var(--ak-signal-myk)",
    fag: "var(--ak-fag)",
    vJunior: "var(--ak-v-junior)",
    vAcademy: "var(--ak-v-academy)",
    vHq: "var(--ak-v-hq)",
    vOrg: "var(--ak-v-org)",
    vProdukt: "var(--ak-v-produkt)",
    ok: "var(--ak-ok)",
    varsel: "var(--ak-varsel)",
    feil: "var(--ak-feil)",
  },
  type: {
    display: "var(--ak-display)",
    sans: "var(--ak-sans)",
    mono: "var(--ak-mono)",
    t11: "var(--ak-t-11)",
    t13: "var(--ak-t-13)",
    t15: "var(--ak-t-15)",
    t17: "var(--ak-t-17)",
    t21: "var(--ak-t-21)",
    t26: "var(--ak-t-26)",
    t34: "var(--ak-t-34)",
    t48: "var(--ak-t-48)",
    t72: "var(--ak-t-72)",
    t112: "var(--ak-t-112)",
    tHero: "var(--ak-t-hero)",
    tSeksjon: "var(--ak-t-seksjon)",
    v400: "var(--ak-v-400)",
    v500: "var(--ak-v-500)",
    v600: "var(--ak-v-600)",
    v700: "var(--ak-v-700)",
    lhDisplay: "var(--ak-lh-display)",
    lhTett: "var(--ak-lh-tett)",
    lhNormal: "var(--ak-lh-normal)",
    spDisplay: "var(--ak-sp-display)",
    spTitt: "var(--ak-sp-titt)",
    spNull: "var(--ak-sp-null)",
    spVid: "var(--ak-sp-vid)",
    spVidt: "var(--ak-sp-vidt)",
  },
  rom: {
    r1: "var(--ak-r-1)",
    r2: "var(--ak-r-2)",
    r3: "var(--ak-r-3)",
    r4: "var(--ak-r-4)",
    r5: "var(--ak-r-5)",
    r6: "var(--ak-r-6)",
    r7: "var(--ak-r-7)",
    r8: "var(--ak-r-8)",
    r9: "var(--ak-r-9)",
    r10: "var(--ak-r-10)",
    hjorne0: "var(--ak-hjorne-0)",
    hjorneSm: "var(--ak-hjorne-sm)",
    hjorneMd: "var(--ak-hjorne-md)",
    hjorneLg: "var(--ak-hjorne-lg)",
    hjornePill: "var(--ak-hjorne-pill)",
    loft1: "var(--ak-loft-1)",
    loft2: "var(--ak-loft-2)",
    loft3: "var(--ak-loft-3)",
    lesebredde: "var(--ak-lesebredde)",
    sidebredde: "var(--ak-sidebredde)",
    treff: "var(--ak-treff)",
    bpMobil: "var(--ak-bp-mobil)",
    bpTablet: "var(--ak-bp-tablet)",
    bpMac: "var(--ak-bp-mac)",
  },
  bevegelse: {
    fartRask: "var(--ak-fart-rask)",
    fartMid: "var(--ak-fart-mid)",
    fartRolig: "var(--ak-fart-rolig)",
    kurve: "var(--ak-kurve)",
    kurveInn: "var(--ak-kurve-inn)",
  },
  instrument: {
    rute: "var(--ak-rute)",
    ruteTett: "var(--ak-rute-tett)",
    ruteLinje: "var(--ak-rute-linje)",
    ruteLys: "var(--ak-rute-lys)",
    ruteMork: "var(--ak-rute-mork)",
    maalTykk: "var(--ak-maal-tykk)",
    maalMerke: "var(--ak-maal-merke)",
    maalHel: "var(--ak-maal-hel)",
    maalSteg: "var(--ak-maal-steg)",
    kryss: "var(--ak-kryss)",
    flateMin: "var(--ak-flate-min)",
  },
} as const;

export type AkGolfTokens = typeof AK_GOLF;
