import { expect, test } from "@playwright/test";
import { readFileSync } from "node:fs";
import { parse } from "dotenv";
const users = parse(readFileSync(".codex/environments/workbench/.env.users"));
test("egen spiller: øktmål og treukerssyklus lagres, kopieres og gjenleses", async ({ page }, info) => {
  page.setDefaultTimeout(10_000); page.setDefaultNavigationTimeout(60_000);
  const errors: string[] = []; page.on("pageerror", e => errors.push(e.message));
  await page.context().route("**/*", async route => { const u = new URL(route.request().url()); if (u.hostname === "127.0.0.1" && ["3072", "55721"].includes(u.port)) await route.continue(); else await route.abort(); });
  await page.goto("/auth/login"); await page.getByRole("button", {name:"Logg inn med passord",exact:true}).click();
  await page.locator("input[type=email]").fill(users.LOCAL_P01_EMAIL); await page.locator("input[type=password]").fill(users.LOCAL_P01_PASSWORD);
  await page.locator("form button[type=submit]").click(); await page.waitForURL(u => u.pathname === "/portal", {timeout:30000});
  const anchor = info.project.name === "desktop" ? "2040-01-02" : "2040-04-02";
  const target = info.project.name === "desktop" ? "2040-02-06" : "2040-05-07";
  const path = "/portal/planlegge/workbench";
  await page.goto(`${path}?flate=uke&uke=${anchor}&aar=2040`);
  const cookies = page.getByRole("button", {name:"Kun nødvendige",exact:true}); await expect(cookies).toBeVisible(); await cookies.click();
  const title = `Syntetisk måløkt ${info.project.name} ${Date.now()}`;
  await page.getByRole("button", {name:"Ny økt",exact:true}).click();
  let dialog = page.locator(".pa-sheet[role=dialog]").last();
  await dialog.getByRole("textbox", {name:"Tittel",exact:true}).fill(title);
  await dialog.getByRole("textbox", {name:"Formål",exact:true}).fill("Syntetisk presisjon");
  await dialog.getByRole("textbox", {name:"Sted",exact:true}).fill("Syntetisk treningssted");
  await dialog.getByRole("textbox", {name:"Øktens målsetning",exact:true}).fill("Syntetisk øktmål");
  await dialog.getByRole("button", {name:"Legg inn",exact:true}).click(); await expect(dialog).not.toBeVisible();
  await page.reload();
  const card = page.locator(info.project.name === "mobil" ? ".ws-agenda .ws-session" : ".ws-calendar .ws-session").filter({hasText:title});
  await card.click();
  await page.waitForURL(u => Boolean(u.searchParams.get("okt")), {waitUntil:"domcontentloaded"});
  if (info.project.name === "mobil") await page.getByRole("button", {name:"Tid, serie og detaljer",exact:true}).click();
  else await page.locator(".ws-inspector").getByRole("button", {name:"Tid, serie og detaljer",exact:true}).click();
  dialog = page.locator(".pa-sheet[role=dialog]").last();
  await expect(dialog.getByRole("textbox", {name:"Øktens målsetning",exact:true})).toHaveValue("Syntetisk øktmål");
  await expect(dialog.getByRole("textbox", {name:"Formål",exact:true})).toHaveValue("Syntetisk presisjon");
  await dialog.getByRole("textbox", {name:"Øktens målsetning",exact:true}).fill("Syntetisk revidert mål");
  await dialog.getByRole("button", {name:"Lagre øktinnhold",exact:true}).click();
  await expect(dialog.getByRole("button", {name:"Lagre øktinnhold",exact:true})).toBeDisabled();
  await page.goto(`${path}?flate=uke&uke=${anchor}&aar=2040`);
  await page.getByRole("button", {name:"Treukerssyklus",exact:true}).click();
  const cycle = page.locator(".pa-sheet[role=dialog]").filter({hasText:"Tre sammenhengende kalenderuker"});
  await expect(cycle.getByRole("button", {name:"Rediger uke 2",exact:true})).toBeEnabled();
  await cycle.getByRole("button", {name:"Rediger uke 2",exact:true}).click();
  const week = page.locator(".pa-sheet[role=dialog]").last();
  await week.getByRole("textbox", {name:"Oppholdssted",exact:true}).fill("Syntetisk uke to");
  await week.getByRole("spinbutton", {name:"FYS timer",exact:true}).fill("0");
  await week.getByRole("spinbutton", {name:"FYS økter",exact:true}).fill("2");
  await week.getByRole("button", {name:"Lagre ukeplan",exact:true}).click();
  await cycle.getByRole("button", {name:"Lagre alle tre uker",exact:true}).click();
  await expect(cycle.getByRole("button", {name:/Oppløs sykluskoblingen/})).toBeVisible();
  await cycle.getByLabel("Målmandag").fill(target);
  await cycle.getByRole("button", {name:"Forhåndsvis kopiering",exact:true}).click();
  await expect(cycle.getByRole("heading", {name:"Konsekvens for målukene",exact:true})).toBeVisible();
  await cycle.getByRole("checkbox").check();
  await cycle.getByRole("button", {name:"Kopier tre uker som utkast",exact:true}).click();
  await expect(cycle.getByRole("checkbox")).not.toBeChecked();
  await page.goto(`${path}?flate=uke&uke=${target}&aar=2040`);
  await expect(page.locator(".wb-samlet")).toContainText(title);
  await page.getByRole("button", {name:"Treukerssyklus",exact:true}).click();
  await expect(cycle).toContainText("Syntetisk uke to");
  await cycle.getByRole("button", {name:"Rediger uke 2",exact:true}).click();
  await expect(week.getByRole("spinbutton", {name:"FYS timer",exact:true})).toHaveValue("0");
  await expect(week.getByRole("spinbutton", {name:"FYS økter",exact:true})).toHaveValue("2");
  await week.getByRole("button", {name:"Lagre ukeplan",exact:true}).click();
  await page.screenshot({path:`/tmp/ak-workbench-okt-syklus-${info.project.name}.png`});
  expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1)).toBe(false);
  expect(errors).toEqual([]);
});
