/* AgencyOS Innboks — runde 26 (Anders 28.09.2026). Én liste for alt. Oppdiktede data. Lørdag 26.09.2026 08:14. age = timer siden. */
window.INBOX = {
  accounts: ["post@akgolf.no", "akgolfgroup@gmail.com"],
  filters: ["Alle", "Spillere", "E-post", "Godkjenn", "Oppfølging", "Varsler"],
  oppf: ["Risiko", "Følg med", "Sjekk", "Løst", "Leads"],
  items: [
    { id: "i1", f: "Spillere", kind: "Spørsmål", from: "Thea Nilsen", grp: "Junior elite", at: "Fre 25.09 · 12:10", age: 20, title: "Skal jeg spille klubbmesterskapet eller trene til regionfinalen?", body: "Regionfinalen er søndag. Klubbmesterskapet er lørdag. Jeg rekker begge, men blir sliten.", draft: { by: "Jarvis", text: "Hei Thea. Spill regionfinalen, og hopp over klubbmesterskapet denne gangen. Lørdag tar vi 45 min nærspill og putting, så er du klar søndag. Anders" } },
    { id: "i2", f: "Spillere", kind: "Video", from: "Tobias Lindvik", grp: "WANG Toppidrett", at: "07:52", age: 0.4, title: "Ny svingvideo fra range", body: "Er hendene foran nå? 7-jern, 50 % fart.", video: "0:24" },
    { id: "i3", f: "Spillere", kind: "Planendring", from: "Tobias Lindvik", grp: "WANG Toppidrett", at: "Fre 25.09 · 21:10", age: 11, title: "Be coach endre planen · Uke 40", body: "Jeg har eksamen tirsdag 29.09 og vil flytte innspillsøkta til onsdag.", actions: ["Åpne i Workbench"] },
    { id: "i4", f: "E-post", kind: "E-post", from: "Hanne Lindvik", acct: "post@akgolf.no", at: "07:31", age: 0.7, title: "Høstsamlingen i Sør-Spania", body: "Hei. Hva koster samlingen for Ada, og når er påmeldingsfristen?", draft: { by: "Jarvis", text: "Hei Hanne. Samlingen 06.10–10.10 koster 8 900 kr inkludert fly og opphold. Frist for påmelding er 30.09. Jeg sender lenke til påmelding i eget svar. Hilsen Anders" } },
    { id: "i5", f: "E-post", kind: "E-post", from: "Fredrikstad GK · administrasjon", acct: "akgolfgroup@gmail.com", at: "Fre 25.09 · 14:02", age: 18, title: "Baneleie vinter 2026–27", body: "Vi trenger bekreftelse på antall timer i simulatorhallen innen 01.10.", draft: { by: "AI", text: "Hei. Vi ønsker 12 timer per uke i simulatorhallen fra uke 44 til uke 12, samme tider som i fjor. Hilsen Anders Kristiansen, AK Golf" } },
    { id: "i6", f: "Godkjenn", kind: "Forslag fra motoren", from: "Planmotor", at: "06:00", age: 2.2, title: "Gjør uke 40 lettere for Tobias Lindvik", body: "Uke 37 og 38 gjennomførte han 134 % og 131 % av planen. Uke 40 går fra 14,5 til 11,5 t. Turneringen er uendret.", meta: "ØKTLOGG · UKE 37–38 · 26.09.2026", actions: ["Godkjenn", "Avvis"] },
    { id: "i7", f: "Godkjenn", kind: "Sammendrag fra opptak", from: "Privattime · Tobias Lindvik", at: "Fre 25.09 · 17:05", age: 15, title: "Sammendrag klart · privattime 25.09", body: "Utkast fra opptak og notater. Godkjent går rett til spilleren.", draft: { by: "AI", text: "Vi jobbet med P6.0: køllen inn fra innsiden. I 25 % fart satt det i 6 av 10. Hjemmelekse: speilarbeid P6.0, 3 × 10 hver dag." }, note: "Navn tas ut før teksten sendes til AI." },
    { id: "i8", f: "Godkjenn", kind: "Ny gruppeøkt", from: "Planmotor", at: "Man 28.09 · 06:00", age: 2, title: "Forslag: tirsdag 17–18, nærspill, 8 plasser, 2 400 kr ESTIMAT", body: "Nærspill tirsdag 16:00 og putting torsdag 17:00 er fulle. 8 spillere venter på nærspill, 7 av dem er ledige tirsdag 17–18. Chippinggreen er ledig. Coach: Kristin Aas.", meta: "PRIS × PLASSER · 300 KR × 8 = 2 400 KR · ESTIMAT · SYNLIG FOR HEAD OG ASSISTANT COACH · GODKJENT LEGGES UT TIL BOOKING", actions: ["Godkjenn", "Avvis", "Se i kalenderen"] },
    { id: "i9", f: "Godkjenn", kind: "Godkjenning", from: "Registrering", at: "Tor 24.09 · 12:20", age: 44, title: "Ny spiller: Mari Solvang, født 2012", body: "Forelder har samtykket. Mangler gruppe.", actions: ["Godkjenn", "Avvis"] },
    { id: "i10", f: "Oppfølging", o: "Følg med", kind: "Følger ikke planen", from: "Oskar Nilsen", grp: "Junior elite", at: "06:00", age: 2.2, title: "52 % og 58 % de to siste ukene", body: "Tredje uke på rad under 70 %. Siste melding fra Oskar 12.09.", meta: "ØKTLOGG · UKE 36–38", actions: ["Spiller 360"] },
    { id: "i11", f: "Oppfølging", o: "Følg med", kind: "Følger ikke planen", from: "Sara Holm", grp: "WANG Toppidrett", at: "06:00", age: 2.2, title: "64 % og 69 % de to siste ukene", body: "Skolestress i uke 38 ifølge fireukerssjekken.", meta: "ØKTLOGG · UKE 37–38", actions: ["Spiller 360"] },
    { id: "i12", f: "Oppfølging", o: "Sjekk", kind: "Sjekk inn", from: "Jonas Lie", grp: "Junior elite", at: "Ons 23.09 · 09:00", age: 71, title: "Ingen økter logget på 9 dager", body: "Sist logget 17.09. Ingen skade registrert.", draft: { by: "Jarvis", text: "Hei Jonas. Så at det har vært stille en stund. Alt i orden? Si fra om planen må justeres. Anders" } },
    { id: "i13", f: "Oppfølging", o: "Leads", kind: "Lead", from: "Kari Moen", acct: "post@akgolf.no", at: "Fre 25.09 · 20:12", age: 12, title: "Juniortrening for sønn (11)", body: "Vi har flyttet til Fredrikstad. Har dere plass i en gruppe for 11-åringer?", draft: { by: "Jarvis", text: "Hei Kari. Ja, vi har plass i Basis på tirsdager 17:00–18:30. Første time er gratis. Vil dere prøve tirsdag 06.10? Hilsen Anders, AK Golf" } },
    { id: "i14", f: "Oppfølging", o: "Løst", kind: "Følger ikke planen", from: "Ida Berg", grp: "Junior elite", at: "Man 21.09 · 10:00", age: 118, title: "Tilbake over 70 % · 88 % uke 38", body: "Løst etter samtale 15.09." },
    { id: "i15", f: "Varsler", kind: "Turnering", from: "GolfBox", at: "Fre 25.09 · 09:14", age: 23, title: "Thea Nilsen er påmeldt Regionfinale junior", body: "Borregaard GK · søndag 27.09 · tee 09:20." },
    { id: "i16", f: "Varsler", kind: "Planendring", from: "Magnus Aasheim", at: "Fre 25.09 · 08:02", age: 24, title: "Flyttet økt torsdag til fredag", body: "Innspill 50–100 m · du la inn økta. Du kan endre tilbake i Workbench." },
  ],
};
