/* AgencyOS admin · batch 2 — oppdiktede, realistiske data. Lørdag 26.09.2026, uke 39. */
window.AOA_DATA = {
  dispatch: [
    { id: "d1", src: "Belastningsagent", icon: "activity", axis: "fys", t: "13:48", title: "Foreslå hviledag for Magnus Aasheim", facts: [["ACWR", "1,62", true], ["Akutt 7 d", "612 AU"], ["Kronisk 28 d", "378 AU"]], body: "Tre økter over plan siste 7 dager. Torsdagens SLAG-økt 01.10 byttes med hvile og flyttes til mandag 05.10." },
    { id: "d2", src: "Caddie", icon: "sparkles", axis: "slag", t: "12:10", title: "Ny wedge-blokk for Ingrid Berg", facts: [["Innspill ca. 50 m ±4 m", "48 %"], ["Mål", "65 %"], ["SG APP", "−0,9"]], body: "Siste 3 runder taper mest innenfor 100 m. Caddie har laget 2 økter à 45 min til uke 40." },
    { id: "d3", src: "Fraværsagent", icon: "calendar-x", axis: "spill", t: "11:32", title: "Flytt privattime for Jonas Lie", facts: [["Fravær", "Fr 02.10"], ["Ny tid", "Ti 29.09 · 17:00"]], body: "WANG Toppidrett har meldt heldagsprøve fredag 02.10. Ledig tid tirsdag 17:00 passer i begge kalendere." },
    { id: "d4", src: "Oppfølgingsagent", icon: "message-square-text", axis: "tek", t: "09:05", title: "Send påminnelse til Oskar Vik", facts: [["Siste økt", "15.09"], ["Dager uten økt", "11"]], body: "Ingen registrerte økter på 11 dager. Utkast til melding til spiller og forelder er klart." },
  ],
  roster: {
    idag: [
      ["Magnus Aasheim", "SLAG · Innspill ca. 150 m · Treningsområde", "15:30", "Pågår"],
      ["Sara Holm", "TEK · Utslag · startretning", "16:00", "Planlagt"],
      ["Henrik Dahl", "Fellestrening WANG · Borregaard GK", "16:00", "Planlagt"],
      ["Thea Nilsen", "SPILL · 9 hull Borregaard", "17:00", "Planlagt"],
      ["Kasper Moen", "FYS · Styrke · Innendørs", "17:30", "Planlagt"],
      ["Nora Bakke", "Privattime · Putting 3–5 fot", "18:00", "Planlagt"],
      ["Ella Strand", "SLAG · Pitch · landingspunkt", "18:30", "Planlagt"],
    ],
    skadet: [
      ["Jonas Lie", "Håndledd venstre · −20 % volum", "til 06.10", "warn"],
      ["Sander Haugen", "Korsrygg · kun FYS bevegelighet", "vurderes 01.10", "warn"],
    ],
    ubesvart: [
      ["Ingrid Berg", "«Kan vi ta putting i stedet på lørdag?»", "2 t"],
      ["Kari Solberg", "Forelder til Emil · «Gjelder samlingen i Oslo»", "3 t"],
      ["Thea Nilsen", "«Hvilken tee bruker vi på 7. hull?»", "40 min"],
      ["Oskar Vik", "«Beklager, har hatt mye på skolen»", "1 d"],
    ],
  },
  approvals: [
    { id: "g1", type: "okt", who: "Sara Holm", grp: "WANG Toppidrett", title: "Ukeplan uke 40", src: "Caddie", due: "18:00", axis: "tek", summary: "6 økter · 8 t 10 min · ACWR etter plan 1,08", lines: [["Ma 28.09", "TEK · Utslag · startretning", "60 min"], ["Ti 29.09", "SLAG · Innspill ca. 100 m", "75 min"], ["On 30.09", "FYS · Styrke", "45 min"], ["To 01.10", "SPILL · 9 hull Borregaard", "120 min"], ["Fr 02.10", "SLAG · Putting 3–5 fot", "60 min"], ["Lø 03.10", "TEK · Pitch · treffpunkt", "60 min"]] },
    { id: "g2", type: "okt", who: "Ingrid Berg", grp: "WANG Toppidrett", title: "Ukeplan uke 40", src: "Caddie", due: "18:00", axis: "slag", summary: "5 økter · 7 t 20 min · ACWR etter plan 1,12", lines: [["Ma 28.09", "SLAG · Innspill ca. 50 m", "45 min"], ["Ti 29.09", "FYS · Bevegelighet", "40 min"], ["On 30.09", "SLAG · Innspill ca. 50 m", "45 min"], ["To 01.10", "SPILL · 18 hull Onsøy", "240 min"], ["Lø 03.10", "SLAG · Putting 5–10 fot", "70 min"]] },
    { id: "g3", type: "okt", who: "Emil Solberg", grp: "Talent U16", title: "Ukeplan uke 40", src: "Caddie", due: "18:00", axis: "spill", summary: "5 økter · 6 t 45 min · ACWR etter plan 0,96", lines: [["Ma 28.09", "TEK · Chip · treffpunkt", "60 min"], ["On 30.09", "FYS · Styrke", "45 min"], ["To 01.10", "SLAG · Innspill ca. 150 m", "60 min"], ["Lø 03.10", "SPILL · 9 hull Borregaard", "120 min"], ["Sø 04.10", "SLAG · Putting 0–3 fot", "120 min"]] },
    { id: "g4", type: "okt", who: "Magnus Aasheim", grp: "WANG Toppidrett", title: "PlanAction · hviledag torsdag 01.10", src: "Belastningsagent", axis: "fys", summary: "ACWR 1,62 → 1,31 etter endring", lines: [["To 01.10", "SLAG · Innspill ca. 150 m → hvile", "−90 min"], ["Ma 05.10", "SLAG · Innspill ca. 150 m", "90 min"]] },
    { id: "g5", type: "endring", who: "Thea Nilsen", grp: "Talent U16", title: "Bytte FYS-økt med 9 hull lørdag 03.10", src: "Spiller", axis: "spill", summary: "«Vil teste gameplanen før klubbmesterskapet.»", lines: [["Lø 03.10", "FYS · Kondisjon", "45 min"], ["Erstattes av", "SPILL · 9 hull Borregaard", "120 min"]] },
    { id: "g6", type: "fravaer", who: "Jonas Lie", grp: "WANG Toppidrett", title: "Fravær fredag 02.10", src: "WANG Toppidrett", summary: "Heldagsprøve i norsk · meldt av kontaktlærer Line Aas", lines: [["Fr 02.10 · 07:00", "WANG morgentrening", "Utgår"], ["Fr 02.10 · 16:00", "Privattime", "Flyttes"]] },
    { id: "g7", type: "fravaer", who: "Nora Bakke", grp: "WANG Toppidrett", title: "Fravær mandag 28.09", src: "Spiller", summary: "Tannlege · meldt 25.09 kl. 21:14", lines: [["Ma 28.09 · 07:00", "WANG morgentrening", "Utgår"]] },
    { id: "g8", type: "samtykke", who: "Emil Solberg", age: 15, grp: "Talent U16", title: "Samtykke · samling Oslo GK 10.–11.10", src: "Forelder · Kari Solberg", summary: "Signert med BankID 26.09 kl. 11:42", lines: [["Samling", "Oslo GK · overnatting og transport", "2 døgn"], ["Deling", "TrackMan-data med NGF region", "Ja"]] },
    { id: "g9", type: "samtykke", who: "Ella Strand", age: 14, grp: "Talent U16", title: "Samtykke · videoanalyse", src: "Forelder · Per Strand", summary: "Signert med BankID 25.09 kl. 19:03", lines: [["Omfang", "Svingvideo på treningsområdet", "12 mnd"], ["Innsyn", "Coach, spiller og forelder", "—"]] },
  ],
  analysis: {
    "Ingrid Berg": { rounds: [["Borregaard GK", "20.09", "74 slag (+2)"], ["Onsøy GK", "14.09", "76 slag (+4)"], ["Hauger GK", "07.09", "73 slag (+1)"]], sg: [["OTT", "+0,2"], ["APP", "−0,9"], ["ARG", "+0,3"], ["PUTT", "−0,4"]], finding: "Innspill innenfor 100 m koster mest: 9 av 14 bom på green kom fra 50–100 m.", session: { axis: "slag", title: "Innspill ca. 50 m · lengdekontroll", code: "SLAG_INNSPILL50_AUTO_TRENINGSOMRÅDE_OBSERVERT", min: 45, items: [["Oppvarming · wedge", "20 slag"], ["40 / 50 / 60 m · restmål ±4 m", "3 × 10 slag"], ["Test · tilfeldig lengde", "10 slag"]] } },
    "Magnus Aasheim": { rounds: [["Borregaard GK", "21.09", "71 slag (−1)"], ["Larvik GK", "13.09", "72 slag (±0)"], ["Borregaard GK", "06.09", "70 slag (−2)"]], sg: [["OTT", "+0,4"], ["APP", "+0,6"], ["ARG", "+0,1"], ["PUTT", "−0,7"]], finding: "Putting 5–10 fot står for hele tapet: 38 % holet mot 52 % i snitt for kategori B.", session: { axis: "slag", title: "Putting 5–10 fot · ballstart", code: "SLAG_PUTTING5-10_TRENINGSOMRÅDE_KONKURRANSE", min: 50, items: [["Port-øvelse · 5 fot", "30 putter"], ["Stige 5–7–9 fot · restmål ±1°", "4 × 9 putter"], ["Test · 10 på rad fra 6 fot", "10 putter"]] } },
    "Sara Holm": { rounds: [["Onsøy GK", "19.09", "78 slag (+6)"], ["Borregaard GK", "12.09", "77 slag (+5)"], ["Hauger GK", "05.09", "79 slag (+7)"]], sg: [["OTT", "−1,1"], ["APP", "+0,1"], ["ARG", "+0,2"], ["PUTT", "−0,2"]], finding: "Utslag havner til høyre: 11 av 28 fairways bom høyre, Club Path +3,8° i snitt.", session: { axis: "tek", title: "Utslag · startretning · P6–P7", code: "TEK_UTSLAG_LH_TRENINGSOMRÅDE_ALENE", min: 60, items: [["Uten ball · P6 til P7", "20 rep."], ["Lav hastighet · restmål ±2° Club Path", "30 slag"], ["Full hastighet · port 30 m", "20 slag"]] } },
  },
  wedge: [["Uke 40", "Avstandskontroll", "Innspill ca. 50 m · Lengdekontroll", "2 × 60 min"], ["Uke 41", "Høyde og spinn", "Pitch · Høyde", "2 × 60 min"], ["Uke 42", "Variasjon under press", "Innspill ca. 100 m · Konkurranse", "2 × 75 min"], ["Uke 43", "Test og overføring til bane", "Test innspill ca. 100 m ±4 m", "60 min + 9 hull"]],
  acwr: [["Magnus Aasheim", 1.62], ["Thea Nilsen", 1.41], ["Ingrid Berg", 1.12], ["Sara Holm", 1.08], ["Henrik Dahl", 1.02], ["Emil Solberg", 0.96], ["Kasper Moen", 0.84], ["Oskar Vik", 0.52]],
  days: [["Ma", "28.09"], ["Ti", "29.09"], ["On", "30.09"], ["To", "01.10"], ["Fr", "02.10"], ["Lø", "03.10"], ["Sø", "04.10"]],
  events: [
    { id: "e1", d: 0, s: 7, l: 1.5, k: "felles", title: "WANG morgentrening", loc: "Borregaard GK · treningsområde", n: 12 },
    { id: "e2", d: 0, s: 15, l: 1, k: "privat", title: "Privattime", who: "Magnus Aasheim", loc: "Studio 1 · TrackMan" },
    { id: "e3", d: 0, s: 16, l: 1, k: "ledig" },
    { id: "e4", d: 0, s: 17, l: 1.5, k: "felles", title: "Talent U16", loc: "Borregaard GK · nærspillsområde", n: 9 },
    { id: "e5", d: 0, s: 19, l: 1, k: "ledig" },
    { id: "e6", d: 1, s: 7, l: 1.5, k: "felles", title: "WANG morgentrening", loc: "Borregaard GK · treningsområde", n: 12 },
    { id: "e7", d: 1, s: 12, l: 1, k: "opptatt", title: "Møte · NGF region Øst" },
    { id: "e8", d: 1, s: 16, l: 1, k: "privat", title: "Privattime", who: "Jonas Lie", loc: "Studio 1 · TrackMan" },
    { id: "e9", d: 1, s: 17, l: 1, k: "ledig" },
    { id: "e10", d: 1, s: 18, l: 1, k: "privat", title: "Privattime", who: "Nora Bakke", loc: "Puttinggreen" },
    { id: "e11", d: 2, s: 7, l: 1.5, k: "felles", title: "WANG morgentrening", loc: "Borregaard GK · treningsområde", n: 11 },
    { id: "e12", d: 2, s: 14, l: 1, k: "ledig" },
    { id: "e13", d: 2, s: 15, l: 1, k: "privat", title: "Privattime", who: "Sara Holm", loc: "Studio 1 · TrackMan" },
    { id: "e14", d: 2, s: 16, l: 1.5, k: "felles", title: "Talent U16", loc: "Borregaard GK · treningsområde", n: 9 },
    { id: "e15", d: 2, s: 18, l: 1, k: "privat", title: "Privattime", who: "Ella Strand", loc: "Nærspillsområde" },
    { id: "e16", d: 3, s: 7, l: 1.5, k: "felles", title: "WANG morgentrening", loc: "Borregaard GK · treningsområde", n: 12 },
    { id: "e17", d: 3, s: 15, l: 1, k: "ledig" },
    { id: "e18", d: 3, s: 16, l: 1, k: "privat", title: "Privattime", who: "Thea Nilsen", loc: "Bane · hull 1–3" },
    { id: "e19", d: 3, s: 17, l: 1, k: "privat", title: "Privattime", who: "Kasper Moen", loc: "Studio 1 · TrackMan" },
    { id: "e20", d: 3, s: 18, l: 1, k: "ledig" },
    { id: "e21", d: 4, s: 7, l: 1.5, k: "felles", title: "WANG morgentrening", loc: "Borregaard GK · treningsområde", n: 10 },
    { id: "e22", d: 4, s: 13, l: 4, k: "opptatt", title: "Trenerkurs NGF · trinn 3" },
    { id: "e23", d: 5, s: 9, l: 3, k: "felles", title: "Banespill · hele stallen", loc: "Borregaard GK · 18 hull", n: 18 },
    { id: "e24", d: 5, s: 13, l: 1, k: "privat", title: "Privattime", who: "Henrik Dahl", loc: "Studio 1 · TrackMan" },
    { id: "e25", d: 5, s: 14, l: 1, k: "ledig" },
  ],
  credits: {
    "Magnus Aasheim": { plan: "Performance Pro", left: 4, total: 4, exp: "31.12.2026", tier: "FULL", last: "21.09" },
    "Jonas Lie": { plan: "Performance Pro", left: 4, total: 4, exp: "31.03.2027", tier: "FULL", last: "22.09" },
    "Nora Bakke": { plan: "Performance", left: 1, total: 2, exp: "30.11.2026", tier: "FULL", last: "19.09" },
    "Sara Holm": { plan: "Performance Pro", left: 4, total: 4, exp: "31.03.2027", tier: "FULL", last: "23.09" },
    "Ella Strand": { plan: "Performance", left: 2, total: 2, exp: "31.12.2026", tier: "TALENT", last: "16.09" },
    "Thea Nilsen": { plan: "Performance Pro", left: 2, total: 4, exp: "31.10.2026", tier: "FULL", last: "24.09" },
    "Kasper Moen": { plan: "Performance", left: 2, total: 2, exp: "28.02.2027", tier: "TALENT", last: "—" },
    "Henrik Dahl": { plan: "Performance Pro", left: 0, total: 4, exp: "31.12.2026", tier: "FULL", last: "20.09" },
  },
  catalog: [
    { axis: "slag", name: "Innspill ca. 100 m · lengdekontroll", code: "SLAG_INNSPILL100_AUTO_TRENINGSOMRÅDE_OBSERVERT", desc: "30 slag · restmål ±4 m", min: 25 },
    { axis: "tek", name: "Utslag · startretning P6–P7", code: "TEK_UTSLAG_LH_INNENDØRS_ALENE", desc: "40 slag · ±2° Club Path", min: 30 },
    { axis: "slag", name: "Pitch · landingspunkt", code: "SLAG_PITCH_TRENINGSOMRÅDE_KONKURRANSE", desc: "30 slag · ±1 m landingspunkt", min: 20 },
    { axis: "slag", name: "Putting 3–5 fot · ballstart", code: "SLAG_PUTTING3-5_TRENINGSOMRÅDE_OBSERVERT", desc: "50 putter · ±1° ballstart", min: 20 },
    { axis: "tek", name: "Bunker · sandinngang", code: "TEK_BUNKER_TRENINGSOMRÅDE_ALENE", desc: "25 slag · 5 cm bak ballen", min: 20 },
    { axis: "fys", name: "Hofterotasjon med strikk", code: "FYS_STYRKE_INNENDØRS_ALENE", desc: "3 × 8 @ 12 kg · RIR 2", min: 15 },
    { axis: "fys", name: "Thorakal mobilitet", code: "FYS_BEVEGELIGHET_INNENDØRS_ALENE", desc: "2 × 10 · 10 min", min: 10 },
    { axis: "spill", name: "9 hull · strategioppgave", code: "SPILL_BANESPILL_BANE_OBSERVERT", desc: "9 hull · kun jern fra tee på par 4", min: 120 },
    { axis: "turn", name: "Treningsturnering · klubb", code: "TURN_TRENINGSTURNERING", desc: "Lav innsats · test av rutiner", min: 240 },
  ],
  players: ["Ingrid Berg", "Magnus Aasheim", "Sara Holm", "Emil Solberg", "Thea Nilsen", "Jonas Lie"],
  groups: [["WANG Toppidrett", 12], ["Talent U16", 9], ["Hele stallen", 18]],
};
