/* AgencyOS skjermkatalog AG-01… — bare demodata. Hovedspiller Tobias Lindvik, coach Anders Kristiansen. Lørdag 26.09.2026, uke 39. */
window.AG_DATA = {
  coach: { name: "Anders Kristiansen", role: "HOVEDCOACH" },
  today: "26.09.2026", dayLabel: "Lørdag 26.09", week: 39,
  now: { title: "Godkjenn ukeplan uke 40 for Tobias Lindvik", why: "Planen er sendt til deg. Tobias kan ikke starte mandag før den er godkjent.", due: "18:00", src: "JARVIS · 26.09.2026 13:48", to: "AG-02" },
  counts: [
    { id: "godkjenning", label: "Godkjenninger", n: 6, to: "AG-02", tab: "godkjenning", signal: true },
    { id: "agent", label: "Agentforslag", n: 4, to: "AG-02", tab: "agent" },
    { id: "test", label: "Tester", n: 3, to: "AG-02", tab: "test" },
    { id: "dublett", label: "Dubletter", n: 2, to: "AG-02", tab: "dublett" },
    { id: "moderering", label: "Moderering", n: 1, to: "AG-02", tab: "moderering" },
    { id: "risiko", label: "Oppfølging · risiko", n: 2, to: "AG-03" },
  ],
  plan: [
    { t: "09:00", end: "12:00", title: "Banespill · hele stallen", where: "Borregaard GK · 18 hull", axis: ["spill"], n: 18, k: "felles" },
    { t: "13:00", end: "14:00", title: "Privattime · Tobias Lindvik", where: "Studio 1 · TrackMan", axis: ["tek", "slag"], k: "privat", status: "Gjennomført" },
    { t: "14:00", end: "15:00", title: "Ledig", k: "ledig" },
    { t: "15:30", end: "16:30", title: "Privattime · Magnus Aasheim", where: "Treningsområde", axis: ["slag"], k: "privat", status: "Pågår" },
    { t: "17:00", end: "18:00", title: "Privattime · Lea Brekke", where: "Studio 1 · TrackMan", axis: ["tek"], k: "privat", status: "Bekreftet" },
  ],
  dispatch: [
    { id: "d1", agent: "Belastningsagent", icon: "activity", axis: "fys", t: "13:48", who: "Tobias Lindvik", title: "Bytt torsdagens SLAG-økt med hviledag", facts: [["ACWR", "1,58", "BELASTNING · 26.09.2026"], ["Akutt 7 d", "598 AU", "ØKTLOGG · 26.09.2026"], ["Kronisk 28 d", "378 AU", "ØKTLOGG · 26.09.2026"]], body: "Tre økter over plan siste 7 dager. Innspill ca. 150 m torsdag 01.10 flyttes til mandag 05.10.", out: "Endring i plan + melding til Tobias" },
    { id: "d2", agent: "Jarvis", icon: "sparkles", axis: "slag", t: "12:10", who: "Ingrid Berg", title: "Ny wedge-blokk uke 40–41", facts: [["Innspill ca. 50 m ±4 m", "48 %", "TEST · 12.09.2026"], ["Mål", "65 %", "PLAN · 01.09.2026"], ["SG APP", "−0,9", "10 RUNDER · 20.09.2026"]], body: "To økter à 45 min med lengdekontroll 40, 50 og 60 m. Restmål ±4 m.", out: "2 økter i Workbench" },
    { id: "d3", agent: "Fraværsagent", icon: "calendar-x", axis: "spill", t: "11:32", who: "Jonas Lie", title: "Flytt privattime fra fredag 02.10", facts: [["Fravær", "Fr 02.10", "WANG TOPPIDRETT · 25.09.2026"], ["Ny tid", "Ti 29.09 17:00", "KALENDER · 26.09.2026"]], body: "Heldagsprøve fredag. Ledig tid tirsdag 17:00 passer i begge kalendere.", out: "Ny tid + melding til Jonas og forelder" },
    { id: "d4", agent: "Oppfølgingsagent", icon: "message-square-text", axis: "tek", t: "09:05", who: "Oskar Vik", title: "Påminnelse etter 11 dager uten økt", facts: [["Siste økt", "15.09", "ØKTLOGG · 26.09.2026"], ["Dager uten økt", "11", "ØKTLOGG · 26.09.2026"]], body: "Kort melding til Oskar med forslag om én økt før onsdag.", out: "Melding til Oskar" },
  ],
  approvals: [
    { id: "a1", kind: "Plan", who: "Tobias Lindvik", grp: "WANG Toppidrett", title: "Ukeplan uke 40", status: "Venter på coach", from: "Tobias Lindvik", at: "26.09 13:48", due: "18:00", axis: ["tek", "slag", "fys", "spill"], lines: [["Ma 28.09", "TEK · Utslag · startretning", "60 min"], ["Ti 29.09", "SLAG · Innspill ca. 100 m", "75 min"], ["On 30.09", "FYS · Styrke", "45 min"], ["To 01.10", "SPILL · 9 hull Borregaard", "120 min"], ["Lø 03.10", "SLAG · Putting 3–5 fot", "60 min"]], sum: "5 økter · 6 t · ACWR etter plan 1,08" },
    { id: "a2", kind: "Plan", who: "Sara Holm", grp: "WANG Toppidrett", title: "Ukeplan uke 40", status: "Venter på coach", from: "Sara Holm", at: "26.09 11:02", due: "18:00", axis: ["tek", "slag"], lines: [["Ma 28.09", "TEK · Utslag · startretning", "60 min"], ["On 30.09", "SLAG · Pitch · landingspunkt", "60 min"]], sum: "2 økter · 2 t" },
    { id: "a3", kind: "Endring", who: "Thea Nilsen", grp: "Talent U16", title: "Bytt FYS-økt med 9 hull lørdag 03.10", status: "Venter på coach", from: "Thea Nilsen", at: "26.09 09:40", axis: ["spill"], lines: [["Lø 03.10", "FYS · Kondisjon", "45 min"], ["Erstattes av", "SPILL · 9 hull Borregaard", "120 min"]], sum: "+75 min" },
    { id: "a4", kind: "Fravær", who: "Jonas Lie", grp: "WANG Toppidrett", title: "Fravær fredag 02.10", status: "Venter på coach", from: "WANG Toppidrett", at: "25.09 15:12", lines: [["Fr 02.10 07:00", "WANG morgentrening", "Utgår"], ["Fr 02.10 16:00", "Privattime", "Flyttes"]], sum: "Heldagsprøve" },
    { id: "a5", kind: "Samtykke", who: "Tobias Lindvik", grp: "WANG Toppidrett", title: "Samtykke · videoanalyse", status: "Signert", from: "Forelder · Hanne Lindvik", at: "26.09 11:42", lines: [["Omfang", "Svingvideo på treningsområdet", "12 mnd"], ["Innsyn", "Coach, spiller og forelder", "—"]], sum: "Signert med BankID" },
    { id: "a6", kind: "Plan", who: "Emil Solberg", grp: "Talent U16", title: "Ukeplan uke 40", status: "Venter på coach", from: "Emil Solberg", at: "25.09 20:18", due: "18:00", axis: ["slag", "fys"], lines: [["Ti 29.09", "SLAG · Chip · treffpunkt", "60 min"], ["To 01.10", "FYS · Styrke", "45 min"]], sum: "2 økter · 1 t 45 min" },
  ],
  tests: [
    { id: "t1", who: "Tobias Lindvik", test: "Innspill ca. 50 m ±4 m", result: "7 av 10", prev: "5 av 10", done: 10, of: 10, witness: "Magnus Aasheim", at: "26.09.2026 13:40", src: "TEST · TEAM NORWAY" },
    { id: "t2", who: "Sara Holm", test: "Putting 3 fot · 10 på rad", result: "9 av 10", prev: "8 av 10", done: 10, of: 10, witness: "—", at: "25.09.2026 17:10", src: "TEST · AK GOLF" },
    { id: "t3", who: "Emil Solberg", test: "Utslag · fairway 30 m", result: null, prev: "6 av 14", done: 9, of: 14, witness: "—", at: "25.09.2026 16:02", src: "TEST · TEAM NORWAY" },
  ],
  dups: [
    { id: "u1", a: { src: "Påmelding · 24.09.2026", name: "Tobias Lindvik", born: "2009", email: "tobias.l@demo.no", phone: "900 11 223", club: "Borregaard GK", parent: "Hanne Lindvik" }, b: { src: "GolfBox-import · 20.09.2026", name: "Tobias S. Lindvik", born: "2009", email: "—", phone: "900 11 223", club: "Borregaard Golfklubb", parent: "—" }, match: "Telefon og fødselsår er like" },
    { id: "u2", a: { src: "Booking · 22.09.2026", name: "Lea Brekke", born: "2011", email: "lea.b@demo.no", phone: "—", club: "Hvaler GK", parent: "Tor Brekke" }, b: { src: "Påmelding · 21.09.2026", name: "Lea Brekke", born: "—", email: "lea.b@demo.no", phone: "911 22 334", club: "—", parent: "Tor Brekke" }, match: "E-post og forelder er like" },
  ],
  mod: [{ id: "m1", where: "Utfordring · Putting 5 fot", who: "Deltaker i Talent U16", text: "Innlegget er skjult til du har vurdert det.", reason: "Meldt av Ella Strand · «Stygg kommentar om en annen spiller»", at: "26.09.2026 10:14" }],
  follow: [
    { id: "f1", col: "risiko", who: "Oskar Vik", grp: "Talent U16", why: "11 dager uten registrert økt", src: "ØKTLOGG · 26.09.2026", by: "Oppfølgingsagent", at: "26.09 09:05" },
    { id: "f2", col: "risiko", who: "Tobias Lindvik", grp: "WANG Toppidrett", why: "ACWR 1,58 · tre økter over plan", src: "BELASTNING · 26.09.2026", by: "Belastningsagent", at: "26.09 13:48" },
    { id: "f3", col: "folg", who: "Thea Nilsen", grp: "Talent U16", why: "Dagsform 2 av 5 tre dager på rad", src: "DAGSFORM · 25.09.2026", by: "Anders Kristiansen", at: "25.09 20:10" },
    { id: "f4", col: "folg", who: "Jonas Lie", grp: "WANG Toppidrett", why: "Håndledd venstre · −20 % volum til 06.10", src: "HELSE · 22.09.2026", by: "Anders Kristiansen", at: "22.09 16:30" },
    { id: "f5", col: "sjekk", who: "Nora Bakke", grp: "WANG Toppidrett", why: "Følger planen igjen siden 24.09. Saken er åpen til du setter Løst.", src: "PLAN · 26.09.2026", by: "Oppfølgingsagent", at: "24.09 21:00", back: true },
    { id: "f6", col: "sjekk", who: "Emil Solberg", grp: "Talent U16", why: "Ba om samtale om skole og trening", src: "MELDING · 23.09.2026", by: "Anders Kristiansen", at: "23.09 18:45" },
    { id: "f7", col: "lost", who: "Ella Strand", grp: "Talent U16", why: "Manglet samtykke til video", src: "SAMTYKKE · 25.09.2026", by: "Anders Kristiansen", at: "25.09 19:12", prev: "sjekk" },
  ],
  threads: [
    { id: "s1", who: "Tobias Lindvik", role: "Spiller", sub: "Kan vi ta putting i stedet på lørdag?", at: "26.09 13:10", unread: true, msgs: [["Tobias Lindvik", "13:10", "Hei! Kan vi ta putting i stedet for pitch på lørdag? Klubbmesterskapet er søndag."]], draft: "Hei Tobias. Ja, vi bytter til putting 3–10 fot lørdag. Jeg legger det inn i planen i kveld. Anders" },
    { id: "s2", who: "Hanne Lindvik", role: "Forelder til Tobias", sub: "Samling Oslo 10.–11.10", at: "26.09 11:48", unread: true, msgs: [["Hanne Lindvik", "11:48", "Hei. Gjelder samlingen i Oslo. Hvem kjører, og når er vi tilbake søndag?"]], draft: "Hei Hanne. AK Golf kjører minibuss fra Borregaard GK lørdag 10.10 kl. 07:30. Vi er tilbake søndag ca. 18:00. Hilsen Anders" },
    { id: "s3", who: "Thea Nilsen", role: "Spiller", sub: "Hvilken tee på 7. hull?", at: "26.09 09:12", unread: false, msgs: [["Thea Nilsen", "09:12", "Hvilken tee bruker vi på 7. hull i morgen?"], ["Anders Kristiansen", "09:30", "Gul tee. Jern 6 fra tee, så har du 110 m inn."]] },
  ],
  drafts: [
    { id: "e1", to: "Hanne Lindvik", toRole: "Forelder til Tobias", subject: "Ukeplan uke 40 for Tobias", body: "Hei Hanne.\n\nTobias' plan for uke 40 er godkjent: 5 økter, 6 timer. Torsdag er hviledag etter høy belastning denne uka.\n\nHilsen Anders", from: "Jarvis", at: "26.09 13:52", tpl: "Ukeplan til forelder" },
    { id: "e2", to: "Tor Brekke", toRole: "Forelder til Lea", subject: "Bekreftet privattime 26.09", body: "Hei Tor.\n\nLea har privattime i dag kl. 17:00 i Studio 1. Ta med treningstøy og egne køller.\n\nHilsen Anders", from: "Anders Kristiansen", at: "25.09 20:05", tpl: "Bookingbekreftelse" },
  ],
  templates: [
    { id: "ukeplan", name: "Ukeplan til forelder", used: 42, edited: "12.09.2026", subject: "Ukeplan uke {{uke}} for {{spiller.fornavn}}", body: "Hei {{forelder.fornavn}}.\n\n{{spiller.fornavn}}s plan for uke {{uke}} er godkjent: {{plan.antall}} økter, {{plan.timer}}.\n\nHilsen {{coach.fornavn}}" },
    { id: "booking", name: "Bookingbekreftelse", used: 118, edited: "02.09.2026", subject: "Bekreftet {{tjeneste}} {{dato}}", body: "Hei {{mottaker.fornavn}}.\n\n{{spiller.fornavn}} har {{tjeneste}} {{dato}} kl. {{tid}} i {{sted}}.\n\nHilsen {{coach.fornavn}}" },
    { id: "avvist", name: "Booking avvist", used: 9, edited: "26.09.2026", subject: "Vi kunne ikke ta {{tjeneste}} {{dato}}", body: "Hei {{mottaker.fornavn}}.\n\n{{begrunnelse}}\n\nFinn en ny tid i PlayerHQ under Booking.\n\nHilsen {{coach.fornavn}}" },
  ],
  vars: { "uke": "40", "spiller.fornavn": "Tobias", "forelder.fornavn": "Hanne", "mottaker.fornavn": "Hanne", "plan.antall": "5", "plan.timer": "6 timer", "coach.fornavn": "Anders", "tjeneste": "privattime", "dato": "tirsdag 29.09", "tid": "17:00", "sted": "Studio 1", "begrunnelse": "Studio 1 er stengt for service tirsdag." },
  cal: {
    days: [["Ma", "28.09"], ["Ti", "29.09"], ["On", "30.09"], ["To", "01.10"], ["Fr", "02.10"], ["Lø", "03.10"], ["Sø", "04.10"]],
    teams: ["WANG Toppidrett", "Talent U16", "Privattimer"],
    ev: [
      { id: "c1", d: 0, s: 7, l: 1.5, k: "felles", team: "WANG Toppidrett", title: "WANG morgentrening", where: "Borregaard GK · treningsområde", axis: ["tek", "slag"], n: 12 },
      { id: "c2", d: 0, s: 15, l: 1, k: "privat", team: "Privattimer", title: "Privattime · Tobias Lindvik", where: "Studio 1 · TrackMan", axis: ["tek"] },
      { id: "c3", d: 0, s: 16, l: 1, k: "ledig" },
      { id: "c4", d: 0, s: 17, l: 1.5, k: "felles", team: "Talent U16", title: "Talent U16", where: "Nærspillsområde", axis: ["slag"], n: 9 },
      { id: "c5", d: 1, s: 7, l: 1.5, k: "felles", team: "WANG Toppidrett", title: "WANG morgentrening", where: "Treningsområde", axis: ["fys"], n: 12 },
      { id: "c6", d: 1, s: 12, l: 1, k: "opptatt", title: "Møte · NGF region Øst" },
      { id: "c7", d: 1, s: 17, l: 1, k: "privat", team: "Privattimer", title: "Privattime · Jonas Lie", where: "Studio 1 · TrackMan", axis: ["tek", "slag"] },
      { id: "c8", d: 2, s: 7, l: 1.5, k: "felles", team: "WANG Toppidrett", title: "WANG morgentrening", where: "Treningsområde", axis: ["slag"], n: 11 },
      { id: "c9", d: 2, s: 14, l: 1, k: "ledig" },
      { id: "c10", d: 2, s: 16, l: 1.5, k: "felles", team: "Talent U16", title: "Talent U16", where: "Treningsområde", axis: ["tek", "fys"], n: 9 },
      { id: "c11", d: 3, s: 7, l: 1.5, k: "felles", team: "WANG Toppidrett", title: "WANG morgentrening", where: "Treningsområde", axis: ["spill"], n: 12 },
      { id: "c12", d: 3, s: 16, l: 1, k: "privat", team: "Privattimer", title: "Privattime · Thea Nilsen", where: "Bane · hull 1–3", axis: ["spill"] },
      { id: "c13", d: 3, s: 18, l: 1, k: "ledig" },
      { id: "c14", d: 4, s: 7, l: 1.5, k: "felles", team: "WANG Toppidrett", title: "WANG morgentrening", where: "Treningsområde", axis: ["slag"], n: 10 },
      { id: "c15", d: 4, s: 13, l: 4, k: "opptatt", title: "Trenerkurs NGF · trinn 3" },
      { id: "c16", d: 5, s: 9, l: 3, k: "felles", team: "WANG Toppidrett", title: "Banespill · hele stallen", where: "Borregaard GK · 18 hull", axis: ["spill", "turn"], n: 18 },
      { id: "c17", d: 5, s: 13, l: 1.5, k: "privat", team: "Privattimer", title: "Privattime · Lea Brekke", where: "Studio 1 · TrackMan", axis: ["tek"] },
    ],
    stall: [
      ["Tobias Lindvik", "WANG Toppidrett", "SLAG · Innspill ca. 100 m", ["slag"], "16:00", "Planlagt"],
      ["Magnus Aasheim", "WANG Toppidrett", "Hviledag", [], "—", "Hvile"],
      ["Sara Holm", "WANG Toppidrett", "TEK · Utslag · startretning", ["tek"], "15:00", "Planlagt"],
      ["Jonas Lie", "WANG Toppidrett", "Privattime · TEK og SLAG", ["tek", "slag"], "17:00", "Planlagt"],
      ["Thea Nilsen", "Talent U16", "FYS · Bevegelighet", ["fys"], "16:30", "Planlagt"],
      ["Emil Solberg", "Talent U16", null, [], "—", "Ingen plan"],
    ],
    avail: [["Mandag", "15:00–20:00", true], ["Tirsdag", "15:00–20:00", true], ["Onsdag", "14:00–19:00", true], ["Torsdag", "15:00–20:00", true], ["Fredag", "—", false], ["Lørdag", "13:00–16:00", true], ["Søndag", "—", false]],
    except: [["02.10.2026", "Trenerkurs NGF · 13:00–17:00"], ["10.10–11.10.2026", "Samling Oslo GK"]],
  },
  services: [
    { id: "pt60", name: "Privattime", min: 60, clip: true, active: true, where: "Studio 1 eller bane" },
    { id: "pt30", name: "Privattime", min: 30, clip: true, active: true, where: "Studio 1" },
    { id: "bane", name: "Banecoaching 9 hull", min: 150, clip: true, active: true, where: "Borregaard GK" },
    { id: "bay", name: "TrackMan-bay uten coach", min: 60, clip: false, active: true, price: 350, where: "Studio 2" },
    { id: "grp", name: "Gruppetime 4 spillere", min: 60, clip: false, active: false, price: 1600, where: "Treningsområde" },
  ],
  rate: 950,
  bookings: [
    { id: "b1", st: "Bekreftet", src: "PlayerHQ · klipp", who: "Tobias Lindvik", guardian: "Hanne Lindvik", svc: "pt60", date: "Ti 29.09", t: "17:00", pay: "Klipp · Performance Pro · 3 av 4 igjen i september", note: "«Vil jobbe med putting før klubbmesterskapet»", at: "26.09 12:30", by: "Automatisk · klipp trukket 26.09 12:30" },
    { id: "b2", st: "Bekreftet", src: "Offentlig booking", who: "Lea Brekke", guardian: "Tor Brekke", svc: "pt60", date: "On 30.09", t: "14:00", pay: "Kort · Stripe · betalt", note: "Ny spiller · første økt", at: "26.09 10:05", by: "Automatisk · betalt 26.09 10:05" },
    { id: "b3", st: "Venter", src: "Forelder · faktura, ikke betalt", who: "Kasper Moen", guardian: "Hege Moen", svc: "bane", date: "Lø 03.10", t: "13:00", pay: "Faktura til forelder", note: "—", at: "25.09 21:40" },
    { id: "b4", st: "Bekreftet", src: "PlayerHQ · klipp", who: "Magnus Aasheim", guardian: "Line Aasheim", svc: "pt60", date: "Lø 26.09", t: "15:30", pay: "Klipp · Performance · 1 av 2 igjen i september", note: "—", at: "20.09 18:00", by: "Anders Kristiansen · 20.09 18:12" },
    { id: "b5", st: "Bekreftet", src: "Offentlig booking", who: "Lea Brekke", guardian: "Tor Brekke", svc: "pt60", date: "Lø 26.09", t: "17:00", pay: "Kort · Stripe · betalt", note: "—", at: "22.09 09:10", by: "Anders Kristiansen · 22.09 09:30" },
    { id: "b6", st: "Avvist", src: "Forelder · faktura, ikke betalt", who: "Thea Nilsen", guardian: "Kjersti Nilsen", svc: "pt30", date: "Fr 02.10", t: "16:00", pay: "—", note: "—", at: "24.09 17:20", by: "Anders Kristiansen · 24.09 19:02", reason: "Trenerkurs NGF hele fredag ettermiddag." },
  ],
};
