import assert from "node:assert/strict";
import { before,beforeEach,mock,test } from "node:test";
import { initialSessionExecution,readSessionExecution } from "./wb-session-life";
let row:Record<string,unknown>;let viewer={id:"player",role:"PLAYER"};let scoped=false;let writes=0;let collision=false;
mock.module("@/lib/auth/requirePortalUser",{namedExports:{requirePortalUser:async()=>viewer}});
mock.module("@/lib/auth/coached",{namedExports:{harCoachTilgangTilSpiller:async()=>scoped}});
mock.module("next/cache",{namedExports:{revalidatePath:()=>undefined}});
mock.module("@/lib/prisma",{namedExports:{prisma:{workbenchSession:{
 findUnique:async()=>row,
 updateMany:async({where,data}:{where:Record<string,unknown>;data:Record<string,unknown>})=>{assert.equal(where.playerId,row.playerId);assert.equal((where.updatedAt as Date).getTime(),(row.updatedAt as Date).getTime());writes++;if(collision)return {count:0};Object.assign(row,data,{updatedAt:new Date((row.updatedAt as Date).getTime()+1)});return {count:1};},
}}}});
let actions:typeof import("./wb-session-life-actions");
before(async()=>{actions=await import("./wb-session-life-actions");});
beforeEach(()=>{viewer={id:"player",role:"PLAYER"};scoped=false;writes=0;collision=false;row={id:"s",playerId:"player",coachId:"coach",status:"IN_PROGRESS",date:new Date("2026-09-01T00:00:00Z"),startMinute:0,durationMinutes:60,title:"Syntetisk økt",pyramid:"TEK",blockType:"OEKT",origin:"COACH",createdBy:"PLAYER",drills:[],createdAt:new Date(0),updatedAt:new Date(0),actualMinutes:null,perceivedEffort:null,isTemplate:false,hiddenByPlayer:false,needsPlayerApproval:false,approvalStatus:null,localOverride:true,liveSnapshot:{execution:initialSessionExecution(new Date().toISOString()),future:{opaque:true}}};});
function input(action="PAUSE",patch:Record<string,unknown>={}){return {sessionId:"s",expectedUpdatedAt:(row.updatedAt as Date).toISOString(),requestId:`synthetic-${action}`,action,...patch};}
test("pause, ny lesing og fortsett bevarer ID, lokal overstyring og råhistorikk",async()=>{assert.equal((await actions.mutateSessionExecution(input())).ok,true);assert.equal(row.status,"IN_PROGRESS");assert.equal(readSessionExecution(row.liveSnapshot)?.phase,"PAUSED");const read=await actions.loadSessionExecution("s");assert.equal(read.ok,true);assert.equal((await actions.mutateSessionExecution(input("RESUME"))).ok,true);assert.equal(row.id,"s");assert.equal(row.localOverride,true);assert.deepEqual((row.liveSnapshot as Record<string,unknown>).future,{opaque:true});});
test("slutt og etterregistrert retting skiller 0/null og krever årsak",async()=>{assert.equal((await actions.mutateSessionExecution(input("FINISH",{actualMinutes:0}))).ok,true);assert.equal(row.actualMinutes,0);assert.equal((await actions.mutateSessionExecution(input("RECORD",{outcome:"COMPLETED",actualMinutes:null}))).ok,false);assert.equal((await actions.mutateSessionExecution(input("RECORD",{outcome:"COMPLETED",actualMinutes:null,reason:"Syntetisk feilregistrering"}))).ok,true);assert.equal(row.actualMinutes,null);assert.equal(readSessionExecution(row.liveSnapshot)?.events.length,2);});
test("samme request retry skriver aldri igjen, og stale versjon endrer ikke historikken",async()=>{const request=input();assert.equal((await actions.mutateSessionExecution(request)).ok,true);assert.equal((await actions.mutateSessionExecution(request)).ok,true);assert.equal(writes,1);const snapshot=structuredClone(row.liveSnapshot);assert.equal((await actions.mutateSessionExecution({...input("RESUME"),expectedUpdatedAt:new Date(0).toISOString()})).ok,false);assert.deepEqual(row.liveSnapshot,snapshot);assert.equal(writes,1);});
test("CAS-kollisjon avvises og setter ikke på pause",async()=>{collision=true;assert.equal((await actions.mutateSessionExecution(input())).ok,false);assert.equal(readSessionExecution(row.liveSnapshot)?.phase,"ACTIVE");});
test("egen og bekreftet trener har tilgang; fremmed trener/spiller/forelder avvises",async()=>{for(const role of ["PLAYER","COACH","PARENT"]){viewer={id:"foreign",role};assert.equal((await actions.loadSessionExecution("s")).ok,false);assert.equal((await actions.mutateSessionExecution(input())).ok,false);}viewer={id:"coach",role:"COACH"};scoped=true;assert.equal((await actions.mutateSessionExecution(input())).ok,true);});
test("skjult, pending, avvist, mal og gruppemaster kan ikke endres",async()=>{for(const patch of [{hiddenByPlayer:true},{needsPlayerApproval:true},{approvalStatus:"REJECTED"},{isTemplate:true},{groupId:"g",id:`wb-group-${"a".repeat(64)}`}]){const original={...row};Object.assign(row,patch);assert.equal((await actions.mutateSessionExecution(input())).ok,false);row=original;}assert.equal(writes,0);});
test("avbrudd krever årsak og beholder faktisk 45; kan ikke gjenstartes som pause",async()=>{row.actualMinutes=45;assert.equal((await actions.mutateSessionExecution(input("ABORT"))).ok,false);assert.equal((await actions.mutateSessionExecution(input("ABORT",{reason:"Syntetisk avbrudd"}))).ok,true);assert.equal(row.status,"ABANDONED");assert.equal(row.actualMinutes,45);assert.equal((await actions.mutateSessionExecution(input("RESUME"))).ok,false);});
test("fremtidig registrering, utkast og ukjent JSON-versjon avvises",async()=>{row.status="PUBLISHED";row.date=new Date("2099-01-01T00:00:00Z");assert.equal((await actions.mutateSessionExecution(input("RECORD",{outcome:"COMPLETED",actualMinutes:0,reason:"Syntetisk"}))).ok,false);row.date=new Date(0);row.status="DRAFT";assert.equal((await actions.mutateSessionExecution(input("RECORD",{outcome:"COMPLETED",reason:"Syntetisk"}))).ok,false);row.status="IN_PROGRESS";row.liveSnapshot={execution:{version:4},raw:"bevar"};assert.equal((await actions.mutateSessionExecution(input())).ok,false);assert.equal(writes,0);});
