import assert from "node:assert/strict";
import {before,beforeEach,mock,test} from "node:test";
import * as React from "react";
import {createSession} from "@/lib/domain/workbench/operations";
import type {WorkbenchSession} from "@/lib/domain/workbench/types";
import {ExecutionCommandSchema,initialSessionExecution,readSessionExecution,transitionSessionExecution,type ExecutionCommand} from "@/lib/workbench/wb-session-life";
const states=new Map<string,unknown[]>();let context="",cursor=0;const effects=new Map<string,{deps:unknown[];cleanup?:()=>void}>();const transitions:Promise<unknown>[]=[];
function draw<T>(name:string,fn:()=>T):T{context=name;cursor=0;return fn();}
function useState<T>(initial:T|(()=>T)):[T,(value:T|((old:T)=>T))=>void]{const slots=states.get(context)??[];states.set(context,slots);const i=cursor++;if(!(i in slots))slots[i]=typeof initial==="function"?(initial as()=>T)():initial;return [slots[i] as T,value=>{slots[i]=typeof value==="function"?(value as(old:T)=>T)(slots[i] as T):value;}];}
function useRef<T>(initial:T){const [value]=useState(()=>({current:initial}));return value;}
function useEffect(fn:()=>void|(()=>void),deps:unknown[]=[]){const key=`${context}:${cursor++}`;const old=effects.get(key);if(!old||deps.some((v,i)=>v!==old.deps[i])){old?.cleanup?.();effects.set(key,{deps,cleanup:fn()||undefined});}}
mock.module("react",{namedExports:{...React,useState,useRef,useEffect,useMemo:(fn:()=>unknown)=>fn(),useTransition:()=>[false,(fn:()=>Promise<unknown>)=>transitions.push(fn())]}});
mock.module("next/link",{defaultExport:"a"});mock.module("next/navigation",{namedExports:{useRouter:()=>({replace(){}})}});
for(const css of ["precision-a4.css","precision-a9.css"])mock.module(`@/styles/${css}`,{namedExports:{}});
mock.module("@/components/precision/pa",{namedExports:{Ikon:"i",Knapp:"button",AKSE_NAVN:{fys:"FYS",tek:"TEK",slag:"SLAG",spill:"SPILL",turn:"TURN"}}});
mock.module("@/components/precision/pa-a4",{namedExports:{Ark:"sheet",Dialogboks:"dialog",Nokkelverdi:"values"}});
mock.module("@/components/precision/pa-a5",{namedExports:{InlineVarsel:"warning"}});mock.module("@/components/precision/pa-a2",{namedExports:{Sokefelt:"input"}});
mock.module("@/components/precision/pa-workbench",{namedExports:{AKSER:["fys","tek","slag","spill","turn"],Caps:"small",Valgpille:"pill",akseFra:(s:string)=>s.toLowerCase(),akseStil:()=>({})}});
let session:WorkbenchSession;let snapshot:unknown;const calls:ExecutionCommand[]=[];let lostReply=false,failWrite=false,failRefetch=false;let readCount=0;
const saved:{session:WorkbenchSession;phase:string|null}[]=[];
mock.module("@/lib/workbench/wb-session-life-actions",{namedExports:{
 loadSessionExecution:async()=>{readCount++;if(failRefetch&&readCount>1)throw Error("Syntetisk historikknettfeil");return {ok:true,data:{session,execution:readSessionExecution(snapshot),unknownVersion:false,updatedAt:session.updatedAt}};},
 mutateSessionExecution:async(input:unknown)=>{const command=ExecutionCommandSchema.parse(input);calls.push(command);if(failWrite)return {ok:false,error:"Syntetisk lagringsfeil"};const next=transitionSessionExecution(command,{status:session.status,actualMinutes:session.actualMinutes??null,perceivedEffort:session.perceivedEffort??null,liveSnapshot:snapshot},"synthetic-owner","2026-10-02T10:00:00.000Z");if(!next.retry){if(command.expectedUpdatedAt!==session.updatedAt)return {ok:false,error:"Samtidig endring"};snapshot=next.snapshot;session={...session,status:next.status as WorkbenchSession["status"],actualMinutes:next.actualMinutes,perceivedEffort:next.perceivedEffort,updatedAt:new Date(Date.parse(session.updatedAt)+1).toISOString()};}if(lostReply){lostReply=false;throw Error("Syntetisk svar tapt etter lagring");}return {ok:true,data:session,execution:readSessionExecution(snapshot)};},
}});
let Panel:typeof import("@/components/workbench/SessionExecutionPanel").SessionExecutionPanel;let OktArk:typeof import("@/components/admin/precision/AG11Ark").OktArk;
before(async()=>{({SessionExecutionPanel:Panel}=await import("@/components/workbench/SessionExecutionPanel"));({OktArk}=await import("@/components/admin/precision/AG11Ark"));});
beforeEach(()=>{states.clear();effects.clear();transitions.length=0;calls.length=0;saved.length=0;lostReply=false;failWrite=false;failRefetch=false;readCount=0;session={...createSession({playerId:"synthetic-owner",coachId:"synthetic-coach",date:"2026-09-01",startMinute:600,durationMinutes:60,title:"Syntetisk økt",pyramid:"TEK",createdBy:"PLAYER"}),id:"synthetic-session",status:"COMPLETED",actualMinutes:45,updatedAt:"2026-10-02T08:00:00.000Z"};snapshot={unknown:{keep:0}};});
type Node=React.ReactElement<Record<string,unknown>>;
function nodes(value:React.ReactNode):Node[]{if(Array.isArray(value))return value.flatMap(nodes);if(!React.isValidElement<Record<string,unknown>>(value))return [];return [value,...nodes(value.props.children as React.ReactNode)];}
function find(tree:React.ReactNode,match:(node:Node)=>boolean){const node=nodes(tree).find(match);assert.ok(node,"Kontroll i faktisk komponent finnes");return node;}
function text(value:React.ReactNode):string{if(typeof value==="string"||typeof value==="number")return String(value);if(Array.isArray(value))return value.map(text).join(" ");if(React.isValidElement<Record<string,unknown>>(value))return text(value.props.children as React.ReactNode);return "";}
function change(tree:React.ReactNode,label:string,value:string){(find(tree,n=>n.props["aria-label"]===label).props.onChange as(e:{target:{value:string}})=>void)({target:{value}});}
function click(tree:React.ReactNode,label:string){const button=find(tree,n=>n.type==="button"&&n.props.children===label);assert.equal(button.props.disabled,false);(button.props.onClick as()=>void)();}
function render(live=false){return draw("panel",()=>Panel({session,live,onSaved:(row,execution)=>saved.push({session:row,phase:execution?.phase??null})}));}
async function settle(){await Promise.resolve();await Promise.resolve();while(transitions.length)await transitions.shift();await Promise.resolve();}
async function ready(live=false){render(live);await settle();return render(live);}
test("faktisk registrering viser null/0/45 separat fra planlagt; input bruker heltall 0–1440",async()=>{for(const actualMinutes of [null,0,45]){states.clear();effects.clear();session={...session,actualMinutes};const tree=await ready();assert.match(text(tree),/Planlagt tid\s+60\s+min/);assert.match(text(tree),actualMinutes===null?/Faktisk tid Ikke registrert/:new RegExp(`Faktisk tid ${actualMinutes} min`));const input=find(tree,n=>n.props["aria-label"]==="Faktiske minutter");assert.equal(input.props.min,0);assert.equal(input.props.max,1440);assert.equal(input.props.step,1);assert.equal(input.props.value,actualMinutes==null?"":String(actualMinutes));}});
test("montert etterregistrering 45→0 lagrer årsak med samme økt-ID og bekreftet status",async()=>{await ready();change(render(),"Faktiske minutter","0");change(render(),"Årsak","Syntetisk korrigering");click(render(),"Lagre etterregistrering");assert.match(text(render()),/Lagrer/);await settle();assert.equal(session.actualMinutes,0);assert.equal(calls[0].sessionId,"synthetic-session");assert.equal(calls[0].reason,"Syntetisk korrigering");assert.equal(readSessionExecution(snapshot)?.events[0].before.actualMinutes,45);assert.match(text(render()),/Lagring bekreftet/);assert.equal(saved.length,1);});
test("feil og brøkdelsminutter gir aldri lagret-bekreftelse eller navigasjonscallback",async()=>{await ready();change(render(),"Årsak","Syntetisk");for(const value of ["-1","0.5","1441","NaN"]){change(render(),"Faktiske minutter",value);click(render(),"Lagre etterregistrering");await settle();assert.match(text(render()),/Ikke lagret/);}assert.equal(calls.length,0);change(render(),"Faktiske minutter","0");failWrite=true;click(render(),"Lagre etterregistrering");await settle();assert.equal(saved.length,0);assert.match(text(render()),/Syntetisk lagringsfeil/);});
test("tapt svar etter persistert retting gir samme request/versjon ved retry og bare én historikkpost",async()=>{await ready();change(render(),"Årsak","Syntetisk tapt svar");change(render(),"Faktiske minutter","0");lostReply=true;click(render(),"Lagre etterregistrering");await settle();assert.equal(saved.length,0);assert.match(text(render()),/Ikke lagret/);click(render(),"Lagre etterregistrering");await settle();assert.equal(calls.length,2);assert.equal(calls[0].requestId,calls[1].requestId);assert.equal(calls[0].expectedUpdatedAt,calls[1].expectedUpdatedAt);assert.equal(readSessionExecution(snapshot)?.events.length,1);assert.equal(saved.length,1);});
test("nytt utkast etter avvist lagring får ny request, refetch-feil endrer ikke bekreftet mutasjon",async()=>{await ready();change(render(),"Årsak","Syntetisk første forsøk");failWrite=true;click(render(),"Lagre etterregistrering");await settle();const first=calls[0].requestId;change(render(),"Årsak","Syntetisk nytt ønske");change(render(),"Faktiske minutter","0");failWrite=false;failRefetch=true;click(render(),"Lagre etterregistrering");await settle();assert.notEqual(calls[1].requestId,first);assert.equal(saved.length,1);assert.match(text(render()),/Lagring bekreftet/);assert.match(text(render()),/historikken kunne ikke hentes/);assert.equal(saved[0].phase,"COMPLETED");});
test("faktisk Live-panel pause→fortsett→avbryt og 0, også uten øvelser",async()=>{session={...session,status:"IN_PROGRESS",actualMinutes:null};snapshot={execution:initialSessionExecution("2026-10-02T08:00:00.000Z")};await ready(true);click(render(true),"Pause økt");await settle();assert.match(text(render(true)),/På pause/);click(render(true),"Fortsett økt");await settle();change(render(true),"Faktiske minutter","0");change(render(true),"Årsak","Syntetisk avbrudd");click(render(true),"Avbryt økt");await settle();assert.equal(session.status,"ABANDONED");assert.equal(session.actualMinutes,0);assert.equal(saved.at(-1)?.phase,"ABANDONED");});
test("faktisk OktArk monterer samme økt-ID og callback til motorens nylesing",()=>{let reloads=0;const motor={travel:false,lastPaaNytt:async()=>{reloads++;}} as unknown as Parameters<typeof OktArk>[0]["motor"];const tree=draw("ark",()=>OktArk({session,spillerNavn:"Syntetisk spiller",motor,onLukk(){},onApneOkt(){},onNyOvelse(){}}));const child=find(tree,n=>n.type===Panel);assert.equal((child.props.session as WorkbenchSession).id,session.id);(child.props.onSaved as()=>void)();assert.equal(reloads,1);});
