import test from "node:test";
import assert from "node:assert/strict";
import { patternScore, bestMatch, navigationKind, buildRegister } from "./bygg-skjermregister.mjs";
import { PRECISION_TYPER } from "./skjermregister-typer.mjs";

test("dynamic segment names do not have to match, and an exact type beats a prefix", () => {
  assert.ok(patternScore("/portal/live/[id]/active", "/portal/live/[sessionId]/active") >= 2000);
  assert.equal(patternScore("/team-norway/[groupId]", "/team-norway/analyse"), -1);
  assert.ok(patternScore("/team-norway/[groupId]", "/team-norway/[groupId]") >= 2000);
  const active = bestMatch("/portal/live/[sessionId]/active", PRECISION_TYPER);
  assert.equal(active.type.id, "PH-05");
  assert.equal(bestMatch("/portal/tren/tester/ny", PRECISION_TYPER).type.id, "PH-14");
  assert.equal(bestMatch("/portal/tren/tester/[testId]/gjennomfor", PRECISION_TYPER).type.id, "PH-15");
  assert.equal(bestMatch("/portal/meg/bookinger/reschedule/[bookingId]", PRECISION_TYPER).type.id, "PH-23");
  assert.equal(bestMatch("/admin/spillere/[id]/rediger", PRECISION_TYPER).type.id, "AG-08");
  assert.equal(bestMatch("/admin/spillere/[id]/plan/[planId]", PRECISION_TYPER).type.id, "AG-10");
  assert.equal(bestMatch("/innsyn/talent/discovery", PRECISION_TYPER).type.id, "AG-22");
  assert.equal(bestMatch("/stats/pga/spillere/[dg_id]", PRECISION_TYPER).type.id, "ST-03");
  assert.equal(bestMatch("/stats/pga/drive-distance", PRECISION_TYPER).type.id, "ST-05");
  assert.equal(PRECISION_TYPER.length, 74);
});

test("auth redirects are not screens, and a screen may import redirect", () => {
  assert.equal(navigationKind('import { redirect } from "next/navigation";\nexport default function Page(){ redirect("/admin/agencyos"); }\n').kind, "videresending");
  assert.equal(navigationKind('import { notFound } from "next/navigation";\nexport default function Page(){ notFound(); }\n').kind, "notFound");
  assert.equal(navigationKind('import { redirect } from "next/navigation";\nexport default function Page(){ return <Dashboard />; }\n'), null);
  assert.equal(navigationKind("export default function Page(){ const x: Promise<string> = redirect(\"/x\") as Promise<string>; }\n").kind, "videresending");
});

test("every current page file gets an explanation and an owner", () => {
  const register = buildRegister(process.cwd());
  assert.equal(register.presisjon.skjermtyper, 74);
  assert.equal(register.sider.length, register.inventar.pageFiles);
  assert.equal(new Set(register.sider.map((row) => row.kildefil)).size, register.sider.length);
  for (const row of register.sider) {
    assert.ok(row.forklaring && row.eier === "D01-skjermregister" && row.kobling && row.screenId);
    assert.equal(row.status.kontrollertIApp, false);
    if (row.status.implementert === "ikke-verifisert") assert.equal(row.kontrollbevis, null);
  }
  const byRoute = new Map(register.sider.map((row) => [row.rute, row]));
  assert.equal(byRoute.get("/portal").screenId, "PH-01");
  assert.equal(byRoute.get("/portal").status.valgtForBygging, true);
  assert.equal(byRoute.get("/portal").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal").kontrollbevis, /PH01IDag/);
  assert.equal(byRoute.get("/admin").kobling, "videresending");
  assert.equal(byRoute.get("/team-gfgk").screenId, "AVSLATT");
  assert.equal(byRoute.get("/").screenId, "MK-FORSIDE");
  assert.equal(byRoute.get("/team-norway/college").screenId, "TN-15");
  assert.match(byRoute.get("/team-norway/college").avvik.join(" "), /TN-06/);
  assert.equal(byRoute.get("/portal/planlegge").screenId, "PH-10");
  assert.equal(byRoute.get("/portal/planlegge").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/planlegge").kontrollbevis, /PH10Plan/);
  assert.equal(byRoute.get("/portal/gjennomfore").screenId, "PH-02");
  assert.equal(byRoute.get("/portal/gjennomfore").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/gjennomfore").kontrollbevis, /PH02Gjor/);
  assert.equal(byRoute.get("/portal/gjennomfore/[id]").screenId, "PH-03");
  assert.equal(byRoute.get("/portal/gjennomfore/[id]").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/gjennomfore/[id]").kontrollbevis, /PH03Oktark/);
  assert.equal(byRoute.get("/portal/live/[sessionId]/brief").screenId, "PH-04");
  assert.equal(byRoute.get("/portal/live/[sessionId]/brief").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/live/[sessionId]/brief").kontrollbevis, /PH04Brief/);
  assert.equal(byRoute.get("/portal/live/[sessionId]/active").screenId, "PH-05");
  assert.equal(byRoute.get("/portal/live/[sessionId]/active").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/live/[sessionId]/active").kontrollbevis, /PH05Live/);
  assert.equal(byRoute.get("/portal/live/[sessionId]/tapper").screenId, "PH-06");
  assert.equal(byRoute.get("/portal/live/[sessionId]/tapper").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/live/[sessionId]/tapper").kontrollbevis, /PH06Tapper/);
  assert.equal(byRoute.get("/portal/live/[sessionId]/summary").screenId, "PH-07");
  assert.equal(byRoute.get("/portal/live/[sessionId]/summary").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/live/[sessionId]/summary").kontrollbevis, /PH07Summary/);
  assert.equal(byRoute.get("/portal/tren/feiring/[planId]").screenId, "PH-07");
  assert.equal(byRoute.get("/portal/tren/feiring/[planId]").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/tren/feiring/[planId]").kontrollbevis, /PH07Feiring/);
  assert.equal(byRoute.get("/portal/analysere").screenId, "PH-16");
  assert.equal(byRoute.get("/portal/analysere").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/analysere").kontrollbevis, /PH16Stats/);
  assert.equal(byRoute.get("/portal/analysere/historikk").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/analysere/historikk").kontrollbevis, /PH16Historikk/);
  assert.equal(byRoute.get("/portal/tren/wb").screenId, "PH-02");
  assert.equal(byRoute.get("/portal/tren/wb").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/tren/wb").kontrollbevis, /PH02WbDag/);
  assert.equal(byRoute.get("/portal/tren/wb/[sessionId]").screenId, "PH-03");
  assert.equal(byRoute.get("/portal/tren/wb/[sessionId]").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/tren/wb/[sessionId]").kontrollbevis, /PH03WbArk/);
  assert.equal(byRoute.get("/portal/planlegge/workbench").screenId, "PH-11");
  assert.equal(byRoute.get("/portal/planlegge/workbench").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/planlegge/workbench").kontrollbevis, /PH11Workbench/);
  assert.equal(byRoute.get("/portal/kalender").screenId, "PH-10");
  assert.equal(byRoute.get("/portal/kalender").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/kalender").kontrollbevis, /PH10Kalender/);
  assert.equal(byRoute.get("/portal/kalender/opptatt").screenId, "PH-10");
  assert.equal(byRoute.get("/portal/kalender/opptatt").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/kalender/opptatt").kontrollbevis, /PH10Opptatt/);
  assert.equal(byRoute.get("/portal/tren/tester").screenId, "PH-14");
  assert.equal(byRoute.get("/portal/tren/tester").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/tren/tester").kontrollbevis, /PH14Hub/);
  assert.equal(byRoute.get("/portal/tren/tester/[testId]").screenId, "PH-14");
  assert.equal(byRoute.get("/portal/tren/tester/[testId]").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/tren/tester/[testId]").kontrollbevis, /PH14Detalj/);
  assert.equal(byRoute.get("/portal/tren/tester/[testId]/gjennomfor").status.implementert, "precision-visning");
  assert.equal(byRoute.get("/portal/mal").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/mal").kontrollbevis, /PH19Mal/);
  assert.equal(byRoute.get("/portal/varsler").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/varsler").kontrollbevis, /PH25Varsler/);
  assert.equal(byRoute.get("/portal/fysisk").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/fysisk").kontrollbevis, /PH26Fysisk/);
  assert.equal(byRoute.get("/auth/login").status.implementert, "precision-visning");
  assert.match(byRoute.get("/auth/login").kontrollbevis, /AU01Innlogging/);
  assert.equal(byRoute.get("/auth/logget-ut").status.implementert, "precision-visning");
  assert.match(byRoute.get("/auth/logget-ut").kontrollbevis, /AU01LoggetUt/);
  assert.equal(byRoute.get("/auth/forgot-password").status.implementert, "precision-visning");
  assert.match(byRoute.get("/auth/forgot-password").kontrollbevis, /AU03Glemt/);
  assert.equal(byRoute.get("/auth/reset-password").status.implementert, "precision-visning");
  assert.match(byRoute.get("/auth/reset-password").kontrollbevis, /AU03NyttPassord/);
  assert.equal(byRoute.get("/auth/signup").status.implementert, "precision-visning");
  assert.match(byRoute.get("/auth/signup").kontrollbevis, /AU02Registrering/);
  assert.equal(byRoute.get("/auth/check-email").status.implementert, "precision-visning");
  assert.match(byRoute.get("/auth/check-email").kontrollbevis, /AU02SjekkEpost/);
  assert.equal(byRoute.get("/auth/checkout-resume").status.implementert, "precision-visning");
  assert.match(byRoute.get("/auth/checkout-resume").kontrollbevis, /AU02Betaling/);
  assert.equal(byRoute.get("/auth/bankid").status.implementert, "precision-visning");
  assert.match(byRoute.get("/auth/bankid").kontrollbevis, /AU01BankId/);
  assert.equal(byRoute.get("/auth/guardian-consent/[token]").status.implementert, "precision-visning");
  assert.match(byRoute.get("/auth/guardian-consent/[token]").kontrollbevis, /AU05Verge/);
  assert.equal(byRoute.get("/auth/lyd-samtykke/[token]").status.implementert, "precision-visning");
  assert.match(byRoute.get("/auth/lyd-samtykke/[token]").kontrollbevis, /AU05Lyd/);
  assert.equal(byRoute.get("/auth/samtykke-venter").status.implementert, "precision-visning");
  assert.match(byRoute.get("/auth/samtykke-venter").kontrollbevis, /AU05Venter/);
  assert.equal(byRoute.get("/inviter/forelder/[token]").status.implementert, "precision-visning");
  assert.match(byRoute.get("/inviter/forelder/[token]").kontrollbevis, /AU05Invitasjon/);
  assert.equal(byRoute.get("/offline").status.implementert, "precision-visning");
  assert.match(byRoute.get("/offline").kontrollbevis, /SY01Offline/);
  assert.equal(byRoute.get("/vedlikehold").status.implementert, "precision-visning");
  assert.match(byRoute.get("/vedlikehold").kontrollbevis, /SY01Vedlikehold/);
  assert.equal(byRoute.get("/forelder").status.implementert, "precision-visning");
  assert.match(byRoute.get("/forelder").kontrollbevis, /FO01IDag/);
  assert.equal(byRoute.get("/forelder/barn").status.implementert, "precision-visning");
  assert.match(byRoute.get("/forelder/barn").kontrollbevis, /FO02BarnListe/);
  assert.equal(byRoute.get("/forelder/bookinger").status.implementert, "precision-visning");
  assert.match(byRoute.get("/forelder/bookinger").kontrollbevis, /FO03Bookinger/);
  assert.equal(byRoute.get("/forelder/okonomi").status.implementert, "precision-visning");
  assert.match(byRoute.get("/forelder/okonomi").kontrollbevis, /FO04Okonomi/);
  assert.equal(byRoute.get("/forelder/fakturaer").status.implementert, "precision-visning");
  assert.match(byRoute.get("/forelder/fakturaer").kontrollbevis, /FO04Fakturaer/);
  assert.equal(byRoute.get("/forelder/samtykke").status.implementert, "precision-visning");
  assert.match(byRoute.get("/forelder/samtykke").kontrollbevis, /FO05Samtykke/);
  assert.equal(byRoute.get("/forelder/coach").status.implementert, "precision-visning");
  assert.match(byRoute.get("/forelder/coach").kontrollbevis, /FO06Coach/);
  assert.equal(byRoute.get("/forelder/innstillinger").status.implementert, "precision-visning");
  assert.match(byRoute.get("/forelder/innstillinger").kontrollbevis, /FO06Innstillinger/);
  assert.equal(byRoute.get("/forelder/ukerapport").status.implementert, "precision-visning");
  assert.match(byRoute.get("/forelder/ukerapport").kontrollbevis, /FO01Ukerapport/);
  assert.equal(byRoute.get("/forelder/varsler").status.implementert, "precision-visning");
  assert.match(byRoute.get("/forelder/varsler").kontrollbevis, /FO01Varsler/);
  assert.equal(byRoute.get("/portal/coach").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/coach").kontrollbevis, /PH21Innboks/);
  assert.equal(byRoute.get("/portal/coach/ai").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/coach/ai").kontrollbevis, /PH22CoachKi/);
  assert.equal(byRoute.get("/portal/coach/melding").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/coach/melding").kontrollbevis, /PH21Meldingsliste/);
  assert.equal(byRoute.get("/portal/coach/melding/ny").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/coach/melding/ny").kontrollbevis, /PH21NyMelding/);
  assert.equal(byRoute.get("/portal/coach/ovelser").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/coach/ovelser").kontrollbevis, /PH13OvelserCoach/);
  assert.equal(byRoute.get("/portal/coach/plans").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/coach/plans").kontrollbevis, /PH21PlanerCoach/);
  assert.equal(byRoute.get("/portal/coach/sg-hub").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/coach/sg-hub").kontrollbevis, /PH21SgHubCoach/);
  assert.equal(byRoute.get("/portal/coach/sporsmal").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/coach/sporsmal").kontrollbevis, /PH21Sporsmalsliste/);
  assert.equal(byRoute.get("/portal/coach/sporsmal/ny").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/coach/sporsmal/ny").kontrollbevis, /PH21NyttSporsmal/);
  assert.equal(byRoute.get("/portal/coach/sporsmal/[id]").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/coach/sporsmal/[id]").kontrollbevis, /PH21SporsmalTraad/);
  assert.equal(byRoute.get("/portal/coach/tilbakemelding").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/coach/tilbakemelding").kontrollbevis, /PH21TbListe/);
  assert.equal(byRoute.get("/portal/coach/tilbakemelding/[oktId]").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/coach/tilbakemelding/[oktId]").kontrollbevis, /PH21TbOkt/);
  assert.equal(byRoute.get("/portal/coach/videoer").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/coach/videoer").kontrollbevis, /PH21Innboks/);
  assert.equal(byRoute.get("/portal/meg/abonnement").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/meg/abonnement").kontrollbevis, /PH25AboOversikt/);
  assert.equal(byRoute.get("/portal/meg/abonnement/kort/ny").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/meg/abonnement/kort/ny").kontrollbevis, /PH25NyttKort/);
  assert.equal(byRoute.get("/portal/meg/abonnement/oppgrader/flyt").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/meg/abonnement/oppgrader/flyt").kontrollbevis, /PH25OppgraderFlyt/);
  assert.equal(byRoute.get("/portal/meg/bookinger/reschedule/[bookingId]").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/meg/bookinger/reschedule/[bookingId]").kontrollbevis, /PH23FlyttTime/);
  assert.equal(byRoute.get("/portal/meg/help/kategori/[slug]").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/meg/help/kategori/[slug]").kontrollbevis, /PH25HjelpKategori/);
  assert.equal(byRoute.get("/portal/meg/helse").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/meg/helse").kontrollbevis, /PH24HelseKort/);
  assert.equal(byRoute.get("/portal/meg/helse/symptom/ny").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/meg/helse/symptom/ny").kontrollbevis, /PH24NyttSymptom/);
  assert.equal(byRoute.get("/portal/meg/innstillinger/anlegg").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/meg/innstillinger/anlegg").kontrollbevis, /PH25AnleggValg/);
  assert.equal(byRoute.get("/portal/meg/innstillinger/integrasjoner").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/meg/innstillinger/integrasjoner").kontrollbevis, /PH25Integrasjoner/);
  assert.equal(byRoute.get("/portal/meg/innstillinger/personvern").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/meg/innstillinger/personvern").kontrollbevis, /PH25Personvern/);
  assert.equal(byRoute.get("/portal/meg/innstillinger/personvern/deling").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/meg/innstillinger/personvern/deling").kontrollbevis, /PH25DelingSamtykke/);
  assert.equal(byRoute.get("/portal/meg/profil").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/meg/profil").kontrollbevis, /PH24Profil/);
  assert.equal(byRoute.get("/portal/meg/resultater").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/meg/resultater").kontrollbevis, /PH24ResultatListe/);
  assert.equal(byRoute.get("/portal/meg/sikkerhet/2fa").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/meg/sikkerhet/2fa").kontrollbevis, /PH25ToFaktor/);
  assert.equal(byRoute.get("/portal/meg/utstyr").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/meg/utstyr").kontrollbevis, /PH24Utstyr/);
  assert.equal(byRoute.get("/portal/drills").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/drills").kontrollbevis, /PH13DrillListe/);
  assert.equal(byRoute.get("/portal/booking/ny").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/booking/ny").kontrollbevis, /PH23NyBooking/);
  assert.equal(byRoute.get("/forelder/barn/[childId]").status.implementert, "precision-visning");
  assert.match(byRoute.get("/forelder/barn/[childId]").kontrollbevis, /FO02BarnDetalj/);
  assert.equal(byRoute.get("/forelder/bookinger/bekreftet").status.implementert, "precision-visning");
  assert.match(byRoute.get("/forelder/bookinger/bekreftet").kontrollbevis, /FO03BookingBekreftet/);
  assert.equal(byRoute.get("/forelder/bookinger/ny/[barnId]/bekreft").status.implementert, "precision-visning");
  assert.match(byRoute.get("/forelder/bookinger/ny/[barnId]/bekreft").kontrollbevis, /FO03NyBarnBekreft/);
  assert.equal(byRoute.get("/forelder/bookinger/ny/[barnId]").status.implementert, "precision-visning");
  assert.match(byRoute.get("/forelder/bookinger/ny/[barnId]").kontrollbevis, /FO03NyBarnTid/);
  assert.equal(byRoute.get("/forelder/bookinger/ny").status.implementert, "precision-visning");
  assert.match(byRoute.get("/forelder/bookinger/ny").kontrollbevis, /FO03VelgBarn/);
  assert.equal(byRoute.get("/forelder/samtykke/deling/[childId]").status.implementert, "precision-visning");
  assert.match(byRoute.get("/forelder/samtykke/deling/[childId]").kontrollbevis, /FO05Deling/);
  assert.equal(byRoute.get("/portal/ai/mal-bygger").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/ai/mal-bygger").kontrollbevis, /PH12MalBygger/);
  assert.equal(byRoute.get("/portal/analysere/datagolf/stasjon").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/analysere/datagolf/stasjon").kontrollbevis, /PH17DgStasjon/);
  assert.equal(byRoute.get("/portal/analysere/hull").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/analysere/hull").kontrollbevis, /PH18HullAnalyse/);
  assert.equal(byRoute.get("/portal/analysere/trackman/[id]").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/analysere/trackman/[id]").kontrollbevis, /PH17TmOkt/);
  assert.equal(byRoute.get("/portal/analysere/turneringer").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/analysere/turneringer").kontrollbevis, /PH18TurnHist/);
  assert.equal(byRoute.get("/portal/booking/coach/[coachId]").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/booking/coach/[coachId]").kontrollbevis, /PH23CoachTid/);
  assert.equal(byRoute.get("/portal/gameplan/[baneId]/hull/[nr]").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/gameplan/[baneId]/hull/[nr]").kontrollbevis, /PH20HullPlan/);
  assert.equal(byRoute.get("/portal/mal/goal/[id]").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/mal/goal/[id]").kontrollbevis, /PH19Enkeltmal/);
  assert.equal(byRoute.get("/portal/mal/runder/ny").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/mal/runder/ny").kontrollbevis, /PH09NyRunde/);
  assert.equal(byRoute.get("/portal/mal/trackman/gapping").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/mal/trackman/gapping").kontrollbevis, /PH17Gapping/);
  assert.equal(byRoute.get("/portal/tren/tester/ny/egen").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/tren/tester/ny/egen").kontrollbevis, /PH14EgenTest/);
  assert.equal(byRoute.get("/portal/tren/tester/ny").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/tren/tester/ny").kontrollbevis, /PH14OpprettTest/);
  assert.equal(byRoute.get("/portal/trening/break-tabell").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/trening/break-tabell").kontrollbevis, /PH26Break/);
  assert.equal(byRoute.get("/portal/trening/putte-laboratoriet").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/trening/putte-laboratoriet").kontrollbevis, /PH26PutteLab/);
  assert.equal(byRoute.get("/portal/tren/fys-plan").screenId, "PH-26");
  assert.equal(byRoute.get("/portal/tren/fys-plan").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/tren/fys-plan").kontrollbevis, /PH26FysPlan/);
  assert.equal(byRoute.get("/portal/tren/fys-plan/[planId]").status.implementert, "ikke-verifisert");
  assert.equal(byRoute.get("/portal/venner").screenId, "PH-24");
  assert.equal(byRoute.get("/portal/venner").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/venner").kontrollbevis, /PH24Venner/);
  assert.equal(byRoute.get("/portal/meg/foreldre").screenId, "PH-24");
  assert.equal(byRoute.get("/portal/meg/foreldre").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/meg/foreldre").kontrollbevis, /PH24Foreldre/);
  assert.equal(byRoute.get("/portal/meg/dokumenter").screenId, "PH-24");
  assert.equal(byRoute.get("/portal/meg/dokumenter").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/meg/dokumenter").kontrollbevis, /PH24Dokumenter/);
  assert.equal(byRoute.get("/portal/trening/logg").screenId, "PH-26");
  assert.equal(byRoute.get("/portal/trening/logg").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/trening/logg").kontrollbevis, /PH26TreningLogg/);
  assert.equal(byRoute.get("/portal/mal/runder").screenId, "PH-18");
  assert.equal(byRoute.get("/portal/mal/runder").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/mal/runder").kontrollbevis, /PH18Runder/);
  assert.equal(byRoute.get("/portal/gameplan").screenId, "PH-20");
  assert.equal(byRoute.get("/portal/gameplan").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/gameplan").kontrollbevis, /PH20Gameplan/);
  assert.equal(byRoute.get("/portal/coach").screenId, "PH-21");
  assert.equal(byRoute.get("/portal/coach").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/coach").kontrollbevis, /PH21Innboks/);
  assert.equal(byRoute.get("/portal/onskeligokt").screenId, "PH-21");
  assert.equal(byRoute.get("/portal/onskeligokt").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/onskeligokt").kontrollbevis, /PH21Innboks/);
  assert.equal(byRoute.get("/admin/ko").screenId, "AG-02");
  assert.equal(byRoute.get("/admin/ko").status.implementert, "precision-visning");
  assert.match(byRoute.get("/admin/ko").kontrollbevis, /AG02Ko/);
  assert.equal(byRoute.get("/admin/turnering").screenId, "AG-17");
  assert.equal(byRoute.get("/admin/turnering").status.implementert, "precision-visning");
  assert.match(byRoute.get("/admin/turnering").kontrollbevis, /AG17Turneringer/);
  assert.equal(register.tellinger.implementert, 127);
  assert.equal(register.tellinger.valgtForBygging > 0, true);
  assert.equal(register.sider.some((row) => row.status.kontrollertIApp), false);
});
