import test from "node:test";
import assert from "node:assert/strict";
import { patternScore, bestMatch, navigationKind, buildRegister } from "./bygg-skjermregister.mjs";
import { PRECISION_TYPER } from "./skjermregister-typer.mjs";

test("dynamic segment names do not have to match, and an exact type beats a prefix", () => {
  assert.ok(patternScore("/portal/live/[id]/active", "/portal/live/[sessionId]/active") >= 2000);
  assert.equal(patternScore("/team-norway/[groupId]", "/team-norway/analyse"), -1);
  assert.ok(patternScore("/team-norway/[groupId]", "/team-norway/[groupId]") >= 2000);
  const active = bestMatch("/portal/live/[sessionId]/active", PRECISION_TYPER);
  assert.equal(active.type.id, "PH-05");
  assert.equal(bestMatch("/portal/tren/tester/ny", PRECISION_TYPER).type.id, "PH-14");
  assert.equal(bestMatch("/portal/tren/tester/[testId]/gjennomfor", PRECISION_TYPER).type.id, "PH-15");
  assert.equal(bestMatch("/portal/meg/bookinger/reschedule/[bookingId]", PRECISION_TYPER).type.id, "PH-23");
  assert.equal(bestMatch("/admin/spillere/[id]/rediger", PRECISION_TYPER).type.id, "AG-08");
  assert.equal(bestMatch("/admin/spillere/[id]/plan/[planId]", PRECISION_TYPER).type.id, "AG-10");
  assert.equal(bestMatch("/innsyn/talent/discovery", PRECISION_TYPER).type.id, "AG-22");
  assert.equal(bestMatch("/stats/pga/spillere/[dg_id]", PRECISION_TYPER).type.id, "ST-03");
  assert.equal(bestMatch("/stats/pga/drive-distance", PRECISION_TYPER).type.id, "ST-05");
  assert.equal(PRECISION_TYPER.length, 74);
});

test("auth redirects are not screens, and a screen may import redirect", () => {
  assert.equal(navigationKind('import { redirect } from "next/navigation";\nexport default function Page(){ redirect("/admin/agencyos"); }\n').kind, "videresending");
  assert.equal(navigationKind('import { notFound } from "next/navigation";\nexport default function Page(){ notFound(); }\n').kind, "notFound");
  assert.equal(navigationKind('import { redirect } from "next/navigation";\nexport default function Page(){ return <Dashboard />; }\n'), null);
  assert.equal(navigationKind("export default function Page(){ const x: Promise<string> = redirect(\"/x\") as Promise<string>; }\n").kind, "videresending");
});

test("every current page file gets an explanation and an owner", () => {
  const register = buildRegister(process.cwd());
  assert.equal(register.presisjon.skjermtyper, 74);
  assert.equal(register.sider.length, register.inventar.pageFiles);
  assert.equal(new Set(register.sider.map((row) => row.kildefil)).size, register.sider.length);
  for (const row of register.sider) {
    assert.ok(row.forklaring && row.eier === "D01-skjermregister" && row.kobling && row.screenId);
    assert.equal(row.status.kontrollertIApp, false);
    if (row.status.implementert === "ikke-verifisert") assert.equal(row.kontrollbevis, null);
  }
  const byRoute = new Map(register.sider.map((row) => [row.rute, row]));
  assert.equal(byRoute.get("/portal").screenId, "PH-01");
  assert.equal(byRoute.get("/portal").status.valgtForBygging, true);
  assert.equal(byRoute.get("/portal").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal").kontrollbevis, /PH01IDag/);
  assert.equal(byRoute.get("/admin").kobling, "videresending");
  assert.equal(byRoute.get("/team-gfgk").screenId, "AVSLATT");
  assert.equal(byRoute.get("/").screenId, "MK-FORSIDE");
  assert.equal(byRoute.get("/team-norway/college").screenId, "TN-15");
  assert.match(byRoute.get("/team-norway/college").avvik.join(" "), /TN-06/);
  assert.equal(byRoute.get("/portal/planlegge").screenId, "PH-10");
  assert.equal(byRoute.get("/portal/planlegge").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/planlegge").kontrollbevis, /PH10Plan/);
  assert.equal(byRoute.get("/portal/gjennomfore").screenId, "PH-02");
  assert.equal(byRoute.get("/portal/gjennomfore").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/gjennomfore").kontrollbevis, /PH02Gjor/);
  assert.equal(byRoute.get("/portal/gjennomfore/[id]").screenId, "PH-03");
  assert.equal(byRoute.get("/portal/gjennomfore/[id]").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/gjennomfore/[id]").kontrollbevis, /PH03Oktark/);
  assert.equal(byRoute.get("/portal/live/[sessionId]/brief").screenId, "PH-04");
  assert.equal(byRoute.get("/portal/live/[sessionId]/brief").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/live/[sessionId]/brief").kontrollbevis, /PH04Brief/);
  assert.equal(byRoute.get("/portal/live/[sessionId]/active").screenId, "PH-05");
  assert.equal(byRoute.get("/portal/live/[sessionId]/active").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/live/[sessionId]/active").kontrollbevis, /PH05Live/);
  assert.equal(byRoute.get("/portal/live/[sessionId]/tapper").screenId, "PH-06");
  assert.equal(byRoute.get("/portal/live/[sessionId]/tapper").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/live/[sessionId]/tapper").kontrollbevis, /PH06Tapper/);
  assert.equal(byRoute.get("/portal/live/[sessionId]/summary").screenId, "PH-07");
  assert.equal(byRoute.get("/portal/live/[sessionId]/summary").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/live/[sessionId]/summary").kontrollbevis, /PH07Summary/);
  assert.equal(byRoute.get("/portal/tren/feiring/[planId]").screenId, "PH-07");
  assert.equal(byRoute.get("/portal/tren/feiring/[planId]").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/tren/feiring/[planId]").kontrollbevis, /PH07Feiring/);
  assert.equal(byRoute.get("/portal/analysere").screenId, "PH-16");
  assert.equal(byRoute.get("/portal/analysere").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/analysere").kontrollbevis, /PH16Analyse/);
  assert.equal(byRoute.get("/portal/analysere/historikk").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/analysere/historikk").kontrollbevis, /PH16Historikk/);
  assert.equal(byRoute.get("/portal/tren/wb").screenId, "PH-02");
  assert.equal(byRoute.get("/portal/tren/wb").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/tren/wb").kontrollbevis, /PH02WbDag/);
  assert.equal(byRoute.get("/portal/tren/wb/[sessionId]").screenId, "PH-03");
  assert.equal(byRoute.get("/portal/tren/wb/[sessionId]").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/tren/wb/[sessionId]").kontrollbevis, /PH03WbArk/);
  assert.equal(byRoute.get("/portal/planlegge/workbench").screenId, "PH-11");
  assert.equal(byRoute.get("/portal/planlegge/workbench").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/planlegge/workbench").kontrollbevis, /PH11Workbench/);
  assert.equal(byRoute.get("/portal/kalender").screenId, "PH-10");
  assert.equal(byRoute.get("/portal/kalender").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/kalender").kontrollbevis, /PH10Kalender/);
  assert.equal(byRoute.get("/portal/kalender/opptatt").screenId, "PH-10");
  assert.equal(byRoute.get("/portal/kalender/opptatt").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/kalender/opptatt").kontrollbevis, /PH10Opptatt/);
  assert.equal(byRoute.get("/portal/tren/tester").screenId, "PH-14");
  assert.equal(byRoute.get("/portal/tren/tester").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/tren/tester").kontrollbevis, /PH14Hub/);
  assert.equal(byRoute.get("/portal/tren/tester/[testId]").status.implementert, "ikke-verifisert");
  assert.equal(byRoute.get("/portal/mal").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/mal").kontrollbevis, /PH19Mal/);
  assert.equal(byRoute.get("/portal/varsler").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/varsler").kontrollbevis, /PH25Varsler/);
  assert.equal(byRoute.get("/portal/fysisk").status.implementert, "precision-visning");
  assert.match(byRoute.get("/portal/fysisk").kontrollbevis, /PH26Fysisk/);
  assert.equal(byRoute.get("/auth/login").status.implementert, "precision-visning");
  assert.match(byRoute.get("/auth/login").kontrollbevis, /AU01Innlogging/);
  assert.equal(byRoute.get("/auth/logget-ut").status.implementert, "precision-visning");
  assert.match(byRoute.get("/auth/logget-ut").kontrollbevis, /AU01LoggetUt/);
  assert.equal(byRoute.get("/auth/forgot-password").status.implementert, "precision-visning");
  assert.match(byRoute.get("/auth/forgot-password").kontrollbevis, /AU03Glemt/);
  assert.equal(byRoute.get("/auth/reset-password").status.implementert, "precision-visning");
  assert.match(byRoute.get("/auth/reset-password").kontrollbevis, /AU03NyttPassord/);
  assert.equal(byRoute.get("/auth/signup").status.implementert, "precision-visning");
  assert.match(byRoute.get("/auth/signup").kontrollbevis, /AU02Registrering/);
  assert.equal(byRoute.get("/auth/check-email").status.implementert, "precision-visning");
  assert.match(byRoute.get("/auth/check-email").kontrollbevis, /AU02SjekkEpost/);
  assert.equal(byRoute.get("/auth/checkout-resume").status.implementert, "precision-visning");
  assert.match(byRoute.get("/auth/checkout-resume").kontrollbevis, /AU02Betaling/);
  assert.equal(byRoute.get("/auth/bankid").status.implementert, "precision-visning");
  assert.match(byRoute.get("/auth/bankid").kontrollbevis, /AU01BankId/);
  assert.equal(byRoute.get("/auth/guardian-consent/[token]").status.implementert, "precision-visning");
  assert.match(byRoute.get("/auth/guardian-consent/[token]").kontrollbevis, /AU05Verge/);
  assert.equal(byRoute.get("/auth/lyd-samtykke/[token]").status.implementert, "precision-visning");
  assert.match(byRoute.get("/auth/lyd-samtykke/[token]").kontrollbevis, /AU05Lyd/);
  assert.equal(byRoute.get("/auth/samtykke-venter").status.implementert, "precision-visning");
  assert.match(byRoute.get("/auth/samtykke-venter").kontrollbevis, /AU05Venter/);
  assert.equal(byRoute.get("/inviter/forelder/[token]").status.implementert, "precision-visning");
  assert.match(byRoute.get("/inviter/forelder/[token]").kontrollbevis, /AU05Invitasjon/);
  assert.equal(byRoute.get("/offline").status.implementert, "precision-visning");
  assert.match(byRoute.get("/offline").kontrollbevis, /SY01Offline/);
  assert.equal(byRoute.get("/vedlikehold").status.implementert, "precision-visning");
  assert.match(byRoute.get("/vedlikehold").kontrollbevis, /SY01Vedlikehold/);
  assert.equal(register.tellinger.implementert, 34);
  assert.equal(register.tellinger.valgtForBygging > 0, true);
  assert.equal(register.sider.some((row) => row.status.kontrollertIApp), false);
});
