/**
 * scripts/seed-baner.ts
 *
 * Seeder 30+ norske golfbaner med realistiske slope/CR/par-data.
 * Idempotent via upsert på slug.
 *
 * Kjøres med: npx tsx scripts/seed-baner.ts
 */

import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });

import { PrismaClient } from "../src/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const adapter = new PrismaPg({
  connectionString: process.env.DATABASE_URL!,
});
const prisma = new PrismaClient({ adapter });

interface BaneSeed {
  slug: string;
  navn: string;
  kortNavn?: string;
  klubb: string;
  region: string;
  kommune: string;
  fylke: string;
  antallHull: number;
  oppstartsaar: number;
  lengdeMeter: number;
  slope: number;
  courseRating: number;
  par: number;
  bio: string;
}

const NORSKE_BANER: BaneSeed[] = [
  // ── Øst (10) ──────────────────────────────────────────────────────────────
  {
    slug: "oslo-gk",
    navn: "Oslo Golfklubb",
    kortNavn: "Oslo GK",
    klubb: "Oslo Golfklubb",
    region: "Øst",
    kommune: "Oslo",
    fylke: "Oslo",
    antallHull: 18,
    oppstartsaar: 1924,
    lengdeMeter: 6112,
    slope: 128,
    courseRating: 71.0,
    par: 72,
    bio: "Oslo Golfklubb er Norges eldste golfklubb, grunnlagt i 1924. Banen ligger idyllisk til ved Bogstad og er kjent for sine krevende par 4-er og vakre omgivelser.",
  },
  {
    slug: "baerum-gk",
    navn: "Bærum Golfklubb",
    kortNavn: "Bærum GK",
    klubb: "Bærum Golfklubb",
    region: "Øst",
    kommune: "Bærum",
    fylke: "Viken",
    antallHull: 18,
    oppstartsaar: 1985,
    lengdeMeter: 6234,
    slope: 132,
    courseRating: 71.5,
    par: 72,
    bio: "Bærum Golfklubb er en av Norges mest populære turneringsbaner med utfordrende design og godt stell. Banen har vært vertskap for en rekke nasjonale mesterskap.",
  },
  {
    slug: "gfgk",
    navn: "Gamle Fredrikstad Golfklubb",
    kortNavn: "GFGK",
    klubb: "Gamle Fredrikstad Golfklubb",
    region: "Øst",
    kommune: "Fredrikstad",
    fylke: "Østfold",
    antallHull: 18,
    oppstartsaar: 1991,
    lengdeMeter: 5876,
    slope: 124,
    courseRating: 70.2,
    par: 72,
    bio: "Gamle Fredrikstad GK holder til i vakre landlige omgivelser utenfor Fredrikstad sentrum. Banen er kjent for sine varierte hull og velpleide greener.",
  },
  {
    slug: "drobak-gk",
    navn: "Drøbak Golfklubb",
    kortNavn: "Drøbak GK",
    klubb: "Drøbak Golfklubb",
    region: "Øst",
    kommune: "Frogn",
    fylke: "Viken",
    antallHull: 18,
    oppstartsaar: 1994,
    lengdeMeter: 5750,
    slope: 120,
    courseRating: 69.5,
    par: 72,
    bio: "Drøbak GK er kjent for sin naturskjønne beliggenhet nær Oslofjorden. Banen passer både nybegynnere og erfarne spillere.",
  },
  {
    slug: "asker-gk",
    navn: "Asker Golfklubb",
    kortNavn: "Asker GK",
    klubb: "Asker Golfklubb",
    region: "Øst",
    kommune: "Asker",
    fylke: "Viken",
    antallHull: 18,
    oppstartsaar: 1988,
    lengdeMeter: 5980,
    slope: 126,
    courseRating: 70.4,
    par: 72,
    bio: "Asker GK tilbyr en variert og teknisk krevende bane i Asker kommunes vakre natur. Godt tilrettelagt for alle nivåer.",
  },
  {
    slug: "bogstad-gk",
    navn: "Bogstad Golfklubb",
    kortNavn: "Bogstad GK",
    klubb: "Bogstad Golfklubb",
    region: "Øst",
    kommune: "Oslo",
    fylke: "Oslo",
    antallHull: 18,
    oppstartsaar: 1972,
    lengdeMeter: 6050,
    slope: 129,
    courseRating: 71.2,
    par: 72,
    bio: "Bogstad GK er en av Oslos eldste etablerte golfklubber med en bane i klassisk parkland-stil. Tett på Bogstad gård og Sognsvann.",
  },
  {
    slug: "holmsbu-gk",
    navn: "Holmsbu Golfklubb",
    kortNavn: "Holmsbu GK",
    klubb: "Holmsbu Golfklubb",
    region: "Øst",
    kommune: "Hurum",
    fylke: "Viken",
    antallHull: 18,
    oppstartsaar: 1996,
    lengdeMeter: 5680,
    slope: 122,
    courseRating: 69.8,
    par: 72,
    bio: "Holmsbu GK ligger vakkert til ved Drammensfjorden og kombinerer krevende hull med flotte naturopplevelser.",
  },
  {
    slug: "tyrifjord-gk",
    navn: "Tyrifjord Golfklubb",
    kortNavn: "Tyrifjord GK",
    klubb: "Tyrifjord Golfklubb",
    region: "Øst",
    kommune: "Ringerike",
    fylke: "Viken",
    antallHull: 18,
    oppstartsaar: 2001,
    lengdeMeter: 5820,
    slope: 123,
    courseRating: 70.0,
    par: 72,
    bio: "Tyrifjord GK er en moderne bane med utsikt over Tyrifjorden. Kombinerer tekniske og åpne hull i et variert design.",
  },
  {
    slug: "onsoy-gk",
    navn: "Onsøy Golfklubb",
    kortNavn: "Onsøy GK",
    klubb: "Onsøy Golfklubb",
    region: "Øst",
    kommune: "Fredrikstad",
    fylke: "Østfold",
    antallHull: 18,
    oppstartsaar: 1992,
    lengdeMeter: 5760,
    slope: 121,
    courseRating: 69.7,
    par: 72,
    bio: "Onsøy GK tilbyr en hyggelig og variert bane i skjønn natur på Onsøyhalvøya. Populær familieklubb med godt miljø.",
  },
  {
    slug: "borre-gk",
    navn: "Borre Golfklubb",
    kortNavn: "Borre GK",
    klubb: "Borre Golfklubb",
    region: "Øst",
    kommune: "Horten",
    fylke: "Vestfold",
    antallHull: 18,
    oppstartsaar: 1989,
    lengdeMeter: 5920,
    slope: 125,
    courseRating: 70.3,
    par: 72,
    bio: "Borre GK ligger ved Oslofjorden med fantastisk utsikt. Banen er kjent for sin blanding av åpne og skogkledte hull.",
  },

  // ── Vest (8) ──────────────────────────────────────────────────────────────
  {
    slug: "bergen-gk",
    navn: "Bergen Golfklubb",
    kortNavn: "Bergen GK",
    klubb: "Bergen Golfklubb",
    region: "Vest",
    kommune: "Bergen",
    fylke: "Hordaland",
    antallHull: 18,
    oppstartsaar: 1937,
    lengdeMeter: 5821,
    slope: 125,
    courseRating: 70.1,
    par: 71,
    bio: "Bergen GK er en av Vestlandets mest tradisjonsrike golfklubber. Banen er omgitt av Bergens vakre natur og passer alle nivåer.",
  },
  {
    slug: "stavanger-gk",
    navn: "Stavanger Golfklubb",
    kortNavn: "Stavanger GK",
    klubb: "Stavanger Golfklubb",
    region: "Vest",
    kommune: "Stavanger",
    fylke: "Rogaland",
    antallHull: 18,
    oppstartsaar: 1956,
    lengdeMeter: 6034,
    slope: 130,
    courseRating: 70.8,
    par: 72,
    bio: "Stavanger GK er Rogalands fremste golfklubb med en krevende og godt vedlikeholdt bane. Vertskap for en rekke regionale mesterskap.",
  },
  {
    slug: "sola-gk",
    navn: "Sola Golfklubb",
    kortNavn: "Sola GK",
    klubb: "Sola Golfklubb",
    region: "Vest",
    kommune: "Sola",
    fylke: "Rogaland",
    antallHull: 18,
    oppstartsaar: 1969,
    lengdeMeter: 6180,
    slope: 133,
    courseRating: 71.8,
    par: 72,
    bio: "Sola GK er kjent for sin linkspregede bane nær flyplassen. Vinden gjør banen ekstra krevende og er en favoritt blant erfarne spillere.",
  },
  {
    slug: "fana-gk",
    navn: "Fana Golfklubb",
    kortNavn: "Fana GK",
    klubb: "Fana Golfklubb",
    region: "Vest",
    kommune: "Bergen",
    fylke: "Hordaland",
    antallHull: 18,
    oppstartsaar: 1993,
    lengdeMeter: 5790,
    slope: 123,
    courseRating: 70.0,
    par: 72,
    bio: "Fana GK ligger sør for Bergen sentrum med kuppert terreng og fine naturomgivelser. Banen er populær blant Bergens golfere.",
  },
  {
    slug: "meland-gk",
    navn: "Meland Golfklubb",
    kortNavn: "Meland GK",
    klubb: "Meland Golfklubb",
    region: "Vest",
    kommune: "Alver",
    fylke: "Vestland",
    antallHull: 18,
    oppstartsaar: 1997,
    lengdeMeter: 5840,
    slope: 124,
    courseRating: 70.2,
    par: 72,
    bio: "Meland GK tilbyr en flott naturopplevelse nord for Bergen. Banen kjennetegnes av variert terrengtilpasning og godt vedlikehold.",
  },
  {
    slug: "haga-gk",
    navn: "Haga Golfklubb",
    kortNavn: "Haga GK",
    klubb: "Haga Golfklubb",
    region: "Vest",
    kommune: "Askøy",
    fylke: "Vestland",
    antallHull: 18,
    oppstartsaar: 2003,
    lengdeMeter: 5640,
    slope: 119,
    courseRating: 69.3,
    par: 72,
    bio: "Haga GK på Askøy er en familievennlig bane med fantastisk utsikt over fjordlandskapet. Passer perfekt for alle ferdighetsnivåer.",
  },
  {
    slug: "algard-gk",
    navn: "Ålgård Golfklubb",
    kortNavn: "Ålgård GK",
    klubb: "Ålgård Golfklubb",
    region: "Vest",
    kommune: "Gjesdal",
    fylke: "Rogaland",
    antallHull: 18,
    oppstartsaar: 1990,
    lengdeMeter: 5960,
    slope: 127,
    courseRating: 70.6,
    par: 72,
    bio: "Ålgård GK er en velkjent bane i Rogaland som kombinerer naturskjønne omgivelser med tekniske utfordringer. Populær turneringsbane.",
  },
  {
    slug: "time-gk",
    navn: "Time Golfklubb",
    kortNavn: "Time GK",
    klubb: "Time Golfklubb",
    region: "Vest",
    kommune: "Time",
    fylke: "Rogaland",
    antallHull: 18,
    oppstartsaar: 1998,
    lengdeMeter: 5720,
    slope: 121,
    courseRating: 69.7,
    par: 72,
    bio: "Time GK ligger idyllisk til i Jærens flate landskap med åpne fairways og god plass. Vindeksponert bane som setter krav til spillsans.",
  },

  // ── Midt (5) ──────────────────────────────────────────────────────────────
  {
    slug: "trondheim-gk",
    navn: "Trondheim Golfklubb",
    kortNavn: "Trondheim GK",
    klubb: "Trondheim Golfklubb",
    region: "Midt",
    kommune: "Trondheim",
    fylke: "Trøndelag",
    antallHull: 18,
    oppstartsaar: 1950,
    lengdeMeter: 5984,
    slope: 127,
    courseRating: 70.5,
    par: 72,
    bio: "Trondheim GK er Midt-Norges mest historiske golfklubb, grunnlagt midt på 1900-tallet. Banen har klassisk parkland-stil med fine greener.",
  },
  {
    slug: "byneset-gk",
    navn: "Byneset Golfklubb",
    kortNavn: "Byneset GK",
    klubb: "Byneset Golfklubb",
    region: "Midt",
    kommune: "Trondheim",
    fylke: "Trøndelag",
    antallHull: 18,
    oppstartsaar: 1987,
    lengdeMeter: 5810,
    slope: 124,
    courseRating: 70.1,
    par: 72,
    bio: "Byneset GK er kjent for sin naturskjønne beliggenhet ved Trondheimsfjorden. Flott utsikt og varierte hull gjør dette til en favoritt.",
  },
  {
    slug: "stiklestad-gk",
    navn: "Stiklestad Golfklubb",
    kortNavn: "Stiklestad GK",
    klubb: "Stiklestad Golfklubb",
    region: "Midt",
    kommune: "Verdal",
    fylke: "Trøndelag",
    antallHull: 18,
    oppstartsaar: 1994,
    lengdeMeter: 5870,
    slope: 125,
    courseRating: 70.3,
    par: 72,
    bio: "Stiklestad GK ligger tett på det historiske Stiklestad og byr på flott golfopplevelse i trøndersk landskap med åpne fairways.",
  },
  {
    slug: "alesund-gk",
    navn: "Ålesund Golfklubb",
    kortNavn: "Ålesund GK",
    klubb: "Ålesund Golfklubb",
    region: "Midt",
    kommune: "Ålesund",
    fylke: "Møre og Romsdal",
    antallHull: 18,
    oppstartsaar: 1991,
    lengdeMeter: 5660,
    slope: 120,
    courseRating: 69.4,
    par: 72,
    bio: "Ålesund GK byr på spektakulær utsikt over øyriket rundt Ålesund. Banen er kuppert og teknisk krevende med vakker natur som bakteppe.",
  },
  {
    slug: "volda-gk",
    navn: "Volda Golfklubb",
    kortNavn: "Volda GK",
    klubb: "Volda Golfklubb",
    region: "Midt",
    kommune: "Volda",
    fylke: "Møre og Romsdal",
    antallHull: 18,
    oppstartsaar: 2005,
    lengdeMeter: 5540,
    slope: 117,
    courseRating: 69.0,
    par: 72,
    bio: "Volda GK er en av Sunnmøres nyere golfklubber og har raskt blitt populær for sin flotte plassering ved fjorden med fjellbakgrunn.",
  },

  // ── Nord (3) ──────────────────────────────────────────────────────────────
  {
    slug: "lofoten-gk",
    navn: "Lofoten Golfklubb",
    kortNavn: "Lofoten GK",
    klubb: "Lofoten Golfklubb",
    region: "Nord",
    kommune: "Vågan",
    fylke: "Nordland",
    antallHull: 18,
    oppstartsaar: 1997,
    lengdeMeter: 5340,
    slope: 115,
    courseRating: 68.4,
    par: 72,
    bio: "Lofoten GK er kjent som en av verdens vakreste golfbaner, omgitt av dramatiske fjell og fjorder. En bucket-list-bane for golfere fra hele verden.",
  },
  {
    slug: "tromso-gk",
    navn: "Tromsø Golfklubb",
    kortNavn: "Tromsø GK",
    klubb: "Tromsø Golfklubb",
    region: "Nord",
    kommune: "Tromsø",
    fylke: "Troms",
    antallHull: 18,
    oppstartsaar: 1986,
    lengdeMeter: 5450,
    slope: 116,
    courseRating: 68.7,
    par: 72,
    bio: "Tromsø GK er en av Norges nordligste golfklubber og tilbyr midnattsolfgolf om sommeren. Unikt golfopplevelse nord for polarsirkelen.",
  },
  {
    slug: "salten-gk",
    navn: "Salten Golfklubb",
    kortNavn: "Salten GK",
    klubb: "Salten Golfklubb",
    region: "Nord",
    kommune: "Bodø",
    fylke: "Nordland",
    antallHull: 18,
    oppstartsaar: 1993,
    lengdeMeter: 5560,
    slope: 118,
    courseRating: 69.1,
    par: 72,
    bio: "Salten GK i Bodø-regionen tilbyr en vakker bane med utsikt over Saltfjorden. Populær turist-destinasjon og lokalt knutepunkt for golf.",
  },

  // ── Sør (4) ──────────────────────────────────────────────────────────────
  {
    slug: "mandal-gk",
    navn: "Mandal Golfklubb",
    kortNavn: "Mandal GK",
    klubb: "Mandal Golfklubb",
    region: "Sør",
    kommune: "Lindesnes",
    fylke: "Agder",
    antallHull: 18,
    oppstartsaar: 1988,
    lengdeMeter: 5700,
    slope: 122,
    courseRating: 69.8,
    par: 72,
    bio: "Mandal GK er Norges sørligste betydningsfulle golfklubb, kjent for sitt milde klima og lange sesong. Vakker kystbane med varierte hull.",
  },
  {
    slug: "kristiansand-gk",
    navn: "Kristiansand Golfklubb",
    kortNavn: "Kristiansand GK",
    klubb: "Kristiansand Golfklubb",
    region: "Sør",
    kommune: "Kristiansand",
    fylke: "Agder",
    antallHull: 18,
    oppstartsaar: 1963,
    lengdeMeter: 5890,
    slope: 126,
    courseRating: 70.4,
    par: 72,
    bio: "Kristiansand GK er regionens fremste golfklubb med en veletablert bane og sterk turneringstradisjon. Sentral for sørlandsgolf.",
  },
  {
    slug: "sogne-gk",
    navn: "Søgne Golfklubb",
    kortNavn: "Søgne GK",
    klubb: "Søgne Golfklubb",
    region: "Sør",
    kommune: "Kristiansand",
    fylke: "Agder",
    antallHull: 18,
    oppstartsaar: 2000,
    lengdeMeter: 5610,
    slope: 119,
    courseRating: 69.3,
    par: 71,
    bio: "Søgne GK er en moderne bane med pittoreske omgivelser sør for Kristiansand. Populær for dagsturer og familiespill.",
  },
  {
    slug: "grimstad-gk",
    navn: "Grimstad Golfklubb",
    kortNavn: "Grimstad GK",
    klubb: "Grimstad Golfklubb",
    region: "Sør",
    kommune: "Grimstad",
    fylke: "Agder",
    antallHull: 18,
    oppstartsaar: 1992,
    lengdeMeter: 5740,
    slope: 122,
    courseRating: 69.9,
    par: 72,
    bio: "Grimstad GK holder til i Ibsen-byen og byr på en hyggelig og teknisk bane i kystlandskapet. Aktiv klubb med godt juniorprogram.",
  },
];

async function main() {
  console.log(`Seeder ${NORSKE_BANER.length} norske golfbaner...`);

  for (const bane of NORSKE_BANER) {
    await prisma.bane.upsert({
      where: { slug: bane.slug },
      update: {
        navn: bane.navn,
        kortNavn: bane.kortNavn,
        klubb: bane.klubb,
        region: bane.region,
        kommune: bane.kommune,
        fylke: bane.fylke,
        antallHull: bane.antallHull,
        oppstartsaar: bane.oppstartsaar,
        lengdeMeter: bane.lengdeMeter,
        slope: bane.slope,
        courseRating: bane.courseRating,
        par: bane.par,
        bio: bane.bio,
      },
      create: {
        slug: bane.slug,
        navn: bane.navn,
        kortNavn: bane.kortNavn,
        klubb: bane.klubb,
        region: bane.region,
        kommune: bane.kommune,
        fylke: bane.fylke,
        antallHull: bane.antallHull,
        oppstartsaar: bane.oppstartsaar,
        lengdeMeter: bane.lengdeMeter,
        slope: bane.slope,
        courseRating: bane.courseRating,
        par: bane.par,
        bio: bane.bio,
      },
    });
    console.log(`  upserted: ${bane.navn}`);
  }

  console.log(`\nFerdig. ${NORSKE_BANER.length} baner i databasen.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
