/* Tegnede skjermtyper. Oppdateres hver runde. Brukes av oversikt.html og skjermkatalogene. Stier relative til prosjektroten. */
window.AK_KATALOG = {
  "PH-01": { name: "I dag", href: "ui_kits/playerhq/index.html#PH-01", runde: 20 },
  "PH-02": { name: "Gjør nå · utgår 28.09 → PH-01", href: "ui_kits/playerhq/index.html#PH-01", runde: 20, utgar: true },
  "PH-03": { name: "Øktark", href: "ui_kits/playerhq/index.html#PH-03", runde: 2 },
  "PH-04": { name: "Live-økt: før start", href: "ui_kits/playerhq/index.html#PH-04", runde: 24, night: true },
  "PH-05": { name: "Live-økt: aktiv", href: "ui_kits/playerhq/index.html#PH-05", runde: 24, night: true, uavklart: ["Bildet for tellerne i live-økt sender Anders senere"] },
  "PH-06": { name: "Live-økt: fysisk", href: "ui_kits/playerhq/index.html#PH-06", runde: 24, night: true },
  "PH-07": { name: "Etter økt", href: "ui_kits/playerhq/index.html#PH-07", runde: 24, night: true },
  "PH-08": { name: "Runde live", href: "ui_kits/playerhq/index.html#PH-08", runde: 2, night: true },
  "PH-09": { name: "Registrer runde", href: "ui_kits/playerhq/index.html#PH-09", runde: 2 },
  "PH-10": { name: "Plan", href: "ui_kits/playerhq/index.html#PH-10", runde: 21 },
  "PH-11": { name: "Workbench (spiller)", href: "ui_kits/playerhq/index.html#PH-11", runde: 29 },
  "PH-12": { name: "Velg treningsplan", href: "ui_kits/playerhq/index.html#PH-12", runde: 19, krav: ["Omdøpt 28.09: fem standardplaner tilpasset kategori A–K, ingen AI-planbygger for spilleren ved lansering. Tegningen er fortsatt den gamle Planbyggeren og tegnes om i runde 20–30"] },
  "PH-13": { name: "Øvelsesbank (break-tabell under putting)", href: "ui_kits/playerhq/index.html#PH-13", runde: 28 },
  "PH-14": { name: "Stats › Tester", href: "ui_kits/playerhq/index.html#PH-14", runde: 22 },
  "PH-15": { name: "Test: gjennomfør", href: "ui_kits/playerhq/index.html#PH-15", runde: 3, night: true },
  "PH-16": { name: "Stats", href: "ui_kits/playerhq/index.html#PH-16", runde: 22 },
  "PH-17": { name: "Stats › Trening · TrackMan", href: "ui_kits/playerhq/index.html#PH-17", runde: 22 },
  "PH-18": { name: "Stats › Snittscore · runder", href: "ui_kits/playerhq/index.html#PH-18", runde: 22, krav: ["Lanseringskrav: komplett etter-runden-gjennomgang — brutto score, hull for hull, slag/lie/avstand der spilleren har dem, SG OTT/APP/ARG/PUTT, putting, noter og manuell innlegging/import fra annen app. Kilde vises som Manuell / Annen app med dato. Kan lagres delvis"] },
  "PH-19": { name: "Målsetning → Workbench", href: "ui_kits/playerhq/index.html#PH-19", runde: 29 },
  "PH-20": { name: "Gameplan og banekart", href: "ui_kits/playerhq/index.html#PH-20", runde: 4, etter: ["Etter lansering: komplett baneguide (ekte hullkart, kartgrunnlag, full banedatabase). Ved lansering er PH-20 klar som mønster med eksempeldata, ikke blokkert"] },
  "PH-21": { name: "Innboks", href: "ui_kits/playerhq/index.html#PH-21", runde: 5 },
  "PH-22": { name: "Caddie-chat", href: "ui_kits/playerhq/index.html#PH-22", runde: 5 },
  "PH-23": { name: "Booking (spiller)", href: "ui_kits/playerhq/index.html#PH-23", runde: 5 },
  "PH-24": { name: "Meg", href: "ui_kits/playerhq/index.html#PH-24", runde: 23 },
  "PH-27": { name: "Deling", href: "ui_kits/playerhq/index.html#PH-27", runde: 31 },
  "PH-27-U16": { name: "Deling · under 16 år", href: "ui_kits/playerhq/index.html#PH-27-U16", runde: 31 },
  "PH-25": { name: "Abonnement og innstillinger", href: "ui_kits/playerhq/index.html#PH-25", runde: 23 , krav: ["Lanseringskrav (kodekontroll 27.09.2026): låst-tilstand for TALENT. requirePortalUser sender TALENT fra FULL-flater til /portal/oppgrader?fra=laast; flyten må vise hvilken flate som er låst og hva som er åpent i TALENT (talent-allowlist.ts)"] },
  "PH-26": { name: "Utenfor banen", href: "ui_kits/playerhq/index.html#PH-26", runde: 5, utgar: "28.09" },
  "PH-WB-FYS": { name: "Fysisk · lag i Plan", href: "ui_kits/playerhq/index.html#PH-WB-FYS", runde: 21, lag: "PH-10" },
  "PH-WB-TURN": { name: "Turneringer · lag i Plan", href: "ui_kits/playerhq/index.html#PH-WB-TURN", runde: 21, lag: "PH-10" },
  "PH-RD-01": { name: "Registrer runde · velg nivå", href: "ui_kits/playerhq/index.html#PH-RD-01", runde: 23 },
  "PH-RD-02": { name: "Registrer runde · oppsett", href: "ui_kits/playerhq/index.html#PH-RD-02", runde: 23 },
  "PH-RD-03": { name: "Live runde · slag", href: "ui_kits/playerhq/index.html#PH-RD-03", runde: 24, night: true },
  "PH-RD-04": { name: "Live runde · putt", href: "ui_kits/playerhq/index.html#PH-RD-04", runde: 24, night: true },
  "PH-RD-05": { name: "SG hittil", href: "ui_kits/playerhq/index.html#PH-RD-05", runde: 23, night: true },
  "PH-RD-06": { name: "Etterregistrering · rask score", href: "ui_kits/playerhq/index.html#PH-RD-06", runde: 23 },
  "PH-RD-07": { name: "Import fra annen app", href: "ui_kits/playerhq/index.html#PH-RD-07", runde: 23 },
  "PH-RD-08": { name: "Runde ferdig", href: "ui_kits/playerhq/index.html#PH-RD-08", runde: 24 },
  "PH-RD-09": { name: "Rediger runde", href: "ui_kits/playerhq/index.html#PH-RD-09", runde: 23 },
  "PH-TP-01": { name: "Teknisk plan (spiller)", href: "ui_kits/playerhq/index.html#PH-TP-01", runde: 24 },
  "PH-A01": { name: "Treningsanalyse · oversikt · utgår 28.09 → Stats › Trening", href: "ui_kits/playerhq/index.html#PH-A01", runde: 22, utgar: true },
  "PH-A02": { name: "Treningsbelastning · utgår 28.09 → Stats › Trening", href: "ui_kits/playerhq/index.html#PH-A02", runde: 22, utgar: true },
  "PH-A03": { name: "Øktkvalitet · utgår 28.09 → Stats › Trening", href: "ui_kits/playerhq/index.html#PH-A03", runde: 22, utgar: true },
  "PH-A04": { name: "Slagdata · utgår 28.09 → Stats › Trening", href: "ui_kits/playerhq/index.html#PH-A04", runde: 22, utgar: true },
  "PH-A05": { name: "Nærspill og putting · utgår 28.09 → Stats › Strokes Gained", href: "ui_kits/playerhq/index.html#PH-A05", runde: 22, utgar: true },
  "PH-A06": { name: "Rundeanalyse · utgår 28.09 → Stats › Snittscore", href: "ui_kits/playerhq/index.html#PH-A06", runde: 22, utgar: true },
  "PH-A07": { name: "Tester · utvikling · utgår 28.09 → Stats › Tester", href: "ui_kits/playerhq/index.html#PH-A07", runde: 22, utgar: true },
  "PH-A08": { name: "Datagrunnlag · utgår 28.09 → Stats › nok data i hver del", href: "ui_kits/playerhq/index.html#PH-A08", runde: 22, utgar: true },
  "AG-01": { name: "Cockpit", href: "ui_kits/agencyos/katalog.html#AG-01", runde: 25 },
  "AG-02": { name: "Kø · utgår 28.09 → Innboks", href: "ui_kits/agencyos/katalog.html#AG-02", runde: 26, utgar: true },
  "AG-03": { name: "Oppfølgingskø · utgår 28.09 → Innboks", href: "ui_kits/agencyos/katalog.html#AG-03", runde: 26, utgar: true },
  "AG-04": { name: "Innboks", href: "ui_kits/agencyos/katalog.html#AG-04", runde: 28 },
  "AG-05": { name: "Kalender", href: "ui_kits/agencyos/katalog.html#AG-05", runde: 28 },
  "AG-06": { name: "Booking", href: "ui_kits/agencyos/katalog.html#AG-06", runde: 30, demo: ["Timeprisen 950 kr er demodata, ikke ekte pris. Skal ikke porteres"] },
  "AG-07": { name: "Stall", href: "ui_kits/agencyos/katalog.html#AG-07", runde: 27 },
  "AG-08": { name: "Spiller 360", href: "ui_kits/agencyos/katalog.html#AG-08", runde: 27 },
  "AG-05-UKE": { name: "Kalender · uke", href: "ui_kits/agencyos/katalog.html#AG-05-UKE", runde: 28 },
  "AG-05-MND": { name: "Kalender · måned", href: "ui_kits/agencyos/katalog.html#AG-05-MND", runde: 28 },
  "AG-05-AR": { name: "Kalender · år", href: "ui_kits/agencyos/katalog.html#AG-05-AR", runde: 28 },
  "AG-05-ASS": { name: "Kalender · assistant coach", href: "ui_kits/agencyos/katalog.html#AG-05-ASS", runde: 28 },
  "AG-04-HASTER": { name: "Innboks · sak som haster (bjella rust)", href: "ui_kits/agencyos/katalog.html#AG-04-HASTER", runde: 28 },
  "PH-15-TN": { name: "Test: Team Norway (poeng og treff)", href: "ui_kits/playerhq/index.html#PH-15-TN", runde: 28, night: true },
  "AG-20-ASS": { name: "Økonomi · assistant coach (ingen tilgang)", href: "ui_kits/agencyos/katalog.html#AG-20-ASS", runde: 32 },
  "AG-06-NY": { name: "Booking · ny booking", href: "ui_kits/agencyos/katalog.html#AG-06-NY", runde: 30 },
  "AG-23-TEAM": { name: "Oppsett · team og roller", href: "ui_kits/agencyos/katalog.html#AG-23-TEAM", runde: 30 },
  "AG-11-GRUPPE": { name: "Workbench · gruppe", href: "ui_kits/agencyos/katalog.html#AG-11-GRUPPE", runde: 29, uavklart: ["B4 «Planforslag for gruppa» er tegnet, men skjult ved lansering"] },
  "AG-11-AR": { name: "Workbench · årsplan (tekstbånd, perioder)", href: "ui_kits/agencyos/katalog.html#AG-11-AR", runde: 33 },
  "AG-11-NY": { name: "Workbench · opprett årsplan (veileder, 3 steg)", href: "ui_kits/agencyos/katalog.html#AG-11-NY", runde: 33 },
  "AG-11-GRUPPE-AR": { name: "Workbench · gruppas årsplan (rulles ut)", href: "ui_kits/agencyos/katalog.html#AG-11-GRUPPE-AR", runde: 33 },
  "AG-11-PER": { name: "Workbench · periode", href: "ui_kits/agencyos/katalog.html#AG-11-PER", runde: 33 },
  "AG-11-PERSKJEMA": { name: "Workbench · periodeskjema (coach)", href: "ui_kits/agencyos/katalog.html#AG-11-PERSKJEMA", runde: 33 },
  "AG-11-MND": { name: "Workbench · måned", href: "ui_kits/agencyos/katalog.html#AG-11-MND", runde: 33 },
  "AG-11-MNDSKJEMA": { name: "Workbench · månedsskjema (coach)", href: "ui_kits/agencyos/katalog.html#AG-11-MNDSKJEMA", runde: 33 },
  "AG-11-OKT": { name: "Workbench · økt og øvelsesbank", href: "ui_kits/agencyos/katalog.html#AG-11-OKT", runde: 29 },
  "AG-11-MAL": { name: "Workbench · målsetninger", href: "ui_kits/agencyos/katalog.html#AG-11-MAL", runde: 29 },
  "AG-11-FYS": { name: "Workbench · fysisk program", href: "ui_kits/agencyos/katalog.html#AG-11-FYS", runde: 29 },
  "PH-11-MAL": { name: "Workbench · målsetninger (spiller)", href: "ui_kits/playerhq/index.html#PH-11-MAL", runde: 29 },
  "PH-11-AR": { name: "Workbench · årsplan (spiller)", href: "ui_kits/playerhq/index.html#PH-11-AR", runde: 33 },
  "PH-11-NY": { name: "Workbench · opprett årsplan (spiller)", href: "ui_kits/playerhq/index.html#PH-11-NY", runde: 33 },
  "PH-11-PER": { name: "Workbench · periode (spiller)", href: "ui_kits/playerhq/index.html#PH-11-PER", runde: 33 },
  "PH-11-PERSKJEMA": { name: "Workbench · periodeskjema (spiller)", href: "ui_kits/playerhq/index.html#PH-11-PERSKJEMA", runde: 33 },
  "PH-11-MND": { name: "Workbench · måned (spiller)", href: "ui_kits/playerhq/index.html#PH-11-MND", runde: 33 },
  "PH-11-MNDSKJEMA": { name: "Workbench · månedsskjema (spiller)", href: "ui_kits/playerhq/index.html#PH-11-MNDSKJEMA", runde: 33 },
  "AG-08-PLAN": { name: "Spiller 360 › Plan", href: "ui_kits/agencyos/katalog.html#AG-08-PLAN", runde: 27 },
  "AG-08-TALENT": { name: "Spiller 360 › Talent", href: "ui_kits/agencyos/katalog.html#AG-08-TALENT", runde: 27 },
  "PH-01-UNG": { name: "I dag · fireukerssjekk Ung", href: "ui_kits/playerhq/index.html#PH-01-UNG", runde: 27 },
  "AG-04-OPP": { name: "Innboks · Oppfølging", href: "ui_kits/agencyos/katalog.html#AG-04-OPP", runde: 26 },
  "PH-07-FYS": { name: "Etter økt · fysisk", href: "ui_kits/playerhq/index.html#PH-07-FYS", runde: 26 },
  "AG-08-IUP-AK": { name: "Spiller 360 › IUP · AK-spiller", href: "ui_kits/agencyos/katalog.html#AG-08-IUP-AK", runde: 25 },
  "AG-13-U": { name: "Live coachingøkt · uten samtykke", href: "ui_kits/agencyos/katalog.html#AG-13-U", runde: 25 },
  "PH-01-AK": { name: "I dag · AK-spiller", href: "ui_kits/playerhq/index.html#PH-01-AK", runde: 25 },
  "AG-08-IUP": { name: "Spiller 360 › IUP", href: "ui_kits/agencyos/katalog.html#AG-08-IUP", runde: 31 },
  "AG-09": { name: "Spilleranalyse · utgår 28.09 → Spiller 360 › Stats", href: "ui_kits/agencyos/katalog.html#AG-09", runde: 27, utgar: true },
  "AG-10": { name: "Teknisk plan", href: "ui_kits/agencyos/katalog.html#AG-10", runde: 27 },
  "AG-TP-01": { name: "Oppgaveskjema", href: "ui_kits/agencyos/katalog.html#AG-TP-01", runde: 24 },
  "AG-TP-02": { name: "Før og nå per posisjon", href: "ui_kits/agencyos/katalog.html#AG-TP-02", runde: 24, krav: ["Krever tillegg i datamodellen: to daterte bilder per oppgave. I dag finnes ett bilde og én video."] },
  /* Runde 25 (27.09.2026): AG-15 testdetalj, PH-A07 utvidet, AG-11 kilde på øktkort, puttebånd 6 i AG-14 m.fl. */
  "AG-11": { name: "Workbench (coach)", href: "ui_kits/agencyos/katalog.html#AG-11", runde: 29 },
  "AG-12": { name: "Øktark etter live", href: "ui_kits/agencyos/katalog.html#AG-12", runde: 25 },
  "AG-13": { name: "Live coachingøkt", href: "ui_kits/agencyos/katalog.html#AG-13", runde: 25 },
  "AG-14": { name: "Plan-hub, maler og øvelser", href: "ui_kits/agencyos/katalog.html#AG-14", runde: 25 },
  "AG-15": { name: "Tester", href: "ui_kits/agencyos/katalog.html#AG-15", runde: 30 },
  "AG-16": { name: "Grupper", href: "ui_kits/agencyos/katalog.html#AG-16", runde: 30 },
  "AG-17": { name: "Turneringer · utgår 28.09 → Workbench og Plan", href: "ui_kits/agencyos/katalog.html#AG-17", runde: 30, utgar: true },
  "AG-18": { name: "TrackMan og video · utgår 28.09 → Spiller 360", href: "ui_kits/agencyos/katalog.html#AG-18", runde: 30, utgar: true },
  "AG-19": { name: "Jarvis-chat", href: "ui_kits/agencyos/katalog.html#AG-19", runde: 30 },
  "AG-20": { name: "Økonomi · bare head coach", href: "ui_kits/agencyos/katalog.html#AG-20", runde: 30, demo: ["WANG-kostnad 33 450 kr er et omtrentlig demotall", "Alle økonomitall er demodata i Tripletex-format, ikke ekte regnskap"] },
  "AG-21": { name: "Oppgaver · utgår 28.09 → Cockpit", href: "ui_kits/agencyos/katalog.html#AG-21", runde: 25, utgar: true },
  "AG-22": { name: "Innsikt og talent · utgår 28.09 → Spiller 360 › Talent", href: "ui_kits/agencyos/katalog.html#AG-22", runde: 27, utgar: true },
  "AG-23": { name: "Oppsett", href: "ui_kits/agencyos/katalog.html#AG-23", runde: 30 },
  "AG-24": { name: "Drift · utgår 28.09 → Oppsett", href: "ui_kits/agencyos/katalog.html#AG-24", runde: 30, utgar: true },
  "AG-WB-FYS": { name: "Workbench · fysisk plan", href: "ui_kits/agencyos/katalog.html#AG-WB-FYS", runde: 22 },
  "AG-WB-TURN": { name: "Workbench · turneringer", href: "ui_kits/agencyos/katalog.html#AG-WB-TURN", runde: 22 },
  "AG-RD-01": { name: "Rundeanalyse", href: "ui_kits/agencyos/katalog.html#AG-RD-01", runde: 23 },
  "AG-RD-02": { name: "Manglende SG-grunnlag", href: "ui_kits/agencyos/katalog.html#AG-RD-02", runde: 23 },
  "AG-A01": { name: "Innsikt · oversikt · utgår 28.09 → Spiller 360 og Grupper", href: "ui_kits/agencyos/katalog.html#AG-A01", runde: 28, utgar: true },
  "AG-A02": { name: "Spilleranalyse samlet", href: "ui_kits/agencyos/katalog.html#AG-A02", runde: 20 },
  "AG-A03": { name: "Gruppeanalyse", href: "ui_kits/agencyos/katalog.html#AG-A03", runde: 20 },
  "AG-A04": { name: "Plan mot faktisk", href: "ui_kits/agencyos/katalog.html#AG-A04", runde: 20 },
  "AG-A05": { name: "Datakvalitet", href: "ui_kits/agencyos/katalog.html#AG-A05", runde: 20 },
  "AG-A06": { name: "Tiltaksverksted", href: "ui_kits/agencyos/katalog.html#AG-A06", runde: 20 },
  "AG-A07": { name: "Rapportbygger · utgår 28.09", href: "ui_kits/agencyos/katalog.html#AG-A07", runde: 30, utgar: true },
  "AG-A08": { name: "Caddie-forslag", href: "ui_kits/agencyos/katalog.html#AG-A08", runde: 20 },
  "FO-01": { name: "Forelder i dag", href: "ui_kits/forelder/katalog.html#FO-01", runde: 10 },
  "FO-02": { name: "Barn", href: "ui_kits/forelder/katalog.html#FO-02", runde: 10 },
  "FO-03": { name: "Booking for barn", href: "ui_kits/forelder/katalog.html#FO-03", runde: 10 },
  "FO-04": { name: "Økonomi", href: "ui_kits/forelder/katalog.html#FO-04", runde: 10 },
  "FO-05": { name: "Samtykke og deling", href: "ui_kits/forelder/katalog.html#FO-05", runde: 31 },
  "FO-06": { name: "Coach og innstillinger", href: "ui_kits/forelder/katalog.html#FO-06", runde: 10 },
  "AU-01": { name: "Logg inn", href: "ui_kits/konto/katalog.html#AU-01", runde: 10 },
  "AU-02": { name: "Registrer", href: "ui_kits/konto/katalog.html#AU-02", runde: 10 },
  "AU-03": { name: "Passord", href: "ui_kits/konto/katalog.html#AU-03", runde: 10 },
  "AU-04": { name: "Oppstart", href: "ui_kits/konto/katalog.html#AU-04", runde: 23 },
  "AU-05": { name: "Samtykke via lenke", href: "ui_kits/konto/katalog.html#AU-05", runde: 10 },
  "AU-06": { name: "Innsyn (ekstern leser)", href: "ui_kits/konto/katalog.html#AU-06", runde: 10 },
  "BK-01": { name: "Velg tjeneste", href: "ui_kits/booking/katalog.html#BK-01", runde: 11 },
  "BK-02": { name: "Velg tid og betal", href: "ui_kits/booking/katalog.html#BK-02", runde: 11 },
  "BK-03": { name: "Kvittering", href: "ui_kits/booking/katalog.html#BK-03", runde: 11 },
  "GJ-01": { name: "GFGK Junior forside og grupper", href: "ui_kits/gfgk/katalog.html#GJ-01", runde: 11 },
  "GJ-02": { name: "GFGK veileder", href: "ui_kits/gfgk/katalog.html#GJ-02", runde: 11 },
  "SY-01": { name: "Systemtilstander", href: "ui_kits/system/katalog.html#SY-01", runde: 11 },
  "ST-01": { name: "Stats-hub og søk", href: "ui_kits/statistikk/katalog.html#ST-01", runde: 12 },
  "ST-02": { name: "Liste med filter", href: "ui_kits/statistikk/katalog.html#ST-02", runde: 12 },
  "ST-03": { name: "Profil/detalj", href: "ui_kits/statistikk/katalog.html#ST-03", runde: 12 },
  "ST-04": { name: "Turnering", href: "ui_kits/statistikk/katalog.html#ST-04", runde: 12 },
  "ST-05": { name: "PGA-kategori og utforskere", href: "ui_kits/statistikk/katalog.html#ST-05", runde: 12, demo: ["PGA-navnene er demonavn. I appen brukes ekte navn fra Data Golf"] },
  "ST-06": { name: "Verktøy og moro", href: "ui_kits/statistikk/katalog.html#ST-06", runde: 12 },
  "EP-01": { name: "Bekreftelse", href: "ui_kits/epost/katalog.html#EP-01", runde: 16 },
  "EP-02": { name: "Endret time", href: "ui_kits/epost/katalog.html#EP-02", runde: 16 },
  "EP-03": { name: "Påminnelse dagen før", href: "ui_kits/epost/katalog.html#EP-03", runde: 16 },
  "EP-04": { name: "Avbestilling", href: "ui_kits/epost/katalog.html#EP-04", runde: 16 },
  "EP-05": { name: "Takk etter coachingtime", href: "ui_kits/epost/katalog.html#EP-05", runde: 16 },
  "EP-06": { name: "Oppfølging senere", href: "ui_kits/epost/katalog.html#EP-06", runde: 16 },
};
/* Runde 19 (28.09.2026): ny IA — plassering og «Utgår 28.09» står i ui_kits/_shared/ia.js (AK_IA). PH-12, PH-16, PH-19, AG-01 omdøpt. PH-26 utgår. */
/* Eldre utkast som ikke er i katalogformat ennå (ikke godkjent, mangler tilstander). */
window.AK_UTKAST = {};
