-- RLS-policyer dumpet fra live DB eljkjqvggsmnbbszzbpj 2026-07-18
-- 99 public-policyer + 2 storage-policyer. RLS er ENABLED på ALLE public-tabeller
-- (kjør ALTER TABLE "<t>" ENABLE ROW LEVEL SECURITY for hver tabell i ny DB først —
--  genereres fra tabellisten; unntak: coach_fokus_pins/periode_fordelinger droppes).
-- NB: policyer refererer auth.uid() (Supabase built-in) og enum "UserRole".

-- ══ public ══

CREATE POLICY achievements_select ON public.achievements AS PERMISSIVE FOR SELECT TO public USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = achievements."userId") OR (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"])))))));
CREATE POLICY agent_runs_admin_select ON public.agent_runs AS PERMISSIVE FOR SELECT TO public USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND (users.role = 'ADMIN'::"UserRole")))));
CREATE POLICY api_keys_select ON public.api_keys AS PERMISSIVE FOR SELECT TO public USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = api_keys."userId") OR (users.role = 'ADMIN'::"UserRole"))))));
CREATE POLICY api_keys_write ON public.api_keys AS PERMISSIVE FOR ALL TO public USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = api_keys."userId") OR (users.role = 'ADMIN'::"UserRole"))))));
CREATE POLICY audit_logs_admin_select ON public.audit_logs AS PERMISSIVE FOR SELECT TO public USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND (users.role = 'ADMIN'::"UserRole")))));
CREATE POLICY bookings_insert_own ON public.bookings AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (("userId" IN ( SELECT users.id FROM users WHERE (users."authId" = (( SELECT auth.uid() AS uid))::text))));
CREATE POLICY bookings_select_own ON public.bookings AS PERMISSIVE FOR SELECT TO authenticated USING (("userId" IN ( SELECT users.id FROM users WHERE (users."authId" = (( SELECT auth.uid() AS uid))::text))));
CREATE POLICY bookings_update_own ON public.bookings AS PERMISSIVE FOR UPDATE TO authenticated USING (("userId" IN ( SELECT users.id FROM users WHERE (users."authId" = (( SELECT auth.uid() AS uid))::text)))) WITH CHECK (("userId" IN ( SELECT users.id FROM users WHERE (users."authId" = (( SELECT auth.uid() AS uid))::text))));
CREATE POLICY caddie_messages_insert ON public.caddie_messages AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND (users.id = caddie_messages."userId")))));
CREATE POLICY caddie_messages_select ON public.caddie_messages AS PERMISSIVE FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = caddie_messages."userId") OR (users.role = 'ADMIN'::"UserRole"))))));
CREATE POLICY coach_availability_select ON public.coach_availability AS PERMISSIVE FOR SELECT TO public USING ((auth.uid() IS NOT NULL));
CREATE POLICY coach_availability_write ON public.coach_availability AS PERMISSIVE FOR ALL TO public USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = coach_availability."coachId") OR (users.role = 'ADMIN'::"UserRole")))))) WITH CHECK ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = coach_availability."coachId") OR (users.role = 'ADMIN'::"UserRole"))))));
CREATE POLICY coaching_sessions_insert ON public.coaching_sessions AS PERMISSIVE FOR INSERT TO public WITH CHECK ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = coaching_sessions."userId") OR (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"])))))));
CREATE POLICY coaching_sessions_select ON public.coaching_sessions AS PERMISSIVE FOR SELECT TO public USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = coaching_sessions."userId") OR (users.id = coaching_sessions."coachId") OR (users.role = 'ADMIN'::"UserRole"))))));
CREATE POLICY coaching_sessions_update ON public.coaching_sessions AS PERMISSIVE FOR UPDATE TO public USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = coaching_sessions."userId") OR (users.id = coaching_sessions."coachId") OR (users.role = 'ADMIN'::"UserRole"))))));
CREATE POLICY course_definitions_admin_write ON public.course_definitions AS PERMISSIVE FOR ALL TO public USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND (users.role = 'ADMIN'::"UserRole")))));
CREATE POLICY course_definitions_select ON public.course_definitions AS PERMISSIVE FOR SELECT TO public USING ((auth.uid() IS NOT NULL));
CREATE POLICY documents_admin_write ON public.documents AS PERMISSIVE FOR ALL TO public USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND (users.role = 'ADMIN'::"UserRole")))));
CREATE POLICY documents_select ON public.documents AS PERMISSIVE FOR SELECT TO public USING ((("userId" IS NULL) OR (EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = documents."userId") OR (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"]))))))));
CREATE POLICY email_templates_admin ON public.email_templates AS PERMISSIVE FOR ALL TO public USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"]))))));
CREATE POLICY error_logs_admin_read ON public.error_logs AS PERMISSIVE FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND (users.role = 'ADMIN'::"UserRole")))));
CREATE POLICY exercise_definitions_admin_write ON public.exercise_definitions AS PERMISSIVE FOR ALL TO public USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND (users.role = 'ADMIN'::"UserRole")))));
CREATE POLICY exercise_definitions_select ON public.exercise_definitions AS PERMISSIVE FOR SELECT TO public USING ((auth.uid() IS NOT NULL));
CREATE POLICY facilities_select ON public.facilities AS PERMISSIVE FOR SELECT TO public USING ((auth.uid() IS NOT NULL));
CREATE POLICY facilities_write ON public.facilities AS PERMISSIVE FOR ALL TO public USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND (users.role = 'ADMIN'::"UserRole")))));
CREATE POLICY friendships_select ON public.friendships AS PERMISSIVE FOR SELECT TO public USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = friendships."userAId") OR (users.id = friendships."userBId") OR (users.role = 'ADMIN'::"UserRole"))))));
CREATE POLICY friendships_write ON public.friendships AS PERMISSIVE FOR ALL TO public USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = friendships."userAId") OR (users.role = 'ADMIN'::"UserRole"))))));
CREATE POLICY goals_select ON public.goals AS PERMISSIVE FOR SELECT TO public USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = goals."userId") OR (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"])))))));
CREATE POLICY goals_write ON public.goals AS PERMISSIVE FOR ALL TO public USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = goals."userId") OR (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"])))))));
CREATE POLICY group_members_select ON public.group_members AS PERMISSIVE FOR SELECT TO public USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = group_members."userId") OR (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"])))))));
CREATE POLICY group_members_write ON public.group_members AS PERMISSIVE FOR ALL TO public USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"]))))));
CREATE POLICY groups_select ON public.groups AS PERMISSIVE FOR SELECT TO public USING ((auth.uid() IS NOT NULL));
CREATE POLICY groups_write ON public.groups AS PERMISSIVE FOR ALL TO public USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"]))))));
CREATE POLICY health_entries_select ON public.health_entries AS PERMISSIVE FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = health_entries."userId") OR (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"])))))));
CREATE POLICY health_entries_write ON public.health_entries AS PERMISSIVE FOR ALL TO authenticated USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = health_entries."userId") OR (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"]))))))) WITH CHECK ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = health_entries."userId") OR (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"])))))));
CREATE POLICY leads_admin_select ON public.leads AS PERMISSIVE FOR SELECT TO public USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"]))))));
CREATE POLICY locations_select_public ON public.locations AS PERMISSIVE FOR SELECT TO anon, authenticated USING ((active = true));
CREATE POLICY notifications_select ON public.notifications AS PERMISSIVE FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = notifications."userId") OR (users.role = 'ADMIN'::"UserRole"))))));
CREATE POLICY notifications_update ON public.notifications AS PERMISSIVE FOR UPDATE TO authenticated USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = notifications."userId") OR (users.role = 'ADMIN'::"UserRole")))))) WITH CHECK ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = notifications."userId") OR (users.role = 'ADMIN'::"UserRole"))))));
CREATE POLICY notion_connections_select ON public.notion_connections AS PERMISSIVE FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = notion_connections."userId") OR (users.role = 'ADMIN'::"UserRole"))))));
CREATE POLICY notion_connections_write ON public.notion_connections AS PERMISSIVE FOR ALL TO authenticated USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = notion_connections."userId") OR (users.role = 'ADMIN'::"UserRole")))))) WITH CHECK ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = notion_connections."userId") OR (users.role = 'ADMIN'::"UserRole"))))));
CREATE POLICY notion_database_links_select ON public.notion_database_links AS PERMISSIVE FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1 FROM (notion_connections nc JOIN users ON ((users."authId" = (auth.uid())::text))) WHERE ((nc.id = notion_database_links."connectionId") AND ((users.id = nc."userId") OR (users.role = 'ADMIN'::"UserRole"))))));
CREATE POLICY notion_database_links_write ON public.notion_database_links AS PERMISSIVE FOR ALL TO authenticated USING ((EXISTS ( SELECT 1 FROM (notion_connections nc JOIN users ON ((users."authId" = (auth.uid())::text))) WHERE ((nc.id = notion_database_links."connectionId") AND ((users.id = nc."userId") OR (users.role = 'ADMIN'::"UserRole")))))) WITH CHECK ((EXISTS ( SELECT 1 FROM (notion_connections nc JOIN users ON ((users."authId" = (auth.uid())::text))) WHERE ((nc.id = notion_database_links."connectionId") AND ((users.id = nc."userId") OR (users.role = 'ADMIN'::"UserRole"))))));
CREATE POLICY oppgave_cache_select ON public.oppgave_cache AS PERMISSIVE FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1 FROM ((notion_database_links ndl JOIN notion_connections nc ON ((nc.id = ndl."connectionId"))) JOIN users ON ((users."authId" = (auth.uid())::text))) WHERE ((ndl.id = oppgave_cache."databaseLinkId") AND ((users.id = nc."userId") OR (users.role = 'ADMIN'::"UserRole"))))));
CREATE POLICY parent_invitations_select ON public.parent_invitations AS PERMISSIVE FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = parent_invitations."playerId") OR (users.id = parent_invitations."acceptedById") OR (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"])))))));
CREATE POLICY parent_invitations_write ON public.parent_invitations AS PERMISSIVE FOR ALL TO authenticated USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = parent_invitations."playerId") OR (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"]))))))) WITH CHECK ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = parent_invitations."playerId") OR (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"])))))));
CREATE POLICY parent_relations_delete ON public.parent_relations AS PERMISSIVE FOR DELETE TO public USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"]))))));
CREATE POLICY parent_relations_insert ON public.parent_relations AS PERMISSIVE FOR INSERT TO public WITH CHECK ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole", 'PARENT'::"UserRole"]))))));
CREATE POLICY parent_relations_select ON public.parent_relations AS PERMISSIVE FOR SELECT TO public USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = parent_relations."parentId") OR (users.id = parent_relations."childId") OR (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"])))))));
CREATE POLICY parent_relations_update ON public.parent_relations AS PERMISSIVE FOR UPDATE TO public USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"]))))));
CREATE POLICY payments_select ON public.payments AS PERMISSIVE FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = payments."userId") OR (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"])))))));
CREATE POLICY plan_actions_select ON public.plan_actions AS PERMISSIVE FOR SELECT TO public USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = plan_actions."userId") OR (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"])))))));
CREATE POLICY plan_actions_update ON public.plan_actions AS PERMISSIVE FOR UPDATE TO public USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = plan_actions."userId") OR (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"])))))));
CREATE POLICY plan_templates_select ON public.plan_templates AS PERMISSIVE FOR SELECT TO public USING ((auth.uid() IS NOT NULL));
CREATE POLICY plan_templates_write ON public.plan_templates AS PERMISSIVE FOR ALL TO public USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"]))))));
CREATE POLICY prosjekt_cache_select ON public.prosjekt_cache AS PERMISSIVE FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1 FROM (notion_connections nc JOIN users ON ((users."authId" = (auth.uid())::text))) WHERE ((nc.id = prosjekt_cache."connectionId") AND ((users.id = nc."userId") OR (users.role = 'ADMIN'::"UserRole"))))));
CREATE POLICY rounds_select ON public.rounds AS PERMISSIVE FOR SELECT TO public USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = rounds."userId") OR (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"])))))));
CREATE POLICY rounds_write ON public.rounds AS PERMISSIVE FOR ALL TO public USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = rounds."userId") OR (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"])))))));
CREATE POLICY season_plans_select ON public.season_plans AS PERMISSIVE FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = season_plans."userId") OR (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"])))))));
CREATE POLICY season_plans_write ON public.season_plans AS PERMISSIVE FOR ALL TO authenticated USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = season_plans."userId") OR (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"]))))))) WITH CHECK ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = season_plans."userId") OR (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"])))))));
CREATE POLICY service_types_admin_delete ON public.service_types AS PERMISSIVE FOR DELETE TO public USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND (users.role = 'ADMIN'::"UserRole")))));
CREATE POLICY service_types_admin_insert ON public.service_types AS PERMISSIVE FOR INSERT TO public WITH CHECK ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND (users.role = 'ADMIN'::"UserRole")))));
CREATE POLICY service_types_admin_update ON public.service_types AS PERMISSIVE FOR UPDATE TO public USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND (users.role = 'ADMIN'::"UserRole")))));
CREATE POLICY service_types_select_public ON public.service_types AS PERMISSIVE FOR SELECT TO anon, authenticated USING ((active = true));
CREATE POLICY session_drills_select ON public.session_drills AS PERMISSIVE FOR SELECT TO public USING ((EXISTS ( SELECT 1 FROM ((training_plan_sessions s JOIN training_plans p ON ((p.id = s."planId"))) JOIN users u ON ((u."authId" = (auth.uid())::text))) WHERE ((s.id = session_drills."sessionId") AND ((p."userId" = u.id) OR (u.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"])))))));
CREATE POLICY session_drills_write ON public.session_drills AS PERMISSIVE FOR ALL TO public USING ((EXISTS ( SELECT 1 FROM ((training_plan_sessions s JOIN training_plans p ON ((p.id = s."planId"))) JOIN users u ON ((u."authId" = (auth.uid())::text))) WHERE ((s.id = session_drills."sessionId") AND ((p."userId" = u.id) OR (u.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"]))))))) WITH CHECK ((EXISTS ( SELECT 1 FROM ((training_plan_sessions s JOIN training_plans p ON ((p.id = s."planId"))) JOIN users u ON ((u."authId" = (auth.uid())::text))) WHERE ((s.id = session_drills."sessionId") AND ((p."userId" = u.id) OR (u.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"])))))));
CREATE POLICY session_recordings_select ON public.session_recordings AS PERMISSIVE FOR SELECT TO public USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = session_recordings."uploadedById") OR (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"])))))));
CREATE POLICY session_recordings_write ON public.session_recordings AS PERMISSIVE FOR ALL TO public USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"]))))));
CREATE POLICY session_requests_select ON public.session_requests AS PERMISSIVE FOR SELECT TO public USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = session_requests."userId") OR (users.id = session_requests."coachId") OR (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"])))))));
CREATE POLICY session_requests_write ON public.session_requests AS PERMISSIVE FOR ALL TO public USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = session_requests."userId") OR (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"])))))));
CREATE POLICY signals_select ON public.signals AS PERMISSIVE FOR SELECT TO public USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = signals."userId") OR (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"])))))));
CREATE POLICY subscriptions_select ON public.subscriptions AS PERMISSIVE FOR SELECT TO public USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = subscriptions."userId") OR (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"])))))));
CREATE POLICY subscriptions_write ON public.subscriptions AS PERMISSIVE FOR ALL TO public USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.role = 'ADMIN'::"UserRole") OR ((users.id = subscriptions."userId") AND (users.role = ANY (ARRAY['PLAYER'::"UserRole", 'PARENT'::"UserRole", 'COACH'::"UserRole"]))))))));
CREATE POLICY technical_plans_select ON public.technical_plans AS PERMISSIVE FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = technical_plans."userId") OR (users.id = technical_plans."opprettetAvId") OR (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"])))))));
CREATE POLICY technical_plans_write ON public.technical_plans AS PERMISSIVE FOR ALL TO authenticated USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = technical_plans."userId") OR (users.id = technical_plans."opprettetAvId") OR (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"]))))))) WITH CHECK ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = technical_plans."userId") OR (users.id = technical_plans."opprettetAvId") OR (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"])))))));
CREATE POLICY test_definitions_admin_write ON public.test_definitions AS PERMISSIVE FOR ALL TO public USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND (users.role = 'ADMIN'::"UserRole")))));
CREATE POLICY test_definitions_select ON public.test_definitions AS PERMISSIVE FOR SELECT TO public USING ((auth.uid() IS NOT NULL));
CREATE POLICY test_results_select ON public.test_results AS PERMISSIVE FOR SELECT TO public USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = test_results."userId") OR (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"])))))));
CREATE POLICY test_results_write ON public.test_results AS PERMISSIVE FOR ALL TO public USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = test_results."userId") OR (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"])))))));
CREATE POLICY test_sessions_owner_or_coach_read ON public.test_sessions AS PERMISSIVE FOR SELECT TO authenticated USING ((("userId" = ( SELECT users.id FROM users WHERE (users."authId" = (auth.uid())::text))) OR (EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"])))))));
CREATE POLICY tournament_results_select ON public.tournament_results AS PERMISSIVE FOR SELECT TO public USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = tournament_results."userId") OR (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"])))))));
CREATE POLICY tournament_results_write ON public.tournament_results AS PERMISSIVE FOR ALL TO public USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"]))))));
CREATE POLICY tournaments_select ON public.tournaments AS PERMISSIVE FOR SELECT TO public USING ((auth.uid() IS NOT NULL));
CREATE POLICY tournaments_write ON public.tournaments AS PERMISSIVE FOR ALL TO public USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"]))))));
CREATE POLICY trackman_sessions_select ON public.trackman_sessions AS PERMISSIVE FOR SELECT TO public USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = trackman_sessions."userId") OR (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"])))))));
CREATE POLICY trackman_sessions_write ON public.trackman_sessions AS PERMISSIVE FOR ALL TO public USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = trackman_sessions."userId") OR (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"])))))));
CREATE POLICY training_plan_session_logs_select ON public.training_plan_session_logs AS PERMISSIVE FOR SELECT TO public USING ((EXISTS ( SELECT 1 FROM ((training_plan_sessions s JOIN training_plans p ON ((p.id = s."planId"))) JOIN users u ON ((u."authId" = (auth.uid())::text))) WHERE ((s.id = training_plan_session_logs."sessionId") AND ((p."userId" = u.id) OR (u.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"])))))));
CREATE POLICY training_plan_session_logs_write ON public.training_plan_session_logs AS PERMISSIVE FOR ALL TO public USING ((EXISTS ( SELECT 1 FROM ((training_plan_sessions s JOIN training_plans p ON ((p.id = s."planId"))) JOIN users u ON ((u."authId" = (auth.uid())::text))) WHERE ((s.id = training_plan_session_logs."sessionId") AND ((p."userId" = u.id) OR (u.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"]))))))) WITH CHECK ((EXISTS ( SELECT 1 FROM ((training_plan_sessions s JOIN training_plans p ON ((p.id = s."planId"))) JOIN users u ON ((u."authId" = (auth.uid())::text))) WHERE ((s.id = training_plan_session_logs."sessionId") AND ((p."userId" = u.id) OR (u.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"])))))));
CREATE POLICY training_plan_sessions_select ON public.training_plan_sessions AS PERMISSIVE FOR SELECT TO public USING ((EXISTS ( SELECT 1 FROM (training_plans p JOIN users u ON ((u."authId" = (auth.uid())::text))) WHERE ((p.id = training_plan_sessions."planId") AND ((p."userId" = u.id) OR (u.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"])))))));
CREATE POLICY training_plan_sessions_write ON public.training_plan_sessions AS PERMISSIVE FOR ALL TO public USING ((EXISTS ( SELECT 1 FROM (training_plans p JOIN users u ON ((u."authId" = (auth.uid())::text))) WHERE ((p.id = training_plan_sessions."planId") AND ((p."userId" = u.id) OR (u.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"]))))))) WITH CHECK ((EXISTS ( SELECT 1 FROM (training_plans p JOIN users u ON ((u."authId" = (auth.uid())::text))) WHERE ((p.id = training_plan_sessions."planId") AND ((p."userId" = u.id) OR (u.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"])))))));
CREATE POLICY training_plans_delete ON public.training_plans AS PERMISSIVE FOR DELETE TO public USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND (users.role = 'ADMIN'::"UserRole")))));
CREATE POLICY training_plans_insert ON public.training_plans AS PERMISSIVE FOR INSERT TO public WITH CHECK ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = training_plans."userId") OR (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"])))))));
CREATE POLICY training_plans_select ON public.training_plans AS PERMISSIVE FOR SELECT TO public USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = training_plans."userId") OR (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"])))))));
CREATE POLICY training_plans_update ON public.training_plans AS PERMISSIVE FOR UPDATE TO public USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = training_plans."userId") OR (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"])))))));
CREATE POLICY training_sessions_v2_select ON public.training_sessions_v2 AS PERMISSIVE FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = training_sessions_v2."studentId") OR (users.id = training_sessions_v2."coachId") OR (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"])))))));
CREATE POLICY training_sessions_v2_write ON public.training_sessions_v2 AS PERMISSIVE FOR ALL TO authenticated USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = training_sessions_v2."coachId") OR (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"]))))))) WITH CHECK ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND ((users.id = training_sessions_v2."coachId") OR (users.role = ANY (ARRAY['ADMIN'::"UserRole", 'COACH'::"UserRole"])))))));
CREATE POLICY users_select_own ON public.users AS PERMISSIVE FOR SELECT TO authenticated USING (((( SELECT auth.uid() AS uid))::text = "authId"));
CREATE POLICY users_update_own ON public.users AS PERMISSIVE FOR UPDATE TO authenticated USING (((( SELECT auth.uid() AS uid))::text = "authId")) WITH CHECK (((( SELECT auth.uid() AS uid))::text = "authId"));
CREATE POLICY webhook_failures_admin_read ON public.webhook_failures AS PERMISSIVE FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1 FROM users WHERE ((users."authId" = (auth.uid())::text) AND (users.role = 'ADMIN'::"UserRole")))));

-- ══ storage ══

CREATE POLICY admin_full_access_recordings ON storage.objects AS PERMISSIVE FOR ALL TO public USING (((bucket_id = 'coaching-recordings'::text) AND (EXISTS ( SELECT 1 FROM users u WHERE ((u."authId" = (auth.uid())::text) AND (u.role = 'ADMIN'::"UserRole")))))) WITH CHECK (((bucket_id = 'coaching-recordings'::text) AND (EXISTS ( SELECT 1 FROM users u WHERE ((u."authId" = (auth.uid())::text) AND (u.role = 'ADMIN'::"UserRole"))))));
CREATE POLICY coach_full_access_recordings ON storage.objects AS PERMISSIVE FOR ALL TO public USING (((bucket_id = 'coaching-recordings'::text) AND (EXISTS ( SELECT 1 FROM users u WHERE ((u."authId" = (auth.uid())::text) AND (u.id = (storage.foldername(u.name))[1])))))) WITH CHECK (((bucket_id = 'coaching-recordings'::text) AND (EXISTS ( SELECT 1 FROM users u WHERE ((u."authId" = (auth.uid())::text) AND (u.id = (storage.foldername(u.name))[1]))))));
-- ^ NB: coach_full_access_recordings ser buggy ut i original (u.name er users.name,
--   ikke objects.name) — gjenskapes som-den-er, men flagges for gjennomgang i Fase 3-QA.
