(() => {
const TABS = [{ value: "foresp", label: "Uten betaling" }, { value: "alle", label: "Bookinger" }, { value: "ny", label: "Ny booking" }, { value: "tj", label: "Tjenester og pris" }];
const TONE = { Venter: "info", Bekreftet: "ok", Avvist: "neutral" };
const ta = { width: "100%", boxSizing: "border-box", minHeight: 96, padding: 12, borderRadius: 8, border: "1px solid var(--border-control)", background: "var(--surface-card)", color: "var(--text-primary)", font: "var(--type-body)", resize: "vertical" };
function AG06({ state, go, arg }) {
  const { PageHeader, Button, StatusPill, EmptyState, Tabs, Sheet, KeyValue, Select, FormField, TextInput, Dialog, DataTable, Switch, Icon } = window.AGQ.ns();
  const A = window.AGQ, D = window.AG_DATA, { mob, pad, desk } = A.useW(), empty = state === "tom";
  const [tab, setTab] = React.useState(arg === "ny" ? "ny" : "foresp"), [bk, setBk] = React.useState(D.bookings), [sel, setSel] = React.useState(null), [rej, setRej] = React.useState(null), [why, setWhy] = React.useState(""), [svcs, setSvcs] = React.useState(D.services), [es, setEs] = React.useState(null);
  const [nb, setNb] = React.useState({ who: "Tobias Lindvik", svc: "pt60", date: "Ti 29.09", t: "17:00", pay: "Klipp" });
  const S = (id) => svcs.find((s) => s.id === id), P = (s) => A.price(s, D.rate);
  const list = empty ? [] : bk, pend = list.filter((b) => b.st === "Venter"), cur = list.find((b) => b.id === sel);
  const stamp = () => "Anders Kristiansen · 26.09 " + new Date().toTimeString().slice(0, 5);
  const confirm = (b) => { setBk((l) => l.map((x) => x.id === b.id ? { ...x, st: "Bekreftet", by: stamp() } : x)); setSel(null); A.toast("Bookingen er bekreftet", (b.who + " · " + b.date + " " + b.t + " · BEKREFTELSE SOM UTKAST I INNBOKS").toUpperCase()); };
  const doReject = () => { const b = rej; setBk((l) => l.map((x) => x.id === b.id ? { ...x, st: "Avvist", by: stamp(), reason: why.trim() } : x)); setRej(null); setWhy(""); setSel(null); A.toast("Bookingen er avvist", ("UTKAST TIL " + b.guardian + " LIGGER I INNBOKS · IKKE SENDT").toUpperCase()); };
  const svcLabel = (s) => s.name + " " + s.min + " min";
  const bRow = (b, i, arr) => { const s = S(b.svc); return <button key={b.id} type="button" onClick={() => setSel(b.id)} aria-pressed={sel === b.id} style={{ all: "unset", boxSizing: "border-box", width: "100%", cursor: "pointer", display: "flex", gap: 12, alignItems: "center", flexWrap: "wrap", padding: "12px 16px", minHeight: 64, borderTop: i ? "1px solid var(--border-hairline)" : "none", background: sel === b.id ? "var(--surface-flat)" : "transparent", boxShadow: sel === b.id ? "inset 2px 0 0 var(--border-ink)" : "none" }}>
    <span style={{ font: "600 14px/1 var(--font-mono)", width: 96, flex: "none" }}>{b.date} {b.t}</span>
    <span style={{ flex: "1 1 180px", minWidth: 0, display: "flex", flexDirection: "column", gap: 3 }}><span style={{ font: "500 14px/1.3 var(--font-sans)", color: "var(--text-primary)" }}>{b.who} · {svcLabel(s)}</span><A.Meta>{A.kr(P(s))} · {b.pay.toUpperCase()} · {(b.src || "—").toUpperCase()}</A.Meta></span>
    <StatusPill tone={TONE[b.st]}>{b.st === "Venter" ? "Venter på deg" : b.st}</StatusPill>
  </button>; };
  const detail = cur && (() => { const s = S(cur.svc); return { title: cur.who + " · " + svcLabel(s), body: <><KeyValue items={[["Kilde", cur.src || null, { mono: false }], ["Tjeneste", svcLabel(s), { mono: false }], ["Tid", cur.date + " " + cur.t], ["Sted", s.where, { mono: false }], ["Pris", A.kr(P(s)), { hint: s.price != null ? "FAST PRIS · SERVICETYPE" : "DEMODATA · TIMEPRIS " + A.kr(D.rate) + " × " + s.min + " MIN" }], ["Betaling", cur.pay, { mono: false }], ["Forelder", cur.guardian, { mono: false }], ["Beskjed", cur.note === "—" ? null : cur.note, { mono: false }], ["Bestilt", cur.at], [cur.st === "Avvist" ? "Avvist av" : "Bekreftet av", cur.by || null, { mono: false }], ["Begrunnelse", cur.reason || null, { mono: false }]].filter((x) => x[1] !== undefined)} /><A.Meta>/ADMIN/BOOKINGER/{cur.id.toUpperCase()}</A.Meta></>,
    foot: cur.st === "Venter" ? <><Button fullWidth icon="check" onClick={() => confirm(cur)}>Bekreft booking</Button><Button variant="secondary" fullWidth icon="x" onClick={() => setRej(cur)}>Avvis</Button></> : cur.st === "Bekreftet" ? <><Button variant="secondary" fullWidth icon="calendar-clock" onClick={() => A.toast("Velg ny tid", "SPILLEREN FÅR UTKAST TIL BESKJED")}>Flytt</Button><Button variant="ghost" fullWidth onClick={() => setRej(cur)}>Avlys med begrunnelse</Button></> : <Button variant="ghost" fullWidth onClick={() => setSel(null)}>Lukk</Button> }; })();
  let body;
  if (tab === "foresp" || tab === "alle") { const rows = tab === "foresp" ? pend : list;
    body = !rows.length ? <EmptyState icon="calendar-check" title={tab === "foresp" ? "Ingen bookinger uten betaling venter" : "Ingen bookinger"} text="Spillere og foreldre booker fra PlayerHQ når du har satt tilgjengelighet." action="Ny booking" actionIcon="plus" onAction={() => setTab("ny")} />
      : desk ? <A.Cols tpl="minmax(0,1.1fr) minmax(0,1fr)"><div className="pa-card" style={{ padding: 0, overflow: "hidden" }}>{rows.map(bRow)}</div>{detail ? <A.Card pad={20} gap={16}><div><span className="kicker">Booking</span><div style={{ font: "var(--type-title-s)", marginTop: 4 }}>{detail.title}</div></div>{detail.body}<div style={{ display: "flex", flexDirection: "column", gap: 8 }}>{detail.foot}</div></A.Card> : <A.Card><EmptyState icon="mouse-pointer-click" title="Velg en booking" text="Bekreft eller avvis forespørsler herfra." /></A.Card>}</A.Cols>
      : <><div className="pa-card" style={{ padding: 0, overflow: "hidden" }}>{rows.map(bRow)}</div><Sheet open={!!cur} onClose={() => setSel(null)} kicker="Booking" title={detail ? detail.title : ""} footer={detail && detail.foot}>{detail && detail.body}</Sheet></>; }
  if (tab === "ny") { const s = S(nb.svc); const clipOk = s && s.clip; body = <A.Cols tpl={desk ? "minmax(0,1.2fr) minmax(0,1fr)" : "minmax(0,1fr)"}>
    <A.Card gap={14}><A.Head k="Ny booking" aside="/ADMIN/BOOKINGER/NY" />
      <Select label="Spiller" value={nb.who} onChange={(e) => setNb({ ...nb, who: e.target.value })} options={["Tobias Lindvik", "Lea Brekke", "Magnus Aasheim", "Kasper Moen"]} />
      <Select label="Tjeneste" value={nb.svc} onChange={(e) => setNb({ ...nb, svc: e.target.value, pay: S(e.target.value).clip ? nb.pay : "Faktura" })} options={svcs.filter((x) => x.active).map((x) => ({ value: x.id, label: svcLabel(x) + " · " + A.kr(P(x)) }))} />
      <A.Cols tpl="repeat(2,minmax(0,1fr))" gap={12}><Select label="Dag" value={nb.date} onChange={(e) => setNb({ ...nb, date: e.target.value })} options={D.cal.days.map((d) => d.join(" "))} /><Select label="Tid" value={nb.t} onChange={(e) => setNb({ ...nb, t: e.target.value })} options={["14:00", "15:00", "16:00", "17:00", "18:00"]} /></A.Cols>
      <Select label="Betaling" value={nb.pay} onChange={(e) => setNb({ ...nb, pay: e.target.value })} options={clipOk ? ["Klipp", "Faktura"] : ["Faktura"]} hint={clipOk ? "Én coachet økt trekker ett klipp fra Performance (2 per måned) eller Performance Pro (4 per måned)." : "Denne tjenesten faktureres."} />
    </A.Card>
    <A.Card gap={12}><A.Head k="Sammendrag" /><KeyValue items={[["Tjeneste", s ? svcLabel(s) : null, { mono: false }], ["Tid", nb.date + " " + nb.t], ["Pris", s ? A.kr(P(s)) : null, { hint: s && s.price == null ? "DEMODATA · TIMEPRIS " + A.kr(D.rate) + " FRA SERVICETYPE" : "FAST PRIS FRA SERVICETYPE" }], ["Betaling", nb.pay === "Klipp" ? "1 klipp fra coaching-pakken" : "Faktura", { mono: false }]]} />
      <Button icon="check" onClick={() => { setBk((l) => [{ id: "b" + (l.length + 1), st: "Bekreftet", who: nb.who, guardian: "—", svc: nb.svc, date: nb.date, t: nb.t, pay: nb.pay, note: "—", at: "26.09", by: stamp() }, ...l]); setTab("alle"); A.toast("Bookingen er opprettet", "BEKREFTELSE SOM UTKAST I INNBOKS"); }}>Opprett booking</Button></A.Card>
  </A.Cols>; }
  if (tab === "tj") body = <A.Stack>
    <DataTable caption={"Tjenester · timepris " + A.kr(D.rate) + " (demodata, ikke ekte pris) · kilde ServiceType"} rowKey="id" onSelect={(id) => setEs({ ...S(id) })} columns={[{ key: "name", label: "Tjeneste" }, { key: "min", label: "Varighet", mono: true, align: "right", render: (r) => A.hm(r.min) }, { key: "p", label: "Pris", mono: true, align: "right", render: (r) => A.kr(P(r)) }, { key: "b", label: "Prisgrunnlag", render: (r) => r.price != null ? "Fast pris" : "Timepris × varighet" }, { key: "clip", label: "Klipp", render: (r) => r.clip ? "Ja" : "Nei" }, { key: "active", label: "Status", render: (r) => <StatusPill tone={r.active ? "ok" : "neutral"}>{r.active ? "Aktiv" : "Skjult"}</StatusPill> }]} rows={empty ? [] : svcs} />
    {empty && <EmptyState icon="tag" title="Ingen tjenester" text="Legg inn første tjeneste med varighet. Prisen regnes fra timeprisen hvis du ikke setter fast pris." action="Ny tjeneste" actionIcon="plus" />}
  </A.Stack>;
  return <A.Page>
    <PageHeader kicker={"Booking · " + D.dayLabel} title="Booking" sub="Betalte bookinger (offentlig og PlayerHQ) bekreftes automatisk når tiden er ledig. Du bekrefter eller avviser bare bookinger uten betaling. Alle kan avlyses." actions={<Button variant="secondary" icon="plus" onClick={() => setTab("ny")}>Ny booking</Button>} />
    <A.Gate state={state} loading="Henter bookinger …" error={{ title: "Bookingene kunne ikke hentes", text: "Ingen bookinger er endret. Spillerne ser fortsatt sine bekreftede timer.", code: "FEIL 502 · BOOKING" }}>
      <Tabs tabs={TABS.map((t) => t.value === "foresp" ? { ...t, count: empty ? undefined : pend.length } : t)} value={tab} onChange={(v) => { setTab(v); setSel(null); }} />
      {body}
    </A.Gate>
    <Dialog open={!!rej} onClose={() => setRej(null)} title={rej && rej.st === "Bekreftet" ? "Avlyse bookingen?" : "Avvise bookingen?"} footer={<><Button variant="ghost" onClick={() => setRej(null)}>Avbryt</Button><Button variant="signal" disabled={why.trim().length < 8} onClick={doReject}>{rej && rej.st === "Bekreftet" ? "Avlys og lag utkast" : "Avvis og lag utkast"}</Button></>}>
      {rej && <div style={{ display: "flex", flexDirection: "column", gap: 12 }}><p style={{ margin: 0, font: "var(--type-body)" }}>{rej.who} · {rej.date} {rej.t}. Begrunnelsen går til {rej.guardian !== "—" ? rej.guardian + " og " + rej.who.split(" ")[0] : rej.who} som et utkast i Innboks. Du sender det selv.</p>
        <FormField label="Kort begrunnelse" required hint="Minst 8 tegn." error={why && why.trim().length < 8 ? "Skriv en kort begrunnelse på minst 8 tegn." : undefined}><textarea style={ta} value={why} onChange={(e) => setWhy(e.target.value)} placeholder="Studio 1 er stengt for service tirsdag." /></FormField></div>}
    </Dialog>
    <Sheet open={!!es} onClose={() => setEs(null)} kicker="Tjeneste · ServiceType" title={es ? es.name : ""} footer={<><Button fullWidth icon="check" onClick={() => { setSvcs((l) => l.map((x) => x.id === es.id ? es : x)); setEs(null); A.toast("Tjenesten er lagret", "NYE PRISER GJELDER NYE BOOKINGER"); }}>Lagre tjeneste</Button><Button variant="ghost" fullWidth onClick={() => setEs(null)}>Avbryt</Button></>}>
      {es && <><FormField label="Navn"><TextInput value={es.name} onChange={(e) => setEs({ ...es, name: e.target.value })} /></FormField><Select label="Varighet" value={String(es.min)} onChange={(e) => setEs({ ...es, min: +e.target.value })} options={["30", "60", "90", "120", "150"].map((v) => ({ value: v, label: v + " min" }))} />
        <FormField label="Fast pris" hint={"Tomt felt = timepris (demodata) " + A.kr(D.rate) + " × varighet = " + A.kr(A.price({ min: es.min }, D.rate))}><TextInput mono inputMode="numeric" value={es.price ?? ""} placeholder="—" onChange={(e) => setEs({ ...es, price: e.target.value === "" ? undefined : +e.target.value.replace(/\D/g, "") })} /></FormField>
        <Switch checked={es.clip} onChange={(e) => setEs({ ...es, clip: e.target.checked })} label="Coachet økt · trekker ett klipp" /><Switch checked={es.active} onChange={(e) => setEs({ ...es, active: e.target.checked })} label="Synlig for spillere" />
        {es.note && <A.Meta>{es.note.toUpperCase()}</A.Meta>}</>}
    </Sheet>
  </A.Page>;
}
window.AG_SCREENS["AG-06"] = { id: "AG-06", name: "Booking (coach)", route: "/admin/bookinger", Component: AG06 };
})();
