/* AG-08 Spiller 360 › IUP (runde 31). Team Norways IUP-arks rekkefølge. Alt hentet fra PlayerHQ (_shared/data-iup.js m.fl.).
   Kompetansemål fra Udir vises ikke her. */
(() => {
function IUP({ empty, ak }) {
  const { KeyValue, StatusPill, Button, AxisBadge } = window.AGQ.ns();
  const A = window.AGQ, I = window.IUP_DATA, U = I.iup, C = I.check, p = I.player, { desk } = A.useW();
  const G = window.STATS_DATA ? window.STATS_DATA.tests : null;
  const Sec = ({ n, children, aside }) => <A.Card gap={10}><div style={{ display: "flex", gap: 8, alignItems: "baseline", flexWrap: "wrap" }}><span style={{ font: "600 12px/1 var(--font-mono)", color: "var(--text-muted)" }}>{String(n + 1).padStart(2, "0")}</span><span className="kicker" style={{ flex: "1 1 auto" }}>{U.order[n]}</span>{aside && <A.Meta>{aside}</A.Meta>}</div>{children}</A.Card>;
  const Rows = ({ rows, tpl = "minmax(0,1fr) auto" }) => <div role="list">{rows.map((r, i) => <div role="listitem" key={i} style={{ display: "grid", gridTemplateColumns: tpl, gap: 12, alignItems: "center", minHeight: 44, borderTop: i ? "1px solid var(--border-hairline)" : "none", padding: "6px 0", minWidth: 0 }}>{r.map((c, j) => <span key={j} style={j === 0 ? { display: "flex", flexDirection: "column", gap: 2, minWidth: 0, font: "500 14px/1.3 var(--font-sans)", color: "var(--text-primary)", overflowWrap: "anywhere" } : { font: j === r.length - 1 ? "600 13px/1.3 var(--font-mono)" : "var(--type-meta)", color: j === r.length - 1 ? "var(--text-primary)" : "var(--text-muted)", textAlign: "right" }}>{c}</span>)}</div>)}</div>;
  const E = <p style={{ margin: 0, font: "var(--type-body-s)", color: "var(--text-secondary)" }}>—</p>;
  const tot = U.training.hours.reduce((a, [, h]) => a + h, 0);
  const secs = [
    <Sec n={0} key={0} aside="FRA PLAYERHQ · MEG"><KeyValue columns={1} items={[["Navn", p.name, { mono: false }], ["Født", String(p.born), { hint: "KLASSE " + p.klasse }], ["Klubb", p.club, { mono: false }], ["Skole", p.school, { mono: false }], ["Hovedcoach", p.coach, { mono: false }], ["WANG", ak ? null : p.wang, { mono: false }], ["Team Norway", ak ? null : p.tnProgram + " · " + p.tn, { mono: false }], ["Nivå utviklingssjekk", ak ? null : p.level, { mono: false, hint: ak ? "BARE WANG- OG TEAM NORWAY-GRUPPER" : undefined }]]} /><A.Meta>RANKING</A.Meta><Rows rows={p.ranking.map(([k, pl, d, src]) => [<>{k}<A.Meta>{src}</A.Meta></>, pl ? pl + " · " + d : "—"])} /></Sec>,
    <Sec n={1} key={1} aside={ak ? "SESONGEVALUERING" : "FIREUKERSSJEKK UKE " + C.last.weeks + " · " + C.last.date}>{empty ? E : ak ? <Rows rows={[["Sesongevaluering", "UKE 42 · —"], ["Fireukerssjekk", "— · BARE WANG OG TEAM NORWAY"]]} /> : <><p style={{ margin: 0, font: "var(--type-body-s)", color: "var(--text-primary)", textWrap: "pretty" }}>«{C.last.note}»</p><Rows rows={[["Neste fireukerssjekk", "FRIST " + C.dueFull], ["Sesongevaluering", "UKE 42 · —"]]} /></>}</Sec>,
    <Sec n={2} key={2} aside="PLAN › MÅLSETNING">{empty ? E : <Rows rows={C.goals.map(([n, now, mal, src]) => [<>{n}<A.Meta>{src}</A.Meta></>, "MÅL " + mal.toUpperCase(), now])} />}</Sec>,
    <Sec n={3} key={3} aside={ak ? "FRA PLAN" : "SVAR UKE " + C.last.weeks}>{empty ? E : ak ? <Rows rows={C.process.map((x) => [x, "—"])} /> : <Rows rows={C.process.map((x, i) => [x, <StatusPill tone={C.last.process[i] === "Ja" ? "ok" : C.last.process[i] === "Nei" ? "warn" : "neutral"}>{C.last.process[i]}</StatusPill>])} />}</Sec>,
    <Sec n={4} key={4} aside="PLAN › ÅR · TIMER GJENNOMFØRT / PLAN">{empty ? E : <Rows tpl="minmax(0,1fr) auto auto" rows={U.periods.map(([n, w, h]) => [n, w.toUpperCase(), h])} />}</Sec>,
    <Sec n={5} key={5} aside="PLAN › TURNERINGER · GOLFBOX">{empty ? E : <Rows rows={U.tournaments.map(([d, n, c, r]) => [<>{n}<A.Meta>{d} · {c.toUpperCase()}</A.Meta></>, r])} />}</Sec>,
    <Sec n={6} key={6} aside="PLAN › UKE 39">{empty ? E : <Rows tpl="72px minmax(0,1fr) auto" rows={U.week.map(([d, n, m]) => [<A.Meta>{d.toUpperCase()}</A.Meta>, <span style={{ font: "400 14px/1.3 var(--font-sans)", color: "var(--text-primary)", textAlign: "left" }}>{n}</span>, m])} />}</Sec>,
    <Sec n={7} key={7} aside={U.training.src}>{empty ? E : <><div style={{ display: "flex", alignItems: "baseline", gap: 8, flexWrap: "wrap" }}><span style={{ font: "600 22px/1 var(--font-mono)", color: "var(--text-primary)" }}>{U.training.n} av {U.training.of}</span><A.Meta>ØKTER GJENNOMFØRT · {A.dec ? A.dec(tot) : String(tot).replace(".", ",")} T</A.Meta></div><div role="list">{U.training.hours.map(([a, h], i) => <div role="listitem" key={a} style={{ display: "grid", gridTemplateColumns: "64px minmax(0,1fr) auto", gap: 12, alignItems: "center", minHeight: 36, borderTop: i ? "1px solid var(--border-hairline)" : "none" }}><span><AxisBadge axis={a} size="sm" /></span><span aria-hidden="true" style={{ height: 8, background: "var(--surface-sunken)", position: "relative" }}><span style={{ position: "absolute", inset: 0, width: (h / 25 * 100) + "%", background: "var(--primary)" }}></span></span><span style={{ font: "600 13px/1 var(--font-mono)", color: "var(--text-primary)" }}>{String(h).replace(".", ",")} t</span></div>)}</div></>}</Sec>,
    ak ? <Sec n={8} key={8} aside="GJELDER IKKE">{<p style={{ margin: 0, font: "var(--type-body-s)", color: "var(--text-secondary)", textWrap: "pretty" }}>Utviklingssjekken og fireukerssjekken gjelder bare spillere i en WANG-gruppe (Ung eller Toppidrett) eller en Team Norway-gruppe.</p>}</Sec> : <Sec n={8} key={8} aside={"NIVÅ " + C.level.toUpperCase() + " · SKALA 1–8 · UKE " + C.last.weeks}>{empty ? E : <><Rows rows={C.questions[C.level].map(([an, qs], ai) => { const a = C.last.answers[ai] || [], v = a.length ? a.reduce((x, y) => x + y, 0) / a.length : null; return [<>{an}<A.Meta>{qs.length} SPØRSMÅL · LAVEST: {a.length ? qs[a.indexOf(Math.min(...a))].toUpperCase().slice(0, 60) : "—"}</A.Meta></>, v == null ? "—" : v.toFixed(1).replace(".", ",") + " / 8"]; })} /><A.Meta>{C.src}</A.Meta></>}</Sec>,
    <Sec n={9} key={9} aside="STATS › TESTER · ETT BATTERI">{empty || !G ? E : <Rows tpl="minmax(0,1fr) auto auto" rows={G.map((t) => [<>{t.name}<A.Meta>{t.src}</A.Meta></>, (t.by || "—").toUpperCase(), t.hist[t.hist.length - 1] + " " + t.unit])} />}</Sec>,
    <Sec n={10} key={10} aside={U.techSrc}>{empty ? E : <Rows rows={U.tech.map(([pp, n, s]) => [<>{pp} · {n}</>, <StatusPill tone="info">{s}</StatusPill>])} />}</Sec>,
    <Sec n={11} key={11} aside="STATS › TESTER · FYS">{empty ? E : <Rows rows={U.fys.map(([n, v, src]) => [<>{n}<A.Meta>{src}</A.Meta></>, v])} />}</Sec>,
  ];
  const half = Math.ceil(secs.length / 2);
  return <>
    <div style={{ display: "flex", gap: 12, alignItems: "center", flexWrap: "wrap" }}><p style={{ margin: 0, flex: "1 1 260px", font: "var(--type-body-s)", color: "var(--text-secondary)", textWrap: "pretty" }}>I Team Norways IUP-arks rekkefølge. Alt er hentet fra PlayerHQ og oppdateres når spilleren registrerer. Kompetansemål fra Udir vises ikke her.</p><Button variant="secondary" icon="file-down" onClick={() => A.toast("IUP-ark lages", "PDF · TEAM NORWAY-MAL · " + p.name.toUpperCase())}>Last ned IUP-ark</Button></div>
    {desk ? <A.Cols tpl="repeat(2,minmax(0,1fr))"><A.Stack>{secs.slice(0, half)}</A.Stack><A.Stack>{secs.slice(half)}</A.Stack></A.Cols> : <A.Stack>{secs}</A.Stack>}
  </>;
}
window.AG_IUP = IUP;
})();
