(() => {
const TABS = [{ value: "uke", label: "Uke" }, { value: "maned", label: "Måned" }, { value: "dag", label: "Dag" }, { value: "stall", label: "Stall-dag" }, { value: "tilg", label: "Tilgjengelighet" }];
const H0 = 7, H1 = 21, PX = 44;
const hh = (h) => String(Math.floor(h)).padStart(2, "0") + ":" + (h % 1 ? "30" : "00");
const KL = { felles: "Lag", privat: "Privattime", opptatt: "Opptatt", ledig: "Ledig" };
function AG05({ state, go }) {
  const { PageHeader, Button, StatusPill, EmptyState, Tabs, SegmentedFilter, Sheet, KeyValue, AxisBadge, Select, Switch, FormField, TextInput, MoveSheet, ConflictSheet } = window.AGQ.ns();
  const A = window.AGQ, D = window.AG_DATA, C = D.cal, { mob, pad, desk, nav } = A.useW(), empty = state === "tom";
  const [evs, setEvs] = React.useState(C.ev), [mv, setMv] = React.useState(null), [mvTo, setMvTo] = React.useState(null), [cf, setCf] = React.useState(null), [dragId, setDragId] = React.useState(null);
  /* Flytting: dra i ukevisning (desktop), eller «Flytt» i arket (alle bredder). Overlapp og tilgjengelighet sjekkes før noe endres. */
  const clash = (e, d, s) => evs.find((x) => x.id !== e.id && x.d === d && x.k !== "ledig" && s < x.s + x.l && s + e.l > x.s);
  const apply = (e, d, s) => { const before = evs; setEvs((l) => l.map((x) => x.id === e.id ? { ...x, d, s } : x)); const lbl = (e.title || KL[e.k]) + " → " + C.days[d].join(" ") + " " + hh(s); nav ? nav.undo("Hendelsen er flyttet", (lbl + (e.k === "privat" ? " · SPILLER FÅR VARSEL" : "")).toUpperCase(), () => setEvs(before)) : A.toast("Hendelsen er flyttet", lbl.toUpperCase()); };
  const tryMove = (e, d, s) => { if (e.d === d && e.s === s) return; const c = clash(e, d, s), items = [];
    if (c) items.push({ kind: "kalender", text: "Overlapper med " + (c.title || KL[c.k]) + " " + hh(c.s) + "–" + hh(c.s + c.l) + ".", meta: C.days[d].join(" ").toUpperCase() });
    if (s < 8 || s + e.l > 21) items.push({ kind: "tilgang", text: "Utenfor tilgjengeligheten din (08–21).", meta: "TILGJENGELIGHET" });
    if (items.length) setCf({ e, d, s, items }); else apply(e, d, s); };
  const slots = (e) => e ? C.days.flatMap((dd, d) => [9, 14, 16, 17.5].map((s) => { const c = clash(e, d, s); return { id: d + ":" + s, label: dd.join(" ") + " · " + hh(s) + "–" + hh(s + e.l), reason: c ? "OVERLAPPER " + (c.title || KL[c.k]).toUpperCase() : null, warn: !!c, disabled: e.d === d && e.s === s }; })) : [];
  const [tab, setTab] = React.useState("uke"), [teams, setTeams] = React.useState(["Alle"]), [open, setOpen] = React.useState(null), [nu, setNu] = React.useState(false), [day, setDay] = React.useState(0), [avail, setAvail] = React.useState(C.avail);
  const ev = empty ? [] : evs.filter((e) => teams.includes("Alle") || !e.team || teams.includes(e.team));
  const setT = (v) => { const last = v[v.length - 1]; setTeams(!v.length || last === "Alle" ? ["Alle"] : v.filter((x) => x !== "Alle")); };
  const card = (e, compact) => <A.EvCard key={e.id} axes={e.axis} dashed={e.k === "ledig"} busy={e.k === "opptatt"} onClick={() => setOpen(e)} style={compact ? { height: "100%", padding: "4px 6px 4px 10px" } : null}>
    <span style={{ font: (compact ? "500 12px/1.25" : "500 14px/1.3") + " var(--font-sans)", color: e.k === "ledig" || e.k === "opptatt" ? "var(--text-secondary)" : "var(--text-primary)", overflow: "hidden", textOverflow: "ellipsis", display: "-webkit-box", WebkitLineClamp: compact && e.l < 1.5 ? 1 : 2, WebkitBoxOrient: "vertical" }}>{e.title || KL[e.k]}</span>
    {(!compact || e.l >= 1.5) && <A.Meta s={compact ? { fontSize: 10 } : null}>{hh(e.s)}–{hh(e.s + e.l)}{!compact && e.where ? " · " + e.where.toUpperCase() : ""}{e.n ? " · " + e.n : ""}</A.Meta>}
  </A.EvCard>;
  const legend = <div style={{ display: "flex", gap: 16, flexWrap: "wrap", alignItems: "center" }}>{["fys", "tek", "slag", "spill", "turn"].map((a) => <AxisBadge key={a} axis={a} />)}<span style={{ display: "inline-flex", gap: 6, alignItems: "center" }}><span style={{ width: 16, height: 12, border: "1px dashed var(--border-strong)", borderRadius: 2 }}></span><A.Meta>LEDIG</A.Meta></span><span style={{ display: "inline-flex", gap: 6, alignItems: "center" }}><span style={{ width: 16, height: 12, background: "var(--surface-sunken)", border: "1px solid var(--border-hairline)", borderRadius: 2 }}></span><A.Meta>OPPTATT</A.Meta></span></div>;
  let body;
  if (tab === "uke") body = desk ? <div className="pa-card" style={{ padding: 0, overflow: "hidden" }}>
    <div style={{ display: "grid", gridTemplateColumns: "48px repeat(7,minmax(0,1fr))", borderBottom: "1px solid var(--border-hairline)", background: "var(--surface-flat)" }}><span></span>{C.days.map(([d, dt], i) => <span key={i} style={{ padding: "10px 6px", font: "600 12px/1 var(--font-mono)", color: "var(--text-primary)", borderLeft: "1px solid var(--border-hairline)" }}>{d.toUpperCase()} {dt}</span>)}</div>
    <div style={{ display: "grid", gridTemplateColumns: "48px repeat(7,minmax(0,1fr))", position: "relative" }}>
      <div>{Array.from({ length: H1 - H0 }, (_, i) => <div key={i} style={{ height: PX, font: "400 11px/1 var(--font-mono)", color: "var(--text-muted)", padding: "4px 6px 0", boxSizing: "border-box", textAlign: "right" }}>{hh(H0 + i)}</div>)}</div>
      {C.days.map((_, di) => <div key={di} data-drop={dragId ? "aktiv" : undefined} onDragOver={(e) => { if (dragId) e.preventDefault(); }} onDrop={(e) => { e.preventDefault(); const it = evs.find((x) => x.id === e.dataTransfer.getData("application/x-ak-event")); setDragId(null); if (!it) return; const r = e.currentTarget.getBoundingClientRect(); const s = Math.max(H0, Math.min(H1 - it.l, Math.round(((e.clientY - r.top) / PX + H0) * 2) / 2)); tryMove(it, di, s); }} style={{ position: "relative", borderLeft: "1px solid var(--border-hairline)", outline: dragId ? "1px dashed var(--border-strong)" : "none", outlineOffset: -2, backgroundImage: "repeating-linear-gradient(to bottom, transparent 0 " + (PX - 1) + "px, var(--border-hairline) " + (PX - 1) + "px " + PX + "px)", height: (H1 - H0) * PX }}>
        {ev.filter((e) => e.d === di).map((e) => <div key={e.id} draggable={e.k !== "ledig"} onDragStart={(x) => { x.dataTransfer.setData("application/x-ak-event", e.id); x.dataTransfer.effectAllowed = "move"; setDragId(e.id); }} onDragEnd={() => setDragId(null)} style={{ position: "absolute", left: 3, right: 3, top: (e.s - H0) * PX + 2, height: e.l * PX - 4, opacity: dragId === e.id ? .45 : 1, cursor: e.k !== "ledig" ? "grab" : "pointer" }}>{card(e, true)}</div>)}
      </div>)}
    </div>
  </div> : <A.Stack gap={12}>{C.days.map(([d, dt], di) => { const es = ev.filter((e) => e.d === di).sort((a, b) => a.s - b.s); return <section key={di} style={{ display: "flex", flexDirection: "column", gap: 6 }}><div style={{ font: "600 13px/1 var(--font-mono)", color: "var(--text-primary)", padding: "4px 0" }}>{d.toUpperCase()} {dt}</div>{es.length ? es.map((e) => <div key={e.id} style={{ display: "grid", gridTemplateColumns: "48px minmax(0,1fr)", gap: 8 }}><span style={{ font: "500 12px/1 var(--font-mono)", color: "var(--text-secondary)", paddingTop: 10 }}>{hh(e.s)}</span>{card(e)}</div>) : <A.Meta>—</A.Meta>}</section>; })}</A.Stack>;
  if (tab === "maned") { const first = 1, dim = 31; const cells = Array.from({ length: 35 }, (_, i) => i - 3 + 1); /* oktober 2026 starter torsdag */
    body = <div className="pa-card" style={{ padding: mob ? 8 : 12, gap: 8 }}><div style={{ font: "600 15px/1 var(--font-sans)", padding: 4 }}>Oktober 2026</div>
      <div style={{ display: "grid", gridTemplateColumns: "repeat(7,minmax(0,1fr))", gap: 4 }}>{["MA", "TI", "ON", "TO", "FR", "LØ", "SØ"].map((d) => <A.Meta key={d} s={{ textAlign: "center" }}>{d}</A.Meta>)}
        {cells.map((n, i) => { const inM = n >= first && n <= dim, dow = i % 7, es = inM && !empty ? C.ev.filter((e) => e.d === dow && e.k !== "ledig" && e.k !== "opptatt") : []; return <button key={i} type="button" disabled={!inM} onClick={() => { setDay(dow); setTab("dag"); }} style={{ all: "unset", boxSizing: "border-box", cursor: inM ? "pointer" : "default", minHeight: mob ? 52 : 84, padding: 6, borderRadius: 4, border: "1px solid var(--border-hairline)", background: inM ? "var(--surface-card)" : "transparent", display: "flex", flexDirection: "column", gap: 4, minWidth: 0 }}>
          <span style={{ font: "500 12px/1 var(--font-mono)", color: inM ? "var(--text-primary)" : "var(--text-faint)" }}>{inM ? n : ""}</span>
          {inM && (mob ? es.length > 0 && <span style={{ display: "flex", gap: 2, flexWrap: "wrap" }}>{es.slice(0, 4).map((e) => <span key={e.id} style={{ width: 6, height: 6, borderRadius: 1, background: A.stripe(e.axis) }}></span>)}</span>
            : es.slice(0, 3).map((e) => <span key={e.id} style={{ display: "flex", gap: 4, alignItems: "center", minWidth: 0 }}><span style={{ width: 3, alignSelf: "stretch", background: A.stripe(e.axis) }}></span><span style={{ font: "400 11px/1.2 var(--font-sans)", color: "var(--text-secondary)", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{hh(e.s)} {e.title}</span></span>))}
        </button>; })}</div></div>; }
  if (tab === "dag") body = <A.Stack gap={12}><div style={{ display: "flex", gap: 6, flexWrap: "wrap" }}>{C.days.map(([d, dt], i) => <Button key={i} size="sm" variant={i === day ? "primary" : "ghost"} onClick={() => setDay(i)}>{d} {dt}</Button>)}</div>
    <div className="pa-card" style={{ padding: 16, gap: 8 }}>{ev.filter((e) => e.d === day).sort((a, b) => a.s - b.s).map((e) => <div key={e.id} style={{ display: "grid", gridTemplateColumns: "56px minmax(0,1fr)", gap: 10 }}><span style={{ font: "500 13px/1 var(--font-mono)", color: "var(--text-secondary)", paddingTop: 10 }}>{hh(e.s)}</span>{card(e)}</div>)}{!ev.some((e) => e.d === day) && <A.Meta>—</A.Meta>}</div></A.Stack>;
  if (tab === "stall") body = <A.Stack gap={8}><A.Meta>STALL-DAG · MANDAG 28.09 · HVA HVER SPILLER HAR I PLANEN</A.Meta>
    <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill,minmax(min(100%,300px),1fr))", gap: 8 }}>{(empty ? [] : C.stall).map(([who, grp, what, ax, t, st]) => <A.EvCard key={who} axes={ax} dashed={!what}><span style={{ display: "flex", gap: 8, alignItems: "baseline", flexWrap: "wrap" }}><span style={{ font: "600 14px/1.3 var(--font-sans)", flex: "1 1 120px", minWidth: 0 }}>{who}</span><StatusPill tone={st === "Ingen plan" ? "warn" : "neutral"}>{st}</StatusPill></span><span style={{ font: "var(--type-body-s)", color: "var(--text-secondary)" }}>{what || "—"}</span><A.Meta>{grp.toUpperCase()} · {t}</A.Meta></A.EvCard>)}</div></A.Stack>;
  if (tab === "tilg") body = <A.Cols tpl={desk ? "minmax(0,1.2fr) minmax(0,1fr)" : "minmax(0,1fr)"}>
    <A.Card gap={4}><A.Head k="Fast ukemønster" aside="GJELDER FRA 01.10.2026" />{avail.map(([d, t, on], i) => <div key={d} style={{ display: "flex", alignItems: "center", gap: 12, minHeight: 52, borderTop: i ? "1px solid var(--border-hairline)" : "none", flexWrap: "wrap" }}><span style={{ font: "500 14px/1 var(--font-sans)", width: 88 }}>{d}</span><span style={{ font: "var(--type-num-s)", color: on ? "var(--text-primary)" : "var(--text-muted)", flex: 1 }}>{on ? t : "—"}</span><Switch checked={on} onChange={(e) => setAvail((l) => l.map((x, j) => j === i ? [x[0], e.target.checked && x[1] === "—" ? "15:00–19:00" : x[1], e.target.checked] : x))} label={on ? "Ledig" : "Stengt"} /></div>)}
      <div style={{ paddingTop: 12 }}><Button icon="check" onClick={() => A.toast("Tilgjengelighet lagret", "SPILLERNE SER NYE TIDER I BOOKING")}>Lagre tilgjengelighet</Button></div></A.Card>
    <A.Card gap={8}><A.Head k="Unntak" />{C.except.map(([d, t]) => <div key={d} style={{ display: "flex", gap: 10, alignItems: "baseline", flexWrap: "wrap", padding: "8px 0", borderTop: "1px solid var(--border-hairline)" }}><span style={{ font: "var(--type-num-s)" }}>{d}</span><span style={{ font: "var(--type-body-s)", color: "var(--text-secondary)" }}>{t}</span></div>)}<div><Button variant="secondary" size="sm" icon="plus" onClick={() => A.toast("Nytt unntak", "VELG DATO")}>Legg til unntak</Button></div></A.Card>
  </A.Cols>;
  return <A.Page max={1480}>
    <PageHeader kicker={"Kalender · uke 40 · 28.09–04.10.2026"} title="Kalender" sub={desk ? "Dra en hendelse til ny dag og tid, eller åpne den og velg Flytt." : "Trykk en hendelse og velg Flytt."} actions={<Button variant="secondary" icon="plus" onClick={() => setNu(true)}>Ny hendelse</Button>} />
    <A.Gate state={state} loading="Henter kalenderen …" error={{ title: "Kalenderen kunne ikke hentes", text: "Ingen hendelser er endret. Bookinger fra spillere tas vare på.", code: "FEIL 503 · KALENDER" }}>
      <Tabs tabs={TABS} value={tab} onChange={setTab} />
      {tab !== "tilg" && tab !== "stall" && <SegmentedFilter label="Lag" multi value={teams} onChange={setT} options={["Alle"].concat(C.teams)} />}
      {tab !== "tilg" && tab !== "stall" && legend}
      {tab === "uke" && !empty && <section aria-label="Turneringslag" style={{ display: "flex", flexDirection: "column", gap: 8 }}>
        <div style={{ display: "grid", gridTemplateColumns: desk ? "48px repeat(7,minmax(0,1fr))" : "repeat(auto-fill,minmax(96px,1fr))", gap: 4, alignItems: "stretch" }}>{desk && <A.Meta s={{ alignSelf: "center" }}>TURN</A.Meta>}{window.WB_DATA.days2.map((x, i) => <div key={i} style={{ minHeight: 44, padding: "6px 8px", borderRadius: "var(--radius-inner)", display: "flex", flexDirection: "column", justifyContent: "center", gap: 2, background: x.turn ? "var(--axis-turn-soft)" : "transparent", border: x.travel ? "1px dashed var(--border-strong)" : x.school ? "1px solid var(--border-hairline)" : "1px solid transparent", boxShadow: x.turn ? "inset 3px 0 0 var(--axis-turn)" : "none" }}><A.Meta>{x.d.toUpperCase()}</A.Meta><span style={{ font: "500 12px/1.2 var(--font-sans)", color: "var(--text-primary)", overflowWrap: "anywhere" }}>{x.turn ? "Srixon Tour · runde " + (i - 4) : x.travel ? "Reise til Larvik" : x.school ? "Skole: heldagsprøve" : "—"}</span></div>)}</div>
        <div role="alert" style={{ display: "flex", gap: 8, alignItems: "center", flexWrap: "wrap", padding: "8px 12px", borderRadius: "var(--radius)", background: "var(--warn-tint)" }}><span style={{ flex: "1 1 240px", font: "var(--type-body-s)" }}>Styrke B ligger på reisedag tor 01.10 for Tobias Lindvik.</span><Button size="sm" variant="secondary" icon="dumbbell" onClick={() => go("AG-WB-FYS")}>Løs i fysisk plan</Button></div>
        <div style={{ display: "flex", gap: 16, flexWrap: "wrap" }}><span style={{ display: "inline-flex", gap: 6, alignItems: "center" }}><span style={{ width: 16, height: 12, background: "var(--axis-turn-soft)", boxShadow: "inset 3px 0 0 var(--axis-turn)" }}></span><A.Meta>TURNERING</A.Meta></span><span style={{ display: "inline-flex", gap: 6, alignItems: "center" }}><span style={{ width: 16, height: 12, border: "1px dashed var(--border-strong)" }}></span><A.Meta>REISE</A.Meta></span><span style={{ display: "inline-flex", gap: 6, alignItems: "center" }}><span style={{ width: 16, height: 12, border: "1px solid var(--border-hairline)" }}></span><A.Meta>SKOLE</A.Meta></span></div>
      </section>}
      {empty && tab !== "tilg" ? <EmptyState icon="calendar-days" title="Ingen hendelser denne uka" text="Legg inn tilgjengelighet først. Da kan spillerne booke, og lagøkter kan legges oppå." action="Sett tilgjengelighet" actionIcon="clock" onAction={() => setTab("tilg")} /> : body}
    </A.Gate>
    <Sheet open={!!open} onClose={() => setOpen(null)} kicker={open ? KL[open.k] + " · " + C.days[open.d].join(" ") : ""} title={open ? open.title || KL[open.k] : ""} footer={open && (open.k === "ledig" ? <Button fullWidth icon="plus" onClick={() => { setOpen(null); go("AG-06", "ny"); }}>Book denne tiden</Button> : <><Button fullWidth variant="secondary" icon="move" onClick={() => { setMv(open); setMvTo(null); setOpen(null); }}>Flytt</Button><Button fullWidth variant="secondary" icon="pencil" onClick={() => setOpen(null)}>Endre hendelse</Button><Button fullWidth variant="ghost" onClick={() => setOpen(null)}>Lukk</Button></>)}>
      {open && <><div style={{ display: "flex", gap: 6, flexWrap: "wrap" }}>{(open.axis || []).map((a) => <AxisBadge key={a} axis={a} />)}</div><KeyValue items={[["Tid", hh(open.s) + "–" + hh(open.s + open.l)], ["Sted", open.where || null, { mono: false }], ["Lag", open.team || null, { mono: false }], ["Spillere", open.n || null], ["Coach", D.coach.name, { mono: false }]]} /><A.Meta>/ADMIN/KALENDER/HENDELSE/{open.id.toUpperCase()}</A.Meta></>}
    </Sheet>
    <MoveSheet open={!!mv} onClose={() => setMv(null)} item={mv ? mv.title || KL[mv.k] : ""} title="Ny tid" targets={slots(mv)} value={mvTo} onChange={setMvTo} note={mv && mv.k === "privat" ? "Spilleren får varsel og kan godta eller be om annen tid." : "Alle i laget får varsel når du flytter."} onConfirm={() => { const [d, s] = mvTo.split(":").map(Number); const e = mv; setMv(null); tryMove(e, d, s); }} />
    <ConflictSheet open={!!cf} onClose={() => setCf(null)} conflicts={cf ? cf.items : []} options={[{ id: "likevel", label: "Flytt likevel", description: "Begge hendelsene blir liggende. Spilleren ser konflikten." }, { id: "annen", label: "Velg annen tid" }]} onResolve={(o) => { const c = cf; setCf(null); if (o === "likevel") apply(c.e, c.d, c.s); else { setMv(c.e); setMvTo(null); } }} />
    <Sheet open={nu} onClose={() => setNu(false)} kicker="Ny hendelse" title="Legg til i kalenderen" footer={<><Button fullWidth icon="check" onClick={() => { setNu(false); A.toast("Hendelsen er lagt til", "SPILLERNE FÅR VARSEL NÅR DU PUBLISERER"); }}>Lagre</Button><Button variant="ghost" fullWidth onClick={() => setNu(false)}>Avbryt</Button></>}>
      <Select label="Type" options={["Lagøkt", "Privattime", "Opptatt", "Ledig tid"]} /><Select label="Lag" options={C.teams} /><Select label="Dag" options={C.days.map((d) => d.join(" "))} /><FormField label="Fra"><TextInput mono defaultValue="16:00" /></FormField><Select label="Varighet" options={["60 min", "90 min", "120 min"]} /><Select label="Akse" options={["FYS", "TEK", "SLAG", "SPILL", "TURN"]} />
    </Sheet>
  </A.Page>;
}
window.AG_SCREENS["AG-05"] = { id: "AG-05", name: "Kalender", route: "/admin/kalender", Component: AG05 };
})();
