(() => {
const TABS = ["godkjenning", "agent", "test", "dublett", "moderering", "epost"];
const LBL = { godkjenning: "Godkjenninger", agent: "Agentforslag", test: "Tester", dublett: "Dubletter", moderering: "Moderering", epost: "E-postutkast" };
const FIELDS = [["name", "Navn"], ["born", "Fødselsår"], ["email", "E-post"], ["phone", "Telefon"], ["club", "Klubb"], ["parent", "Forelder"]];
function AG02({ state, go, arg }) {
  const { PageHeader, Button, StatusPill, EmptyState, Tabs, Sheet, KeyValue, AxisBadge, Icon, Dialog, FormField, SortableList, MoveSheet } = window.AGQ.ns();
  const A = window.AGQ, D = window.AG_DATA, { mob, pad, desk, nav } = A.useW(), empty = state === "tom";
  const [prio, setPrio] = React.useState(false), [ord, setOrd] = React.useState({}), [mvP, setMvP] = React.useState(null), [mvTo, setMvTo] = React.useState(null);
  const [tab, setTab] = React.useState(TABS.includes(arg) ? arg : "godkjenning"), [sel, setSel] = React.useState(null), [res, setRes] = React.useState({}), [pick, setPick] = React.useState({}), [rm, setRm] = React.useState(false), [note, setNote] = React.useState(window.EPOST ? window.EPOST.DATA.coachNote : "");
  const lists = { godkjenning: D.approvals, agent: D.dispatch, test: D.tests, dublett: D.dups, moderering: D.mod, epost: [{ id: "ep5", to: "Mari Solvang", email: "mari.s@demo.no", tpl: "EP-05", by: "Jarvis", at: "26.09 15:05", svc: "Privattime 60 min · fredag 25.09 kl. 14:00", ready: "Klar til sending — timen var i går kl. 14.00" }] };
  const byOrd = (l) => ord[tab] ? [...l].sort((a, b) => ord[tab].indexOf(a.id) - ord[tab].indexOf(b.id)) : l;
  const items = empty ? [] : byOrd(lists[tab].filter((x) => !res[x.id]));
  const reorder = (ids) => { const before = ord; setOrd((o) => ({ ...o, [tab]: ids })); nav && nav.undo("Prioriteten er endret", "ØVERST BEHANDLES FØRST · KAN ANGRES", () => setOrd(before)); };
  const cur = items.find((x) => x.id === sel) || (desk ? items[0] : null);
  const close = (x, verb, meta) => { setRes((r) => ({ ...r, [x.id]: verb })); setSel(null); nav ? nav.undo(verb, meta, () => setRes((r) => { const n = { ...r }; delete n[x.id]; return n; })) : A.toast(verb, meta); };
  const row = (x) => {
    if (tab === "godkjenning") return [x.who + " · " + x.title, x.kind.toUpperCase() + " · FRA " + x.from.toUpperCase() + " · " + x.at, <StatusPill tone={x.status === "Signert" ? "ok" : "info"}>{x.status}</StatusPill>, x.axis];
    if (tab === "agent") return [x.title + " · " + x.who, x.agent.toUpperCase() + " · 26.09 " + x.t, <A.Draft />, [x.axis]];
    if (tab === "test") return [x.who + " · " + x.test, x.src + " · " + x.at, <StatusPill tone={x.done < x.of ? "warn" : "info"}>{x.done < x.of ? x.done + " av " + x.of + " slag" : "Til attestering"}</StatusPill>, ["slag"]];
    if (tab === "dublett") return [x.a.name + " / " + x.b.name, x.match.toUpperCase(), <StatusPill>Mulig dublett</StatusPill>, null];
    if (tab === "epost") return ["Takk etter timen · " + x.to, x.ready.toUpperCase() + " · " + x.tpl + " · IKKE SENDT", <A.Draft>Klar til sending</A.Draft>, null];
    return [x.where, x.reason, <StatusPill tone="warn">Skjult</StatusPill>, null];
  };
  const sortList = <div className="pa-card" style={{ padding: 8, gap: 0, minWidth: 0 }}>
    <div style={{ display: "flex", justifyContent: "space-between", gap: 8, flexWrap: "wrap", padding: "4px 8px 8px" }}><span className="kicker">Prioritet · {LBL[tab]}</span><A.Meta>DRA · PILTASTER · FLYTT</A.Meta></div>
    <SortableList label={"Prioritet " + LBL[tab]} items={items.map((x) => ({ ...x, label: row(x)[0] }))} onReorder={reorder} onMove={(it) => { setMvP(it); setMvTo(null); }} renderItem={(x, c) => { const [t0, m0] = row(x); return <div style={{ display: "flex", alignItems: "center", gap: 4, minHeight: 56, borderTop: c.index ? "1px solid var(--border-hairline)" : "none", background: c.dragging ? "var(--surface-sunken)" : "transparent" }}>{c.handle}<A.Meta s={{ width: 22, flex: "none" }}>{String(c.index + 1).padStart(2, "0")}</A.Meta><span style={{ flex: 1, minWidth: 0, display: "flex", flexDirection: "column", gap: 2 }}><span style={{ font: "500 14px/1.3 var(--font-sans)", color: "var(--text-primary)", overflowWrap: "anywhere" }}>{t0}</span><A.Meta>{m0}</A.Meta></span>{c.moveButton}</div>; }} />
    <p style={{ margin: "8px", font: "var(--type-body-s)", color: "var(--text-secondary)" }}>Godkjenn og avvis gjøres med knappene i detaljen, aldri ved å dra.</p>
  </div>;
  const list = prio && items.length > 1 ? sortList : <div className="pa-card" style={{ padding: 0, overflow: "hidden", minWidth: 0 }}>
    {items.map((x, i) => { const [t, m, pill, ax] = row(x), on = cur && cur.id === x.id; return <button key={x.id} type="button" aria-pressed={on} onClick={() => setSel(x.id)} style={{ all: "unset", boxSizing: "border-box", width: "100%", cursor: "pointer", display: "flex", gap: 12, alignItems: "center", padding: "12px 16px 12px 18px", minHeight: 64, position: "relative", borderTop: i ? "1px solid var(--border-hairline)" : "none", background: on ? "var(--surface-flat)" : "transparent", boxShadow: on ? "inset 2px 0 0 var(--border-ink)" : "none" }}>
      {ax && <span aria-hidden="true" style={{ position: "absolute", left: 0, top: 10, bottom: 10, width: 4, background: A.stripe(ax) }}></span>}
      <span style={{ flex: 1, minWidth: 0, display: "flex", flexDirection: "column", gap: 4 }}><span style={{ font: "500 14px/1.3 var(--font-sans)", color: "var(--text-primary)" }}>{t}</span><A.Meta>{m}</A.Meta></span>
      {!mob && pill}
    </button>; })}
  </div>;
  let body = null, foot = null;
  if (cur && tab === "godkjenning") { body = <><div style={{ display: "flex", gap: 6, flexWrap: "wrap" }}>{(cur.axis || []).map((a) => <AxisBadge key={a} axis={a} />)}<StatusPill tone={cur.status === "Signert" ? "ok" : "info"}>{cur.status}</StatusPill></div>
      <KeyValue items={[["Spiller", cur.who, { mono: false }], ["Gruppe", cur.grp, { mono: false }], ["Sendt av", cur.from + " · " + cur.at, { mono: false }], ["Frist", cur.due ? "I dag " + cur.due : null], ["Sammendrag", cur.sum, { mono: false }]]} />
      <div style={{ display: "flex", flexDirection: "column" }}>{cur.lines.map(([d, t, m], i) => <div key={i} style={{ display: "grid", gridTemplateColumns: "minmax(80px,auto) minmax(0,1fr) auto", gap: 10, padding: "10px 0", borderTop: "1px solid var(--border-hairline)", alignItems: "baseline" }}><A.Meta s={{ color: "var(--text-secondary)" }}>{d.toUpperCase()}</A.Meta><span style={{ font: "var(--type-body-s)", color: "var(--text-primary)" }}>{t}</span><span style={{ font: "var(--type-num-s)" }}>{m}</span></div>)}</div></>;
    foot = <><Button fullWidth icon="check" onClick={() => close(cur, "Godkjent", (cur.who + " · " + cur.title).toUpperCase() + " · SPILLEREN FÅR BESKJED")}>{cur.kind === "Samtykke" ? "Registrer samtykke" : "Godkjenn"}</Button><Button variant="secondary" fullWidth onClick={() => close(cur, "Sendt tilbake med kommentar", "UTKAST TIL MELDING I INNBOKS")}>Send tilbake</Button></>; }
  if (cur && tab === "agent") { body = <><div style={{ display: "flex", gap: 8, alignItems: "center", flexWrap: "wrap" }}><Icon name={cur.icon} size={16} /><A.Meta s={{ color: "var(--text-secondary)" }}>{cur.agent.toUpperCase()} · 26.09 {cur.t}</A.Meta><A.Draft /></div>
      <p style={{ margin: 0, font: "var(--type-body)", color: "var(--text-primary)", textWrap: "pretty" }}>{cur.body}</p>
      <KeyValue items={cur.facts.map(([k, v, s]) => [k, v, { hint: s }]).concat([["Går ut som", cur.out, { mono: false }]])} />
      <A.Meta>JARVIS SENDER OG ENDRER INGENTING SELV</A.Meta></>;
    foot = <><Button fullWidth icon="check" onClick={() => close(cur, "Godkjent av deg", cur.out.toUpperCase())}>Godkjenn og send</Button><Button variant="secondary" fullWidth icon="pencil" onClick={() => A.toast("Åpnet som utkast", "ENDRE FØR DU GODKJENNER")}>Rediger utkast</Button><Button variant="ghost" fullWidth onClick={() => close(cur, "Forslaget er avvist", "INGENTING SENDT")}>Avvis</Button></>; }
  if (cur && tab === "test") { const full = cur.done >= cur.of; body = <><KeyValue items={[["Spiller", cur.who, { mono: false }], ["Test", cur.test, { mono: false }], ["Resultat", full ? cur.result : null, { hint: full ? cur.src + " · " + cur.at : "TELLER BARE MED ALLE SLAG" }], ["Forrige", cur.prev], ["Registrert", cur.done + " av " + cur.of + " slag"], ["Vitne", cur.witness === "—" ? null : cur.witness, { mono: false }]]} />
      {!full && <div style={{ display: "flex", gap: 8, alignItems: "flex-start", padding: 12, borderRadius: 8, background: "var(--warn-tint)" }}><span style={{ color: "var(--warn)", display: "inline-flex", paddingTop: 2 }}><Icon name="triangle-alert" size={16} /></span><span style={{ font: "var(--type-body-s)", color: "var(--text-primary)" }}>{cur.of - cur.done} slag mangler. Testen teller først når alle slag er registrert.</span></div>}</>;
    foot = full ? <><Button fullWidth icon="shield-check" onClick={() => close(cur, "Testen er attestert", (cur.who + " · " + cur.result).toUpperCase())}>Attester resultat</Button><Button variant="ghost" fullWidth onClick={() => close(cur, "Sendt tilbake", "SPILLEREN TAR TESTEN PÅ NYTT")}>Be om ny test</Button></> : <Button variant="secondary" fullWidth icon="message-square" onClick={() => A.toast("Utkast til påminnelse i Innboks", "IKKE SENDT")}>Påminn spilleren</Button>; }
  if (cur && tab === "dublett") { const p = pick[cur.id] || {}; body = <><p style={{ margin: 0, font: "var(--type-body-s)", color: "var(--text-secondary)" }}>{cur.match}. Velg hvilken verdi som beholdes per felt. Historikk fra begge beholdes.</p>
      <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>{FIELDS.map(([k, l]) => { const va = cur.a[k], vb = cur.b[k], same = va === vb, ch = p[k] || (va === "—" ? "b" : "a"); return <div key={k} style={{ display: "flex", flexDirection: "column", gap: 6 }}><A.Meta>{l.toUpperCase()}{same ? " · LIK" : ""}</A.Meta>
        <div role="radiogroup" aria-label={l} style={{ display: "grid", gridTemplateColumns: "repeat(2,minmax(0,1fr))", gap: 6 }}>{["a", "b"].map((s) => { const v = cur[s][k], on = same ? s === "a" : ch === s; return <button key={s} type="button" role="radio" aria-checked={on} disabled={same || v === "—"} onClick={() => setPick((x) => ({ ...x, [cur.id]: { ...p, [k]: s } }))} style={{ minHeight: 44, textAlign: "left", padding: "6px 10px", borderRadius: 6, border: "1px solid " + (on ? "var(--border-ink)" : "var(--border-hairline)"), boxShadow: on ? "inset 0 0 0 1px var(--border-ink)" : "none", background: "var(--surface-card)", color: v === "—" ? "var(--text-muted)" : "var(--text-primary)", font: "var(--type-body-s)", overflowWrap: "anywhere", cursor: same || v === "—" ? "default" : "pointer", minWidth: 0 }}>{v}</button>; })}</div></div>; })}</div>
      <div style={{ display: "grid", gridTemplateColumns: "repeat(2,minmax(0,1fr))", gap: 6 }}><A.Meta>A · {cur.a.src.toUpperCase()}</A.Meta><A.Meta>B · {cur.b.src.toUpperCase()}</A.Meta></div></>;
    foot = <><Button fullWidth icon="git-merge" onClick={() => close(cur, "Profilene er slått sammen", cur.a.name.toUpperCase() + " · KAN ANGRES I 30 DAGER")}>Slå sammen</Button><Button variant="ghost" fullWidth onClick={() => close(cur, "Merket som ikke dublett", "BEGGE PROFILER BEHOLDES")}>Ikke dublett</Button></>; }
  if (cur && tab === "moderering") { body = <><KeyValue items={[["Hvor", cur.where, { mono: false }], ["Skrevet av", cur.who, { mono: false }], ["Meldt", cur.reason, { mono: false }], ["Tid", cur.at]]} /><div style={{ padding: 12, borderRadius: 8, background: "var(--surface-sunken)", font: "var(--type-body-s)", color: "var(--text-secondary)" }}>{cur.text}</div><A.Meta>NAVN VISES IKKE · DELTAKERE ER UNDER 18</A.Meta></>;
    foot = <><Button variant="secondary" fullWidth onClick={() => close(cur, "Innlegget er synlig igjen", "MELDINGEN ER LUKKET")}>Behold innlegget</Button><Button variant="ghost" fullWidth icon="trash-2" onClick={() => setRm(true)}>Fjern innlegget</Button></>; }
  if (cur && tab === "epost") { const r = window.EPOST.render("EP-05", { note }); body = <><div style={{ display: "flex", gap: 8, alignItems: "center", flexWrap: "wrap" }}><A.Draft>Klar til sending</A.Draft><span style={{ font: "500 14px/1.3 var(--font-sans)" }}>{cur.ready}</span></div><KeyValue items={[["Til", cur.to + " · " + cur.email, { mono: false }], ["Gjelder", cur.svc, { mono: false }], ["Mal", "EP-05 · Takk etter coachingtime", { mono: false }], ["Emne", r.subject, { mono: false }]]} />
      <FormField label="Dine linjer til kunden" hint="To–tre linjer om hva dere jobbet med. Vises i e-posten under «Fra Anders Kristiansen»."><textarea aria-label="Dine linjer til kunden" value={note} onChange={(e) => setNote(e.target.value)} style={{ width: "100%", boxSizing: "border-box", minHeight: 96, padding: 12, borderRadius: 8, border: "1px solid var(--border-control)", background: "var(--surface-card)", color: "var(--text-primary)", font: "var(--type-body)", resize: "vertical" }} /></FormField>
      <A.Meta>FORHÅNDSVISNING · SLIK KUNDEN SER DEN</A.Meta><iframe title="Forhåndsvisning av e-post" srcDoc={r.html} style={{ width: "100%", height: 720, border: "1px solid var(--border-hairline)", borderRadius: 8, background: "var(--white)" }}></iframe><A.Meta>LAGET AV {cur.by.toUpperCase()} {cur.at} · KLAR INNEN 24 TIMER ETTER TIMEN · INGENTING SENDES AUTOMATISK · RESERVASJONSLENKE ER MED</A.Meta></>;
    foot = <><Button variant="signal" fullWidth icon="send" disabled={!note.trim()} onClick={() => close(cur, "E-posten er sendt", ("TIL " + cur.to + " · EP-05").toUpperCase())}>Send</Button><Button variant="ghost" fullWidth onClick={() => close(cur, "Utkastet er forkastet", "INGENTING SENDT")}>Forkast</Button></>; }
  const detail = cur && <A.Card pad={mob ? 16 : 20} gap={16}><div><span className="kicker">{LBL[tab]}</span><div style={{ font: "var(--type-title-s)", color: "var(--text-primary)", marginTop: 4 }}>{row(cur)[0]}</div></div>{body}<div style={{ display: "flex", flexDirection: "column", gap: 8 }}>{foot}</div></A.Card>;
  const cnt = (t) => empty ? undefined : lists[t].filter((x) => !res[x.id]).length;
  return <A.Page>
    <PageHeader kicker={"Kø · " + D.dayLabel} title="Kø" sub="Alt som venter på en beslutning fra deg. Ingenting sendes før du godkjenner." actions={<Button variant="secondary" icon={prio ? "check" : "arrow-up-down"} onClick={() => setPrio(!prio)}>{prio ? "Ferdig med prioritet" : "Sorter prioritet"}</Button>} />
    <MoveSheet open={!!mvP} onClose={() => setMvP(null)} item={mvP && mvP.label} title="Ny plass i køen" targets={items.map((x, i) => ({ id: String(i), label: "Plass " + (i + 1), meta: row(x)[0].toUpperCase(), disabled: mvP && x.id === mvP.id }))} value={mvTo} onChange={setMvTo} onConfirm={() => { const ids = items.map((x) => x.id).filter((id) => id !== mvP.id); ids.splice(+mvTo, 0, mvP.id); reorder(ids); setMvP(null); }} />
    <A.Gate state={state} loading="Henter køen …" error={{ title: "Køen kunne ikke hentes", text: "Ingen saker er godkjent eller avvist. Prøv igjen.", code: "FEIL 502 · KØ" }}>
      <Tabs tabs={TABS.map((t) => ({ value: t, label: LBL[t], count: cnt(t) }))} value={tab} onChange={(t) => { setTab(t); setSel(null); }} />
      {items.length === 0 ? <EmptyState icon="check" title={"Ingen " + LBL[tab].toLowerCase() + " venter"} text={empty ? "Køen er tom. Nye saker kommer fra spillere, foreldre og agentene." : "Alt i denne fanen er behandlet."} action="Til Hjem" actionIcon="house" onAction={() => go("AG-01")} />
        : desk ? <A.Cols tpl="minmax(0,1fr) minmax(0,1.1fr)">{list}{detail}</A.Cols> : <>{list}<Sheet open={!!cur} onClose={() => setSel(null)} kicker={LBL[tab]} title={cur ? row(cur)[0] : ""} footer={foot}>{body}</Sheet></>}
    </A.Gate>
    <Dialog open={rm} onClose={() => setRm(false)} title="Fjerne innlegget?" footer={<><Button variant="ghost" onClick={() => setRm(false)}>Avbryt</Button><Button variant="signal" onClick={() => { setRm(false); close(cur, "Innlegget er fjernet", "DELTAKEREN FÅR BESKJED"); }}>Fjern</Button></>}><p style={{ margin: 0, font: "var(--type-body)" }}>Innlegget slettes for alle deltakere. Dette kan ikke angres.</p></Dialog>
  </A.Page>;
}
window.AG_SCREENS["AG-02"] = { id: "AG-02", name: "Kø", route: "/admin/ko", Component: AG02 };
})();
