(() => {
const AG = window.AGQ;
const sg = (v) => v == null ? "—" : (v > 0.04 ? "+" : v < -0.04 ? "−" : "±") + Math.abs(v).toFixed(1).replace(".", ",");
const toPar = (d) => d > 0 ? "+" + d : d < 0 ? "−" + Math.abs(d) : "±0";
const KI = { Trening: "flag", Reise: "bus", Treningsrunde: "map", Utstyr: "backpack", "Ernæring": "utensils", "Søvn": "moon", FYS: "dumbbell" };
const TT = { Trening: "neutral", Utvikling: "info", Prestasjon: "solid" };

/* AG-WB-TURN · Turneringsmodul i Workbench. Årsplan → turnering → forberedelse → dager → mål → etter. PlayerHQ: PH-WB-TURN. */
function AGWBTURN({ state, go, nav }) {
  const { PageHeader, Button, IconButton, StatusPill, EmptyState, DataTable, KeyValue, Sheet, FormField, TextInput, Select, InlineAlert, ActionBar, ConfirmDialog, MoveSheet, ConflictSheet, DropZone, SourceBadge, ChoicePill, Switch, Icon, Checkbox } = AG.ns();
  const { Card, Head, Meta, useW, toast } = AG, { mob, desk, wide } = useW(), D = window.WB_DATA, T = D.turn, empty = state === "tom";
  const [mvT, setMvT] = React.useState(null), [mvW, setMvW] = React.useState(null), [dragT, setDragT] = React.useState(null);
  const moveT = (id, w) => { const x = list.find((y) => y.id === id); if (!x || x.w === w) return; const clash = list.find((y) => y.id !== id && Math.abs(y.w - w) < 1); if (clash) { setCf({ id: null, items: [{ kind: "belastning", text: "Uke " + w + " har allerede " + clash.name + ".", meta: "TURNERINGSPROGRAM" }], t: { id, w } }); return; } const before = list; setList((l) => l.map((y) => y.id === id ? { ...y, w } : y)); dirty(); nav && nav.undo("Turnering flyttet", (x.name + " → uke " + w).toUpperCase(), () => setList(before)); };
  const [sel, setSel] = React.useState("t1"), [tab, setTab] = React.useState("Forberedelse"), [prep, setPrep] = React.useState(T.prep), [list, setList] = React.useState(T.list);
  const [st, setSt] = React.useState("idle"), [pub, setPub] = React.useState(false), [wd, setWd] = React.useState(false), [add, setAdd] = React.useState(false), [addP, setAddP] = React.useState(false), [mv, setMv] = React.useState(null), [mvTo, setMvTo] = React.useState(null), [cf, setCf] = React.useState(null), [drag, setDrag] = React.useState(null), [ev, setEv] = React.useState(T.after.eval);
  const t = list.find((x) => x.id === sel) || list[0];
  const dirty = () => { setSt("dirty"); nav && nav.setDirty(true); };
  const snap = (msg, meta, fn) => nav && nav.undo(msg, meta, fn);
  const moveTo = (id, day, force) => { const p = prep.find((x) => x.id === id); if (!p || p.day === day) return;
    const items = [];
    if (day >= 5) items.push({ kind: "kalender", text: D.days[day] + " er turneringsdag. Forberedelse må ligge før runde 1.", meta: "TURNERING · " + t.name.toUpperCase() });
    if (p.kind === "Treningsrunde" && day < 3) items.push({ kind: "belastning", text: "Treningsrunde tre dager før gir lang dag og mindre restitusjon.", meta: "PLANMOTOR" });
    if (day === 3 && p.kind !== "Reise") items.push({ kind: "kalender", text: "Tor 01.10: reise til Larvik kl. 15:00.", meta: "REISE" });
    if (!force && items.length) { setCf({ id, day, items }); return; }
    const before = prep; setPrep((l) => l.map((x) => x.id === id ? { ...x, day } : x)); dirty(); snap("Forberedelse flyttet", (p.what + " → " + D.days[day]).toUpperCase(), () => setPrep(before)); };
  const save = (partial) => { setSt("saving"); setTimeout(() => { setSt("saved"); nav && nav.setDirty(false); toast(partial ? "Delvis lagret" : "Lagret", "IKKE PUBLISERT"); }, 400); };
  const season = <Card><Head k="Turneringer i perioden" aside={<Meta>UKE 40–44 · SPESIALPERIODE → KONKURRANSE</Meta>} />
    <div role="list" style={{ display: "flex", flexDirection: "column" }}>{list.map((x, i) => <div key={x.id} role="listitem" draggable={desk} onDragStart={(e) => { e.dataTransfer.setData("application/x-ak-turn", x.id); setDragT(x.id); }} onDragEnd={() => setDragT(null)} onDragOver={(e) => dragT && e.preventDefault()} onDrop={(e) => { e.preventDefault(); const id = e.dataTransfer.getData("application/x-ak-turn"); setDragT(null); if (id) moveT(id, x.w); }} style={{ display: "flex", alignItems: "center", gap: 4, opacity: dragT === x.id ? .45 : 1, outline: dragT && dragT !== x.id ? "1px dashed var(--border-strong)" : "none", borderRadius: "var(--radius-inner)" }}><button type="button" aria-pressed={x.id === sel} onClick={() => setSel(x.id)} style={{ all: "unset", cursor: "pointer", flex: 1, minWidth: 0, display: "grid", gridTemplateColumns: "56px minmax(0,1fr) auto", gap: 10, alignItems: "center", minHeight: 56, padding: "8px 8px", borderTop: i ? "1px solid var(--border-hairline)" : "none", borderRadius: "var(--radius-inner)", background: x.id === sel ? "var(--surface-hover)" : "transparent", boxShadow: x.id === sel ? "inset 2px 0 0 var(--border-ink)" : "none" }}>
      <span style={{ font: "600 12px/1.2 var(--font-mono)", color: "var(--text-secondary)" }}>UKE {x.w}</span>
      <span style={{ display: "flex", flexDirection: "column", gap: 2, minWidth: 0 }}><span style={{ font: "500 14px/1.3 var(--font-sans)", color: "var(--text-primary)", overflowWrap: "anywhere" }}>{x.name}</span><Meta>{x.date} · {x.course.toUpperCase()}</Meta></span>
      <StatusPill tone={TT[x.type]}>{T.types[x.type]}</StatusPill>
    </button><IconButton icon="move" label={"Flytt " + x.name} onClick={() => { setMvT(x); setMvW(null); }} /></div>)}</div>
    <div role="list" aria-label="Konflikter" style={{ display: "flex", flexDirection: "column", gap: 6, padding: 12, borderRadius: "var(--radius)", background: "var(--warn-tint)" }}><span style={{ font: "600 13px/1.3 var(--font-sans)" }}>{T.conflictsAll.length} konflikter i programmet</span>{T.conflictsAll.map((c) => <div role="listitem" key={c.text} style={{ display: "flex", flexDirection: "column", gap: 2 }}><span style={{ font: "var(--type-body-s)" }}>{c.text}</span><Meta>{c.meta}</Meta></div>)}</div>
  </Card>;
  const header = <Card><Head k={T.types[t.type]} aside={<SourceBadge source={t.src.split(" · ")[0]} date={t.src.split(" · ").pop()} kind={t.src.startsWith("GOLFBOX") ? "golfbox" : "manuell"} />} />
    <div style={{ font: "var(--type-title-m)", color: "var(--text-primary)", overflowWrap: "anywhere" }}>{t.name}</div>
    <KeyValue columns={mob ? 1 : 2} items={[["Datoer", t.date], ["Bane", t.course, { mono: false }], ["Tee", t.tee], ["Format", T.format[t.id] || null, { mono: false }], ["Reisedager", (T.travel[t.id] || []).join(", ") || null], ["Runder", String(t.rounds)], ["Periode", "Turneringsuke " + t.w, { mono: false }], ["Status", sent(t) ? "Publisert" : t.status, { mono: false }]]} />
  </Card>;
  function sent(x) { return x.status === "Publisert"; }
  const prepBoard = <div style={{ display: "grid", gridTemplateColumns: mob ? "minmax(0,1fr)" : wide ? "repeat(7,minmax(0,1fr))" : "repeat(auto-fill,minmax(160px,1fr))", gap: mob ? 8 : 6 }}>{D.days.map((d, di) => { const items = prep.filter((p) => p.day === di), rd = T.rounds.find((r) => r.day === di);
    return <DropZone key={di} label={d} accept={["application/x-ak-prep"]} valid={!drag || di < 5} reason="TURNERINGSDAG" onDrop={(id) => moveTo(id, di)} minHeight={mob ? 44 : 180} empty="—">
      <span style={{ font: "600 12px/1.2 var(--font-mono)", color: "var(--text-primary)", display: "flex", gap: 4, flexWrap: "wrap", justifyContent: "space-between" }}><span>{d.toUpperCase()}</span>{D.days2[di].travel && <span style={{ color: "var(--text-muted)" }}>REISE</span>}{D.days2[di].school && <span style={{ color: "var(--text-muted)" }}>SKOLE</span>}</span>
      {rd && <div style={{ padding: 8, borderRadius: "var(--radius-inner)", background: "var(--surface-inverse)", color: "var(--text-inverse)", display: "flex", flexDirection: "column", gap: 2 }}><span style={{ font: "600 13px/1.2 var(--font-sans)" }}>{rd.r}</span><span style={{ font: "500 11px/1 var(--font-mono)" }}>TEE {rd.tee} · {rd.start.toUpperCase()}</span></div>}
      {items.map((p) => <div key={p.id} draggable={desk} onDragStart={(e) => { e.dataTransfer.setData("application/x-ak-prep", p.id); setDrag(p.id); }} onDragEnd={() => setDrag(null)} style={{ display: "flex", alignItems: "stretch", borderRadius: "var(--radius-inner)", border: "1px solid var(--border-hairline)", background: "var(--surface-card)", opacity: drag === p.id ? .45 : 1, minWidth: 0, overflow: "hidden" }}>
        <span aria-hidden="true" style={{ width: 4, flex: "none", background: p.kind === "FYS" ? "var(--axis-fys)" : p.kind === "Trening" || p.kind === "Treningsrunde" ? "var(--axis-turn)" : "var(--border-strong)" }}></span>
        <span style={{ flex: 1, minWidth: 0, padding: "8px 4px 8px 8px", display: "flex", flexDirection: "column", gap: 4 }}><span style={{ display: "flex", gap: 6, alignItems: "center", flexWrap: "wrap", font: "500 11px/1.2 var(--font-mono)", color: "var(--text-secondary)", overflowWrap: "anywhere" }}><Icon name={KI[p.kind] || "circle"} size={14} />{p.kind.toUpperCase() + (p.min ? " · " + p.min + " MIN" : "")}</span><span style={{ font: "500 13px/1.25 var(--font-sans)", color: "var(--text-primary)", overflowWrap: "anywhere" }}>{p.what}</span>{!p.pub && <Meta>IKKE SYNLIG FOR SPILLER</Meta>}</span>
        <IconButton icon="move" label={"Flytt " + p.what} onClick={() => { setMv(p); setMvTo(null); }} />
      </div>)}
    </DropZone>; })}</div>;
  let body;
  if (tab === "Forberedelse") body = <Card><Head k={"Turneringsuke " + t.w + " · forberedelse"} aside={<Meta>{desk ? "DRA TIL NY DAG · ELLER FLYTT" : "TRYKK FLYTT"}</Meta>} />{prepBoard}<div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}><Button variant="secondary" icon="plus" onClick={() => setAddP(true)}>Legg inn forberedelse</Button><Button variant="ghost" icon="layers" onClick={() => go("AG-11")}>Se i ukeplanen</Button><Button variant="ghost" icon="dumbbell" onClick={() => go("AG-WB-FYS")}>Juster fysisk plan</Button></div></Card>;
  if (tab === "Turneringsdager") body = <Card><Head k="Runder og dager" />
    <DataTable caption="Runder" rowKey="r" columns={[{ key: "r", label: "Runde" }, { key: "day", label: "Dag", mono: true, render: (r) => D.days[r.day] }, { key: "tee", label: "Tee", mono: true }, { key: "start", label: "Start" }, { key: "note", label: "Rutine" }]} rows={T.rounds} />
    <div style={{ display: "flex", flexDirection: "column", gap: 4 }}><span className="kicker">Synlig for spiller</span>{prep.map((p) => <Checkbox key={p.id} checked={p.pub} onChange={(e) => { setPrep((l) => l.map((x) => x.id === p.id ? { ...x, pub: e.target.checked } : x)); dirty(); }} label={p.what} />)}</div>
  </Card>;
  if (tab === "Mål og strategi") body = <AG.Cols tpl={desk ? "repeat(2,minmax(0,1fr))" : "minmax(0,1fr)"}>
    <Card><Head k="Prosessmål" aside={<SourceBadge source="Anders Kristiansen" date="25.09.2026" kind="coach" />} /><ol style={{ margin: 0, paddingLeft: 18, display: "flex", flexDirection: "column", gap: 6, font: "var(--type-body)" }}>{T.goals.process.map((g) => <li key={g}>{g}</li>)}</ol><KeyValue items={[["Resultatmål", T.goals.result, { mono: false }]]} /></Card>
    <Card><Head k="Strategi og gameplan" /><p style={{ margin: 0, font: "var(--type-body)", color: "var(--text-primary)", textWrap: "pretty" }}>{T.goals.strategy}</p><Meta>HULLKART ER EKSEMPELDATA · KOMPLETT BANEGUIDE ETTER LANSERING</Meta><div><Button variant="secondary" icon="map" onClick={() => toast("Gameplan åpnes i PlayerHQ", "PH-20 · " + t.course.toUpperCase())}>Åpne gameplan</Button></div></Card>
  </AG.Cols>;
  if (tab === "Etter turnering") { const A = T.after, tot = A.rounds.reduce((s, r) => s + r.gross, 0), par = A.rounds.reduce((s, r) => s + r.par, 0);
    body = <Card><Head k={"Evaluering · " + A.name + " · " + A.date} aside={<Meta>PLASSERING {A.place}</Meta>} />
      <DataTable caption="Runder" rowKey="r" columns={[{ key: "r", label: "Runde" }, { key: "gross", label: "Brutto", mono: true, align: "right", render: (r) => r.gross + " (" + toPar(r.gross - r.par) + ")" }, { key: "sg", label: "SG totalt", mono: true, align: "right", render: (r) => sg(r.sg) }, { key: "src", label: "Kilde", render: (r) => <SourceBadge source={r.src.split(" · ").slice(0, -1).join(" · ")} date={r.src.split(" · ").pop()} kind={r.src.startsWith("GOLFBOX") ? "golfbox" : "annen_app"} /> }]} rows={A.rounds} />
      <KeyValue columns={mob ? 1 : 3} items={[["Totalt brutto", tot + " (" + toPar(tot - par) + ")"], ["SG snitt", null, { hint: "MANGLER FOR RUNDE 2" }], ["Bane", A.course, { mono: false }]]} />
      <FormField label="Coachens evaluering"><textarea aria-label="Evaluering" value={ev} onChange={(e) => { setEv(e.target.value); dirty(); }} style={{ width: "100%", boxSizing: "border-box", minHeight: 96, padding: 12, borderRadius: "var(--radius)", border: "1px solid var(--border-control)", font: "var(--type-body)", background: "var(--surface-card)", color: "var(--text-primary)" }} /></FormField>
      <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}><Button variant="secondary" icon="plus" onClick={() => toast("Legg inn runde", "MANUELT ELLER FRA ANNEN APP · PH-18")}>Legg inn runde</Button><Button variant="secondary" icon="wand-2" onClick={() => go("AG-A06")}>Lag tiltak fra evalueringen</Button></div>
    </Card>; }
  return <AG.Page max={1440}>
    <PageHeader kicker="Workbench · Turneringer · Tobias Lindvik" title="Turneringsplan" meta={<span style={{ display: "inline-flex", gap: 8, alignItems: "center", flexWrap: "wrap" }}><StatusPill tone={sent(t) ? "ok" : "neutral"}>{sent(t) ? "Publisert" : "Utkast"}</StatusPill><span>{t.name.toUpperCase()}</span></span>}
      actions={<><Button variant="secondary" icon="plus" onClick={() => setAdd(true)}>Legg til turnering</Button>{sent(t) ? <Button variant="secondary" icon="undo-2" onClick={() => setWd(true)}>Trekk tilbake</Button> : <Button icon="send" disabled={state !== "data"} onClick={() => setPub(true)}>Publiser plan</Button>}</>} />
    <AG.Gate state={state} loading="Henter turneringer og forberedelse …" error={{ title: "Turneringsplanen kunne ikke hentes", text: "Ingen turneringer er endret. GolfBox-data hentes på nytt når du prøver igjen.", code: "FEIL 503 · WORKBENCH · TURN" }}>
      {empty ? <EmptyState icon="trophy" title="Ingen turneringer i perioden" text="Velg turneringer fra terminlisten eller legg inn manuelt. Forberedelse, dager og evaluering bygges rundt hver turnering." action="Legg til turnering" actionIcon="plus" onAction={() => setAdd(true)} /> : <>
      <AG.Cols tpl={desk ? "minmax(0,1fr) minmax(0,1.6fr)" : "minmax(0,1fr)"}>{season}<AG.Stack>{header}
        <div role="tablist" aria-label="Del av turneringen" style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>{["Forberedelse", "Turneringsdager", "Mål og strategi", "Etter turnering"].map((x) => <ChoicePill key={x} role="tab" aria-selected={tab === x} selected={tab === x} onClick={() => setTab(x)}>{x}</ChoicePill>)}</div>
      </AG.Stack></AG.Cols>
      {body}
      <ActionBar sticky={mob} status={st} statusMeta={st === "saved" ? "14:02" : undefined} secondary={<><Button variant="ghost" onClick={() => go("AG-11")}>Avbryt</Button><Button variant="secondary" onClick={() => save(true)}>Lagre delvis</Button></>} primary={<Button icon="check" onClick={() => save(false)}>Lagre</Button>} />
      </>}
    </AG.Gate>
    <MoveSheet open={!!mv} onClose={() => setMv(null)} item={mv && mv.what} title="Flytt forberedelse" targets={D.days.map((d, i) => ({ id: String(i), label: d, meta: prep.filter((p) => p.day === i).length + " PUNKTER", reason: i >= 5 ? "TURNERINGSDAG" : null, warn: i >= 5, disabled: mv && mv.day === i }))} value={mvTo} onChange={setMvTo} note="Spilleren ser endringen når planen publiseres." onConfirm={() => { const m = mv; setMv(null); moveTo(m.id, +mvTo); }} />
    <MoveSheet open={!!mvT} onClose={() => setMvT(null)} item={mvT && mvT.name} title="Flytt turnering" targets={[40, 41, 42, 43, 44, 45, 46].map((w) => { const c = list.find((y) => y.w === w && (!mvT || y.id !== mvT.id)); return { id: String(w), label: "Uke " + w, meta: c ? "HAR " + c.name.toUpperCase() : "LEDIG", warn: !!c, reason: c ? "ALLEREDE TURNERING · GIR KONFLIKT" : null, disabled: mvT && mvT.w === w }; })} value={mvW} onChange={setMvW} note="Forberedelsen flyttes med. Spilleren ser endringen når planen publiseres." onConfirm={() => { const m = mvT; setMvT(null); moveT(m.id, +mvW); }} />
    <ConflictSheet open={!!cf} onClose={() => setCf(null)} conflicts={cf ? cf.items : []} options={[{ id: "annen", label: "Velg annen dag" }, { id: "likevel", label: "Flytt likevel", description: "Konflikten vises i Kø." }]} onResolve={(o) => { const c = cf; setCf(null); if (c.t) { if (o === "likevel") { const before = list; setList((l) => l.map((y) => y.id === c.t.id ? { ...y, w: c.t.w } : y)); nav && nav.undo("Turnering flyttet", "UKE " + c.t.w, () => setList(before)); } else { setMvT(list.find((y) => y.id === c.t.id)); setMvW(null); } return; } if (o === "likevel") moveTo(c.id, c.day, true); else { setMv(prep.find((p) => p.id === c.id)); setMvTo(null); } }} />
    <Sheet open={add} onClose={() => setAdd(false)} kicker="Workbench · Turneringer" title="Legg til turnering" footer={<><Button fullWidth icon="check" onClick={() => { setAdd(false); const before = list; setList((l) => [...l, { id: "t" + Date.now(), name: "Vinterserie Mulligan", type: "Trening", date: "14.11.2026", w: 46, course: "Mulligan Indoor", tee: null, rounds: 1, src: "MANUELL · 26.09.2026", status: "Utkast" }]); snap("Turnering lagt til", "UKE 46 · UTKAST", () => setList(before)); }}>Legg til som utkast</Button><Button variant="ghost" fullWidth onClick={() => setAdd(false)}>Avbryt</Button></>}>
      <Select label="Velg fra terminliste" options={["Srixon Tour · runde 7 · 17.10 · GolfBox", "Region Øst finale · 17.10 · GolfBox", "Manuell turnering"]} />
      <Select label="Type" options={["Treningsturnering", "Utviklingsturnering", "Prestasjonsturnering"]} />
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(min(100%,140px),1fr))", gap: 12 }}><FormField label="Dato"><TextInput mono defaultValue="14.11.2026" /></FormField><FormField label="Runder"><TextInput mono inputMode="numeric" defaultValue="1" /></FormField><FormField label="Bane" optional><TextInput placeholder="—" /></FormField><FormField label="Tee" optional><TextInput placeholder="—" /></FormField></div>
      <InlineAlert tone="info" title="Kilde">Fra terminlisten hentes dato og bane fra GolfBox. Manuell turnering merkes «Manuell» med dato. Ingen ny API-integrasjon.</InlineAlert>
    </Sheet>
    <Sheet open={addP} onClose={() => setAddP(false)} kicker={"Forberedelse · " + t.name} title="Legg inn forberedelse" footer={<><Button fullWidth icon="plus" onClick={() => { setAddP(false); const before = prep; setPrep((l) => [...l, { id: "p" + Date.now(), day: 2, what: "Nærspill 20–40 m", kind: "Trening", min: 45, pub: true }]); dirty(); snap("Forberedelse lagt til", "ONS 30.09 · 45 MIN", () => setPrep(before)); }}>Legg til</Button><Button variant="ghost" fullWidth onClick={() => setAddP(false)}>Avbryt</Button></>}>
      <Select label="Type" options={["Trening", "Treningsrunde", "Innspillsrunde", "Reise", "Utstyr", "Ernæring", "Søvn og restitusjon", "FYS (lettere)"]} /><Select label="Dag" options={D.days.slice(0, 5)} /><FormField label="Hva"><TextInput defaultValue="Nærspill 20–40 m" /></FormField><Switch checked onChange={() => {}} label="Synlig for spiller" />
    </Sheet>
    <ConfirmDialog open={pub} kind="publish" title={"Publisere turneringsplanen for " + t.name + "?"} consequences={[prep.filter((p) => p.pub).length + " punkter blir synlige for Tobias i Plan og I dag.", prep.filter((p) => !p.pub).length + " punkt er bare for coach.", "Kan trekkes tilbake etterpå."]} onCancel={() => setPub(false)} onConfirm={() => { setPub(false); const before = list; setList((l) => l.map((x) => x.id === t.id ? { ...x, status: "Publisert" } : x)); snap("Turneringsplanen er publisert", "TIL TOBIAS LINDVIK", () => setList(before)); }} />
    <ConfirmDialog open={wd} kind="destructive" title="Trekke tilbake turneringsplanen?" confirmLabel="Trekk tilbake" consequences={["Forberedelsen fjernes fra Tobias sin plan.", "Tobias får beskjed om at planen er trukket."]} onCancel={() => setWd(false)} onConfirm={() => { setWd(false); const before = list; setList((l) => l.map((x) => x.id === t.id ? { ...x, status: "Utkast" } : x)); snap("Planen er trukket tilbake", "KAN ANGRES I 8 SEKUNDER", () => setList(before)); }} />
  </AG.Page>;
}
window.AG_SCREENS["AG-WB-TURN"] = { id: "AG-WB-TURN", name: "Workbench · turneringer", parent: "AG-11", route: "/admin/workbench/[playerId]?pille=turn", Component: AGWBTURN };
})();
