/* Informasjonsarkitektur 28.09.2026 (Anders, grillingen runde 8). Én kilde for skall, hurtigknapp, bjelle og oversikt.html.
   plassering: [menypunkt-id, sti]. utgar: skjermen går ut av menyen; gamle adresser sender videre til «til». */
window.AK_IA = {
  dato: "28.09.2026",
  phq: {
    tabs: [
      { id: "idag", label: "I dag", icon: "sun", to: "PH-01", sub: ["Dagens økter", "Agenda og oppgaver", "Live-økt (natt)", "Runde live (natt)"] },
      { id: "plan", label: "Plan", icon: "calendar-days", to: "PH-10", sub: ["År · Måned · Uke · Dag", "Rediger (Workbench)", "Lag: Fysisk · Turneringer · Samlinger · Opptatt tid · Google", "Velg treningsplan", "Øvelsesbank", "Teknisk plan", "Gameplan", "Målsetning"] },
      { id: "analyse", label: "Stats", icon: "chart-no-axes-column", to: "PH-16", sub: ["Snittscore", "Strokes Gained", "Trening", "Tester"] },
      { id: "meg", label: "Meg", icon: "user", to: "PH-24", sub: ["Profil", "Fasiliteter", "Bookinger", "Abonnement og betalingskort", "Foreldre", "Deling", "Helse og fravær", "Utstyr", "Min coach", "Venner og utfordringer", "Hjelp", "Innstillinger"] },
    ],
    fab: [
      { id: "caddie", label: "Spør Caddie", icon: "sparkles", to: "PH-22" },
      { id: "nyokt", label: "Ny økt", icon: "layers", to: "PH-11" },
      { id: "runde", label: "Registrer runde", icon: "flag", to: "PH-RD-01" },
      { id: "start", label: "Start økt", icon: "play", to: "PH-04" },
    ],
    bell: { to: "PH-21", label: "Innboks", count: 3 },
  },
  aos: {
    menu: [
      { id: "AG-01", label: "Cockpit", icon: "gauge", sub: ["Én ting nå", "Dagens plan", "Live-tavle"] },
      { id: "AG-04", label: "Innboks", icon: "inbox", sub: ["Meldinger", "Godkjenninger (Kø)", "Oppfølging", "Caddie-forslag", "Datakvalitet", "E-postutkast og maler"] },
      { id: "AG-07", label: "Stall", icon: "users", sub: ["Spillere", "Trenger oppfølging", "Grupper", "Sammenlign", "Spiller 360 · Stats · Teknisk plan · Tester"] },
      { id: "AG-05", label: "Kalender", icon: "calendar-days", sub: ["Uke/måned/dag", "Stall-dag", "Tilgjengelighet"] },
      { id: "AG-11", label: "Workbench", icon: "layers", sub: ["Plan per spiller og gruppe", "Fysisk", "Turneringer", "Maler og øvelser", "Tiltak"] },
      { id: "MER", label: "Mer", icon: "ellipsis", sub: [] },
    ],
    mer: [
      { id: "AG-06", label: "Booking", icon: "calendar-check" },
      { id: "AG-16", label: "Grupper", icon: "users-round" },
      { id: "AG-15", label: "Tester", icon: "clipboard-check" },
      { id: "AG-20", label: "Økonomi", icon: "wallet" },
      { id: "AG-23", label: "Oppsett", icon: "settings" },
    ],
    fab: [
      { id: "okt", label: "Ny økt i Workbench", icon: "layers", to: "AG-11" },
      { id: "melding", label: "Ny melding til spiller", icon: "message-square-plus" },
      { id: "runde", label: "Registrer runde", icon: "flag" },
      { id: "jarvis", label: "Spør Jarvis", icon: "sparkles", to: "AG-19" },
      { id: "booking", label: "Ny booking", icon: "calendar-plus", to: "AG-06" },
    ],
    bell: { to: "AG-04", label: "Innboks", count: 7 },
  },
  plassering: {
    "PH-01": ["idag", "I dag"], "PH-02": ["idag", "I dag (slått sammen med PH-01)"], "PH-03": ["idag", "I dag › Økt"],
    "PH-04": ["idag", "I dag › Start økt · natt"], "PH-05": ["idag", "I dag › Live-økt · natt"], "PH-06": ["idag", "I dag › Live-økt › Slagteller · natt"], "PH-07": ["idag", "I dag › Live-økt › Oppsummering · natt"],
    "PH-08": ["idag", "I dag › Runde live · natt"], "PH-09": ["analyse", "Hurtigknapp › Registrer runde (lagres i Stats › Snittscore)"],
    "PH-10": ["plan", "Plan (én flate, zoom År · Måned · Uke · Dag)"], "PH-11": ["plan", "Plan › Rediger"], "PH-12": ["plan", "Plan › Velg treningsplan (fem standardplaner, kategori A–K)"],
    "PH-13": ["plan", "Plan › Øvelsesbank"], "PH-14": ["analyse", "Stats › Tester"], "PH-15": ["analyse", "Stats › Tester › Gjennomfør · natt"],
    "PH-16": ["analyse", "Stats (start: Snittscore)"], "PH-17": ["analyse", "Stats › Trening › TrackMan"], "PH-18": ["analyse", "Stats › Snittscore › Runder"],
    "PH-19": ["plan", "Plan › Målsetning (talent «Min plan» og roadmap utgår)"], "PH-20": ["plan", "Plan › Turneringer › Gameplan (banekart senere)"],
    "PH-21": ["meg", "Bjella › Innboks · Meg › Coach (ukesdigest blir melding her)"], "PH-22": ["meg", "Hurtigknapp › Spør Caddie"], "PH-23": ["meg", "Meg › Booking"],
    "PH-24": ["meg", "Meg (utfordringer og venner flyttes hit)"], "PH-25": ["meg", "Meg › Abonnement og innstillinger"], "PH-27": ["meg", "Meg › Deling"], "PH-27-U16": ["meg", "Meg › Deling (under 16)"],
    "PH-WB-FYS": ["plan", "Plan › lag Fysisk (ikke egen side)"], "PH-WB-TURN": ["plan", "Plan › lag Turneringer › Turneringsreise (ikke egen side)"], "PH-TP-01": ["plan", "Plan › Teknisk plan"],
    "PH-RD-01": ["analyse", "Hurtigknapp › Registrer runde › Velg nivå"], "PH-RD-02": ["analyse", "Registrer runde › Oppsett"], "PH-RD-03": ["idag", "I dag › Runde live · natt"], "PH-RD-04": ["idag", "Runde live › Slag-for-slag · natt"], "PH-RD-05": ["idag", "Runde live › SG hittil · natt"],
    "PH-RD-06": ["analyse", "Registrer runde › Rask score"], "PH-RD-07": ["analyse", "Registrer runde › Import"], "PH-RD-08": ["analyse", "Stats › Snittscore › Runde"], "PH-RD-09": ["analyse", "Stats › Snittscore › Runde › Rediger"],
    "PH-A01": ["analyse", "Stats › Trening"], "PH-A02": ["analyse", "Stats › Trening › Belastning"], "PH-A03": ["analyse", "Stats › Trening › Øktkvalitet"], "PH-A04": ["analyse", "Stats › Trening › Slagdata"],
    "PH-A05": ["analyse", "Stats › Trening › Nærspill og putting"], "PH-A06": ["analyse", "Stats › Strokes Gained"], "PH-A07": ["analyse", "Stats › Tester › Utvikling"], "PH-A08": ["analyse", "Stats › Datagrunnlag"],
    "AG-01": ["AG-01", "Cockpit (startskjerm)"], "AG-02": ["AG-04", "Innboks › Godkjenninger (Kø er ikke eget menypunkt)"], "AG-03": ["AG-04", "Innboks › Oppfølging"], "AG-04": ["AG-04", "Innboks"],
    "AG-05": ["AG-05", "Kalender"], "AG-06": ["MER", "Mer › Booking · Hurtigknapp › Ny booking"], "AG-07": ["AG-07", "Stall"], "AG-08": ["AG-07", "Stall › Spiller 360"], "AG-08-IUP": ["AG-07", "Stall › Spiller 360 › IUP"], "AG-08-PLAN": ["AG-07", "Stall › Spiller 360 › Plan"], "AG-05-UKE": ["AG-05", "Kalender › Uke"], "AG-11-GRUPPE": ["AG-11", "Workbench › Gruppe"], "AG-11-AR": ["AG-11", "Workbench › År"], "AG-11-OKT": ["AG-11", "Workbench › Økt"], "AG-11-MAL": ["AG-11", "Workbench › Målsetninger"], "AG-11-FYS": ["AG-11", "Workbench › Fysisk program"], "PH-11-MAL": ["plan", "Plan › Rediger › Målsetninger"], "AG-05-MND": ["AG-05", "Kalender › Måned"], "AG-05-AR": ["AG-05", "Kalender › År"], "AG-05-ASS": ["AG-05", "Kalender (assistant coach)"], "AG-04-HASTER": ["AG-04", "Innboks"], "PH-15-TN": ["plan", "Stats › Tester › Team Norway-test"], "AG-08-TALENT": ["AG-07", "Stall › Spiller 360 › Talent"],
    "AG-09": ["AG-07", "Stall › Spiller 360 › Stats (slås sammen med AG-A02)"], "AG-10": ["AG-07", "Stall › Spiller 360 › Teknisk plan"], "AG-TP-01": ["AG-07", "Spiller 360 › Teknisk plan › Oppgave"], "AG-TP-02": ["AG-07", "Spiller 360 › Teknisk plan › Før og nå"],
    "AG-11": ["AG-11", "Workbench"], "AG-12": ["AG-11", "Workbench › Økt"], "AG-13": ["AG-01", "Cockpit › Start live › Live coachingøkt"], "AG-13-U": ["AG-01", "Cockpit › Live coachingøkt (uten samtykke)"], "AG-14": ["AG-11", "Workbench › Maler og øvelser"],
    "AG-15": ["MER", "Mer › Tester (tildel, normer, TrackMan-økter)"], "AG-16": ["MER", "Mer › Grupper · gruppeplan i Workbench"], "AG-17": ["AG-11", "Workbench › Turneringer · spillerens Plan"], "AG-18": ["AG-07", "Stall › Spiller 360 › Samtaler"],
    "AG-19": ["AG-01", "Hurtigknapp › Spør Jarvis"], "AG-20": ["MER", "Mer › Økonomi"], "AG-21": ["AG-01", "Cockpit › Oppgaver fra Notion"], "AG-22": ["AG-07", "Stall › Sammenlign"], "AG-23": ["MER", "Mer › Oppsett"], "AG-24": ["MER", "Mer › Oppsett › Logger og GDPR"], "AG-06-NY": ["MER", "Mer › Booking › Ny booking"], "AG-20-ASS": ["MER", "Ikke i Mer for assistant coach"], "AG-23-TEAM": ["MER", "Mer › Oppsett › Team"],
    "AG-WB-FYS": ["AG-11", "Workbench › Fysisk"], "AG-WB-TURN": ["AG-11", "Workbench › Turneringer"], "AG-RD-01": ["AG-07", "Spiller 360 › Stats › Runder"], "AG-RD-02": ["AG-04", "Innboks › Datakvalitet"],
    "AG-A01": ["AG-07", "Stall › Trenger oppfølging (Innsikt er ikke eget menypunkt)"], "AG-A02": ["AG-07", "Stall › Spiller 360 › Stats"], "AG-A03": ["AG-07", "Stall › Grupper › Stats"], "AG-A04": ["AG-07", "Spiller 360 › Stats › Plan mot faktisk"],
    "AG-A05": ["AG-04", "Innboks › Datakvalitet"], "AG-A06": ["AG-11", "Workbench › Tiltak"], "AG-A07": ["AG-07", "Utgår 28.09 · ikke i navigasjonen"], "AG-A08": ["AG-04", "Innboks › Caddie-forslag"],
  },
  utgar: {
    "AG-A07": "Utgår 28.09 · Rapportbyggeren fjernes, ikke i navigasjonen (runde 30)",
    "AG-17": "Utgår 28.09 · turneringer ligger i Workbench og Plan (runde 30)", "AG-18": "Utgår 28.09 · videoer og opptak ligger i Spiller 360 › Samtaler (runde 30)", "AG-24": "Utgår 28.09 · Drift er slått inn i Oppsett (runde 30)",
    "AG-A01": "Utgår 28.09 · ingen egen Stats-side for coach; Stats bor i Spiller 360 og Grupper (runde 28)",
    "AG-09": "Utgår 28.09 · Spilleranalyse er Stats-fanen i Spiller 360 (runde 27)", "AG-22": "Utgår 28.09 · Talentradar er Talent-fanen i Spiller 360 (runde 27)",
    "AG-02": "Utgår 28.09 · Kø er slått inn i Innboks › Godkjenn (runde 26)", "AG-03": "Utgår 28.09 · Oppfølgingskøen er filter under Innboks › Oppfølging (runde 26)",
    "AG-21": "Utgår 28.09 · oppgaver fra Notion ligger i Cockpit (runde 25)",
    "PH-A01": "Utgår 28.09 · slått inn i Stats › Trening (runde 22)", "PH-A02": "Utgår 28.09 · Stats › Trening", "PH-A03": "Utgår 28.09 · Stats › Trening", "PH-A04": "Utgår 28.09 · Stats › Trening (TrackMan)", "PH-A05": "Utgår 28.09 · Stats › Strokes Gained", "PH-A06": "Utgår 28.09 · Stats › Snittscore", "PH-A07": "Utgår 28.09 · Stats › Tester", "PH-A08": "Utgår 28.09 · nok data-merking i hver del av Stats",
    "PH-02": "Utgår 28.09 · slått sammen med PH-01 I dag (runde 20). Gjentok bare dagens økter; oppgavene fra coach ligger i agendaen. /portal/gjennomfore, /portal/tren/wb og /portal/live → /portal",
    "PH-26": "Utgår 28.09 · «Utenfor banen» er ikke egen side. /portal/utenfor-banen → I dag · /portal/fysisk og /portal/tren/fys-plan → Plan › Fysisk · /portal/tren/turneringer* → Plan › Turneringer · /portal/utfordringer* → Meg · /portal/ukesdigest → Innboks (melding) · putte-lab → Stats › Trening",
  },
  delvis: {
    "PH-10": "Utgår 28.09: egen kalender (/portal/kalender → Plan › Uke)",
    "PH-12": "Utgår 28.09: AI-planbygger (/portal/ai/mal-bygger → Plan › Velg treningsplan). Ingen AI-planbygger for spilleren ved lansering",
    "PH-19": "Utgår 28.09: talent «Min plan» og roadmap (/portal/talent/*, /portal/utviklingsplan → Plan › Målsetning)",
  },
  kilde: [
    ["Ytelsesbilde", "Stats › Snittscore"], ["Kategori A–K", "Stats › Snittscore"], ["Strokes Gained", "Stats › Strokes Gained"],
    ["Treningsanalyse", "Stats › Trening"], ["TrackMan", "Stats › Trening"], ["Ferdighetstest", "Stats › Tester"],
    ["Baseline", "Oppstart (AU-04)"], ["Onboarding", "Oppstart (AU-04)"], ["Stall-matrise", "AgencyOS › Stall"], ["Øvelse", "AgencyOS › Workbench"],
    ["Banekart", "Senere (etter lansering)"], ["Mål og dagens økt", "Plan › Målsetning · I dag"], ["Kalender", "Plan › Uke"], ["Gameplan", "Plan › Turneringer › Gameplan"],
  ],
  treningsplaner: ["Weekend Warrior", "Klubbspilleren", "Junior-aspirant", "Konkurransespilleren", "Practice like the pros"],
};
