-- Granulære SG-felter på Round (jf. taksonomien TRENINGSOMRADER)
-- Applied: 2026-05-16

ALTER TABLE "rounds"
  ADD COLUMN "sgTee"        DOUBLE PRECISION,
  ADD COLUMN "sgApp200"     DOUBLE PRECISION,
  ADD COLUMN "sgApp150"     DOUBLE PRECISION,
  ADD COLUMN "sgApp100"     DOUBLE PRECISION,
  ADD COLUMN "sgApp50"      DOUBLE PRECISION,
  ADD COLUMN "sgChip"       DOUBLE PRECISION,
  ADD COLUMN "sgPitch"      DOUBLE PRECISION,
  ADD COLUMN "sgLob"        DOUBLE PRECISION,
  ADD COLUMN "sgBunker"     DOUBLE PRECISION,
  ADD COLUMN "sgPutt0_3"    DOUBLE PRECISION,
  ADD COLUMN "sgPutt3_5"    DOUBLE PRECISION,
  ADD COLUMN "sgPutt5_10"   DOUBLE PRECISION,
  ADD COLUMN "sgPutt10_15"  DOUBLE PRECISION,
  ADD COLUMN "sgPutt15_25"  DOUBLE PRECISION,
  ADD COLUMN "sgPutt25_40"  DOUBLE PRECISION,
  ADD COLUMN "sgPutt40plus" DOUBLE PRECISION;
